### ISSUE TITLE
repo_checker: delete check should take into account requests in same group

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1009]
The delete check carried over from the previous checker is a bit too simplistic since it does not take into account the effect of other requests in the same group. Meaning that if package `a` depends on `b` and both have `delete` requests in the same group there should be no issue, but currently the checker will complain that `b` depends on `a` since it looks at the results in the main project.

If anything the simplest way to handle this would be to check the staging project first and use the result if available and otherwise fallback to the project. Likely that is sufficient. Any other issues will be handled by the `installcheck`.

Somewhat related to #277 as the same logic will need to be applied when implementing the run-time check.

**Comment by jberry-suse** [comment]
Closed related https://progress.opensuse.org/issues/10814 as duplicate.

**Comment by nilxam** [comment]
Another case I see:

> Dec 12 08:10:18 repochecker osrt-repo-checker[1210]: [W] qt3 is still a build requirement of qt3-extensions, qt3-devel-doc
> Dec 12 08:10:18 repochecker osrt-repo-checker[1210]: [D] previous comment too similar on 554754
> Dec 12 08:10:18 repochecker osrt-repo-checker[1210]: [I] 554754 ignored

qt3-extensions, qt3-devel-doc both are sub-package of qt3, we really need to work this issue out asap...

**Comment by jberry-suse** [comment]
Unless I misremember, this is the same logic used for years in previous checker.

**Comment by nilxam** [comment]
yep, you're right, I think just the message on the request confuses people as it's its own sub-package.

**Comment by nilxam** [comment]
some more detail is that, with the old r-c if a delete request has nothing to rely on eg. https://build.opensuse.org/request/show/512644 and https://build.opensuse.org/request/show/511462 , r-c has the capability accepting the request, back to qt3 case, it has nothing to rely on it in Leap 15.0, r-c should should able to approve it however r-c thinks its own sub-package is not in the same group.
