### ISSUE TITLE
repo_checker: include duplicate binaries check

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1031]
As noted in #1030 it might make sense to post comments on packages producing duplicate binaries. Given the similar functionality is being added to `repo_checker` for uninstallable issues it likely makes sense to just include duplicate binaries check in the `repo_checker` as it would seem to make sense to be a blocking issue and would resolve the workflow issues surrounding it.

**Comment by coolo** [comment]
#2081 blocks duplicated binaries for staging projects
