### ISSUE TITLE
repo_checker: handle staging changes after review accepted

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1038]
In the case that the `repo_checker` has completed review of all requests in a staging and then changes are made to the staging all requests should be rechecked. Previously, the old `repo_checker` could approve before even staged so this was not really fixable, but now it should be doable. @DimStar77 suggested some sort of project level attribute that marks the staging as dirty or somesuch. The details of when the individual reviews are accepted vs if the mark is used to block the accept command or what need to be worked out, but definitely seems worth doing.

**Comment by lnussel** [comment]
a rather simple workaround would be to reset certain reviews if a package gets selected elsewhere

**Comment by jberry-suse** [comment]
If by that you mean all (or at least one) in a staging group why any package changes are made then yes. Merely on the package being changed does not work for a staging that was happy and then had packages removed from it. Additionally, this does not handle prjconf/meta changes or re-freezing.

**Comment by jberry-suse** [comment]
Another case, could be a package introducing a problem is staged...fails to build due to transient issue (fairly common) and the previous version had no issue. Repo-checker could then accept review and after a rebuild the problem is introduced and would never be re-reviewed. Not even a staging select performed.

**Comment by coolo** [comment]
> The fact that the repository state is misleading presented as representing the current source state is the issue.

I agree. And for staging projects, the repository check should help.

**Comment by coolo** [comment]
Fixed as part of staging-installcheck
