### ISSUE TITLE
Tidy OBS staging permissions

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1043]
As I do not have access I would ask someone who does make these changes, preferably prior to the 14th. See #1006 for overview of where this is originates.

## OBS

- create `release-tools` group
- add the following users to `release-tools` group
  - factory-repo-checker (to be removed post 14th deployment)
  - leaper
  - repo-checker
  - totest-manager
- add `release-tools` to `openSUSE:{Factory,Leap:15.0}:Staging/dashboard` as maintainer
- remove the three existing users now in the group from the dashboard maintainers

### evaluate

Need to confirm the following changes are alright.

- drop `ancorgs` and `aplanas` from `openSUSE:Factory:Staging/dashboard` maintainers
- drop `factory-auto` from `factory-staging` group (or demote to `release-tools` if writing to dashboard)

**Comment by lnussel** [comment]
created: osc api /group/release-tools-maintainers

**Comment by jberry-suse** [comment]
Thanks for creating the group and looks like you dropped the two extra users from Factory/dashboard.

- added `release-tools-maintainers` to `openSUSE:{Factory,Leap:15.0}:Staging/dashboard` as maintainer
- confirmed that repo-checker is able to write to dashboard

Will save the following for Monday deployment to keep the possible disruptions limited to same timeframe.

- remove the three existing users now in the group from the dashboard maintainers
- drop `factory-auto` from `factory-staging` group (or demote to `release-tools-maintainers` if writing to dashboard)

**Comment by jberry-suse** [comment]
Should also drop `factory-repo-checker` from all projects in which it is a maintainer as the current workflow does not require that and once disabled just another user with a lot of access.

**Comment by jberry-suse** [comment]
The other aspect to consider are the bots that require review permission on the target project. Perhaps `release-tools-reviewers` that way new projects just need those two groups added to grant all the relevant permissions to bots.

**Comment by jberry-suse** [comment]
`factory-repo-checker` is still in charge of superseding duplicate requests. Should either move to another user if possible, perhaps `factory-auto` as it does not relate to `repo-checker`.

**Comment by coolo** [comment]
isn't repo checker also the one rebuilding failed deps in O:F?

**Comment by jberry-suse** [comment]
Partially, standardizing around `staging-bot` for non-review related actions. See #1176.

**Comment by jberry-suse** [comment]
`pkglist` service runs are `factory-repo-checker` which would be another likely source for needing maintainer.

**Comment by lnussel** [comment]
Are we done here?

**Comment by jberry-suse** [comment]
Still need to migrate the services running as `factory-repo-checker` for dashboard access. That and make a decision about group vs user for reviews going forward and standardize.

**Comment by coolo** [comment]
I just checked and factory-repo-checker is nowhere maintainer, but it's part of the release-tools-maintainers group. I removed it there now as I can't find any service running under that user, we should be fine.
