### ISSUE TITLE
update-crawler: fetch requests already

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1048]
so far update crawler only submits packages that are already checked in. Speed things up it should have an additional mode to submit packages that have an open request already. There should be some grace period before it submits to make sure other bots had a  chance to do automated review, or we even wait until e.g. repochecker is done.

**Comment by jberry-suse** [comment]
Since this likely needs a new processing path based on requests instead of commits it may make sense to use similar xpath based filter to https://github.com/openSUSE/osc-plugin-factory/blob/1cefbfce343b280ea1e9db2af5b06a0382502582/osclib/request_splitter.py#L476-L480.
