### ISSUE TITLE
select: --merge do not re-stage requests that were manually removed

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1053]
It likely makes sense to blacklist such requests from entering the same staging again.

![image](https://user-images.githubusercontent.com/22943929/29284683-5424da56-80f1-11e7-95cb-d71b07f9b40c.png)

**Comment by coolo** [comment]
When they are unselected with a reason, they stay in the backlog. And we don't run with staging-bot atm, so it seems a rather fancy problem to have
