### ISSUE TITLE
repo_checker: provide repo arch context on devel comments

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1055]
The comments on these packages are seemingly incorrect, but actually they are correct.

- [vegastrike-extra](https://build.opensuse.org/package/show/games/vegastrike-extra)
- [vegastrike-music](https://build.opensuse.org/package/show/games/vegastrike-music)
- [vegastrike-speech](https://build.opensuse.org/package/show/games/vegastrike-speech)

```
can't install vegastrike-extra-0.5.1.r1-7.4.noarch:
  nothing provides vegastrike-data >= 0.5.1.r1 needed by vegastrike-extra-0.5.1.r1-7.4.noarch
```

I even checked the caches:

```
rpm -qp ~/.cache/opensuse-repo-checker/openSUSE\:Factory/standard/x86_64/b8e583726f99f2e75c5f96093d935923-vegastrike-data.rpm
vegastrike-data-0.5.1.r1-8.4.noarch
```

The trick is that `vegastrike-data` has `ExcludeArch:    %{ix86}`, but the other packages that depend on it do not. As such in the `i586` repo those packages are not installable. The maintainer was as confused as I was at first. The staging comments already have the arch context, but due to the new method used for parsing and merging the problems for posting on devel packages that context was not preserved. I have considered utilizing the parsing for the staging comments as well. Merging these two code paths likely makes sense.

**Comment by jberry-suse** [comment]
Should also update `binary_list_existing_problem()` to utilize the arch information when done.

**Comment by coolo** [comment]
We don't do these devel comments any more - possibly we should reintroduce them, but we would rather have them as part of the build fail reminder
