### ISSUE TITLE
repo_checker: consider ensuring that no new issues were added as part of snapshot testing

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1063]
Another [mail regarding install-time deps was sent to opensuse-factory](https://lists.opensuse.org/opensuse-factory/2017-08/msg00433.html). The new `repo-checker` had [already commented on the devel package](https://build.opensuse.org/package/show/devel:languages:haskell/pandoc), but nothing prevents the snapshot from being released. Considering the huge swath of packages not included in rings problems like this are not too hard to get past the staging process.

Perhaps:

- `repo_checker` result from previous snapshot could be stored somewhere
- openqa could include a test that compares output for the previous snapshot against the current one to ensure no new issues were introduced

Alternatively, the check could be performed at other stages in the workflow, but not sure where it is the most visible.

I understand that some packages break and are not fixed immediately, but seems like its something that should be explicitly acknowledged before going out the door. For problems like this that affect a variety of packages post a big change it would seem desirable to avoid users having to run into these problems. After all we try to test everything else under the sun.

It's rather jarring to receive such a message when trying to update and from experience helping others it does not improve their perception of quality and stability. If a package is in Factory it ought to at least be installable.

**Comment by jberry-suse** [comment]
To be clear during the last week, over 50 new packages (not counting subpackages) were affected by installation issues in Factory. Granted the new repo-checker has only been enforcing for the last day, but many of these changes seem to appear due to not being rings.

**Comment by lnussel** [comment]
Are some of those errors a result of rebuild=local? Maybe rebuildpacs.pl needs to gain some additional heuristics to just try to rebuild affected packages.

**Comment by coolo** [comment]
@DimStar77 has a different policy on Factory - a package that doesn't build (the most frequent source of uninstallable packages - rebuildpac.pl won't help them) will be flagged and if the maintainer doesn't react within X weeks, it's removed.

So "If a package is in Factory it ought to at least be installable." might sound like a noble goal, in reality it's just not feasable.

So I would say this is to be closed, but it's Dimstar's call.

**Comment by DimStar77** [comment]
I tend to agree: having oS:F 100% error free as a criteria to release a snapshot is utopic.

We should rather push on things like https://github.com/openSUSE/openSUSE-release-tools/pull/1951 so we can shorten the times between things failed and how long we accept the broken stuff in Factory.

**Comment by jberry-suse** [comment]
"no new issues" != "no issues"

The idea here was to require a human to ignore the highlighted issue just as it done with openQA tests.

**Comment by coolo** [comment]
Can you name an example? Because your initial example is just a build failure as I expressed: https://lists.opensuse.org/opensuse-factory/2017-08/msg00445.html

Because again, if it can be solved by rebuilding, we should rebuild.

**Comment by jberry-suse** [comment]
At this point no, but if we spent some time grepping mailing list there are reported examples and I've encountered others that are not reported. If we care to resolve this, which it does not sound like, then perhaps worth the effort to find some.

**Comment by DimStar77** [comment]
we have rebuldpacs that 'detects problems and triggers rebuilds' - whenever it finds a package that is no longer installable (changed deps, mainly soname changes) - if the build then fail, it's out of luck

**Comment by coolo** [comment]
Well, you can construct cases that are only for humans to check.

E.g. a package buildrequires a provides that after the latest checkin is provided by something else - and if that *something else* is providing that provide, the package will create different provides - required for some 3rd package that was also added during that checkin.

Now rebuilding the lowest and the highest package won't help, only the package in the middle would. rebuildpacs can potentially figure this out, but it's a little big of a challenge compared to passing every new uninstallable through a human. And if we can remove build failure caused problems from that repo checker reports (as we should, also if we want to mail developers with those), it could be useful.

But still, the corner cases are so academical compared to build failure caused problems, that I still consider it WONTFIX. 

Having these reports as part of the tumbleweed status for people to check upfront before updating: different story.
