### ISSUE TITLE
repo_checker: cleanup/report back on devel packages once problems corrected

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1074]
With the addition of a comments API for retrieving own comments (openSUSE/open-build-service#3618), tracked in #1060, it should be simple to cleanup comments that are no longer relevant.

Given maitainers typically discuss problems as replies to the `repo_checker` comment it will leave a deleted parent comment based on standard `ReviewBot.write_comment()` behavior. It may also make sense to post an affirmative `Previously reported problems have been resolved` as I have started doing in staging projects to be clear that things are fine. Those comments could also be removed after a period of time.

Alternatively, the comments could never be removed and only replaced the next time a problem with that package is encountered.

**Comment by jberry-suse** [comment]
Re-visited this and found new API lacking. Reported on OBS issue.

**Comment by jberry-suse** [comment]
In lieu of OBS ever including parent entity in self comment API (should be near trivial) could parse the content since `repo_checker` includes a link to the package that should be enough context to know where the comment was posted. As such `repo_checker` could request all comments it made, loop through them and only look at comments for the current project and drop those that are either a) old-style comments, or b) no longer present.

**Comment by jberry-suse** [comment]
Then the only question is should it post a "Previously reported problems have been resolved." message like it does for stagings or just delete the comment?

**Comment by coolo** [comment]
we no longer have these comments in devel projects
