### ISSUE TITLE
repo_checker: delete: ignore bundle-lang-* for depends_on check

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1083]
The `bundle-lang-*` packages contain auto-generated `BuildRequires` that should be ingored for the purposes of a delete check. Likely makes sense to make a remote config list of prefixes to ignore.

**Comment by DimStar77** [comment]
https://build.opensuse.org/request/show/591113 will void this issue - TW is the last product still using bundle-lang-* packages, I'd say it's not worth investing time in changing the tooling
