### ISSUE TITLE
osc staging: possibility to merge two staging projects

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/openSUSE-release-tools#1105]
Every now and then, it would be handy to be able to 'merge' two staging projects (more commonly on adi, but sometimes also on letter stagings)

maybe any of our overly complex syntax options already does it - but I could not work out a set :)

Something like: osc staging merge adi:25 adi:65 -> move all packages from adi:25 to adi:65

(currently I do this using a shell function:

```
adimerge () 
{ 
    osc ls openSUSE:Factory:Staging:adi:$1 | xargs osc staging select --move openSUSE:Factory:Staging:adi:$2
}
```

)

**Comment by jberry-suse** [comment]
Overly complex eh? The closest proposal is #731, but I remember discussing this idea before as it is seemingly common and useful.

**Comment by DimStar77** [comment]
Just for the record - over time I have improved my `adimerge` command, as the original one did not cope with multi-spec packages.

Currently, I use:

```
adimerge is a function
adimerge () 
{ 
    osc review list openSUSE:Factory -P openSUSE:Factory:Staging:adi:$1 | awk '/State:review/ {print $1}' | xargs osc staging select --move openSUSE:Factory:Staging:adi:$2
}
```

**Comment by coolo** [comment]
That's actually pretty close to what I would have suggested. `osc staging select --move adi:24 adi:25` - and teach the request finder to look into staged requests.
