### ISSUE TITLE
update-crawler: duplicate requests

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1111]
Seen on patterns-caasp it was submitted from the devel project to sle15. looks like the same sources were later submitted to Factory too and thecked it. After that update-crawler didn't see the sle15 submission as identical anymore. Looks like srcmd5 changed while sources are the same. A solution could be to always call _get_source_package(), not just if the rev in the request is decimal.

**Comment by lnussel** [comment]
important to fix for sle15

**Comment by jberry-suse** [comment]
Could have sworn we had an issue for this, but apparently not. Have some semi-similar, but not this.

**Comment by jberry-suse** [comment]
This is due to the silly assumption made where it only looks for identical requests from same source and target instead of same sources. The replacement code only looks at sources.
