### ISSUE TITLE
factory-announcer: fails if being redirected to a https site

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/openSUSE-release-tools#1135]
Factory-announcer has trouble following redirects if there is https involved.

At the moment, I get these redirects:

> curl -vL https://download.opensuse.org/tumbleweed/iso/Changes.20170908.txt -o dummy 2>&1 | grep Location
< Location: http://opensuse.ucom.am/tumbleweed/iso/Changes.20170908.txt
< Location: https://opensuse.ucom.am/tumbleweed/iso/Changes.20170908.txt

a) Factory announcer only follows the first redirect
b) Factory-announcer is hard coded to connect on port 80

**Comment by coolo** [comment]
I worked around that now by retrieving the changes file from downloadcontent
