### ISSUE TITLE
repo_checker: detect old-school "multi-build" subpackage rename and ignore all binaries from target project

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1137]
A case occurred in Factory of a package with multiple spec files having one of them renamed. The repo_checker has no way to know that it should ignore the binaries from all the previous state of spec files in target project and instead looks for the renamed package in the target project which does not exist so only binaries from the non-renamed packages are ignored.

Short of always making API calls for all updated packges this seems a bit cumbersome to deal with. Interestingly the new `_multibuild` style packages work just fine with this setup since all the binaries produced are associated with a single OBS package container. It almost begs if there are any technical reasons remaining to prevent all such packages from being ported to `_multibuild` as logically it simplifies a number areas the staging tools currently have to deal with or lack.

Perhaps one approach would be to look for all packages in target project that are links to other packages in target project and keep a lookup map. Anytime a request for a package (root package) exists then automatically ignore all binaries from subpackages. Even if the subpackages are detected and ignored a second time the net ignore `set()` would be correct in both the rename and non-rename case without having to explicitly detect it.

The possible edge-case is for packages that do not have all their subpackages duplicated in the rings. Ignoring the ones not built in rings may cause unresolveable install-time dependencies. Obviously this would be another case for enforcing install-time deps to be resolved within rings.

Overall, short of the install-time deps rule being enforced for rings solving this with code may simple trade one problem for another. From what I can see prioritizing `_multibuild` and install-time deps resolved within rings solves both of these problems without requiring a tooling change. Obviously, one of the implications of `_mulitbuild` conversion would be building all subpackages which again seems consistent, but may require discussion.

**Comment by jberry-suse** [comment]
To be clear subpackage renames within a single spec file are handled correctly, but renaming a non-primary spec can trigger this problem. For example:

- somepackage
  - somepackage.spec
  - somepackage-variant.spec

If a request changed that package to provide the following specs the problem can occur.

- somepackage
  - somepackage.spec
  - somepackage_variant.spec (dash to underscore)

Even if the same names are used for binaries the `repo_checker` would see `somepackage_variant` package in the staging and ignore any binaries produced by that package in target project which of course would be none and thus likely to have file conflicts with identically named packages from `somepackage-variant`.

In the case that a set of sub-packages are renamed I would expect obsoletes or conflicts to be present and this to be a non-issue. So really this seems like a very special case.

**Comment by DimStar77** [comment]
we MUST have the capability to have sub-packages split across rings - and _multibuild currently does not allow this (witthout adding 'patched' _multibuild files into the ring, which I really don't want to see)

Just look at glibc in ring0: would you really want to build all it's subpackages (incl. -testsuite) inside ring0? Bootstrap would become insanely large and impossible to handle.

This is basically what https://github.com/openSUSE/open-build-service/issues/3227 is about

**Comment by jberry-suse** [comment]
Thanks, the split subpackages across rings explains why we cannot use `_multibuild` cleanly. To be clear the split subpackages already works with `repo_checker` as is. It's the renaming without renaming the actually binaries produced that causes an issue. I would expect that to be rather rare, but you likely have a better idea. Either way I agree if we are to keep using old-school multi-spec packages this needs to work. Having that OBS issue resolved would seem preferable as it renaming would work and the split would continue to work.

If this change is rare, like it would seem, I would suggest this is low priority to fix, but if renaming a spec file and not the binaries produced is common then this need to fix more urgently. From what I remember the old checker would have had issues with this as well which further leads me to believe it is rare.

**Comment by DimStar77** [comment]
I agree to put it as low prio - I don't think it's a very common thing that will happen

**Comment by coolo** [comment]
as we filled the leaks of the rings, we no longer have this problem. At least not in installcheck

**Comment by jberry-suse** [comment]
adi still layers target project and would be subject to this problem

**Comment by coolo** [comment]
then let's say WONTFIX
