### ISSUE TITLE
carry-over build state fails to work when adi command supersedes the request

### ISSUE THREAD

**Issue by nilxam** [openSUSE/openSUSE-release-tools#1141]
libstorage-ng got superseded many times in Factory Staging:E, it got superseded by user/bot, however we sometimes see the build state doesn't carry-over, I dig into it today and find the root cause(it should be), as libstorage-ng is a non-rings package, adi command tries process it although the request was staged in a letter staging.

from staging-bot log,
<pre>
Sep 19 11:01:19 packagelists staging-bot[31198]: adi:274 broken: ghc-download, ghc-fortran-src, ghc-hslua, ghc-inline-r
Sep 19 11:01:19 packagelists staging-bot[31198]: adi:298 broken: rubygem-bundler
Sep 19 11:01:20 packagelists staging-bot[31198]: Base:System
Sep 19 11:02:20 packagelists staging-bot[31198]: - 527250 u-boot                         (staged in openSUSE:Factory:Staging:adi:5)
Sep 19 11:02:20 packagelists staging-bot[31198]: GNOME:Apps
Sep 19 11:02:26 packagelists staging-bot[31198]: - 527243 geany-plugins                  (staged in openSUSE:Factory:Staging:adi:105)
Sep 19 11:02:27 packagelists staging-bot[31198]: Java:packages
Sep 19 11:02:32 packagelists staging-bot[31198]: - 527235 jgraphx                        (staged in openSUSE:Factory:Staging:adi:106)
Sep 19 11:02:37 packagelists staging-bot[31198]: - 527240 jgroups                        (staged in openSUSE:Factory:Staging:adi:106)
Sep 19 11:02:42 packagelists staging-bot[31198]: - 527244 jlatexmath                     (staged in openSUSE:Factory:Staging:adi:106)
Sep 19 11:02:46 packagelists staging-bot[31198]: - 527245 velocity                       (staged in openSUSE:Factory:Staging:adi:106)
Sep 19 11:02:51 packagelists staging-bot[31198]: - 527253 postgresql-jdbc                (staged in openSUSE:Factory:Staging:adi:106)
Sep 19 11:02:51 packagelists staging-bot[31198]: YaST:Head
Sep 19 11:02:54 packagelists staging-bot[31198]: WARNING:root:openSUSE:Factory:Staging:E/libstorage-ng not in ring, build disabled
Sep 19 11:03:00 packagelists staging-bot[31198]: - 527260 libstorage-ng                  (superseded)
Sep 19 11:03:00 packagelists staging-bot[31198]: devel:languages:haskell
Sep 19 11:05:50 packagelists staging-bot[31198]: - 527237 ghc-bifunctors                 (staged in openSUSE:Factory:Staging:adi:107)
Sep 19 11:05:56 packagelists staging-bot[31198]: - 527238 ghc-libinfluxdb                (staged in openSUSE:Factory:Staging:adi:107)
Sep 19 11:05:59 packagelists staging-bot[31198]: devel:languages:python
Sep 19 11:06:07 packagelists staging-bot[31198]: - 527256 python-sphinxcontrib-issuetracker (staged in openSUSE:Factory:Staging:adi:108)
Sep 19 11:06:08 packagelists staging-bot[31198]: multimedia:apps
Sep 19 11:06:15 packagelists staging-bot[31198]: - 527251 gradio                         (staged in openSUSE:Factory:Staging:adi:109)
Sep 19 11:06:29 packagelists staging-bot[31198]: Empty proposal
</pre>

https://build.opensuse.org/request/show/527242 got superseded by https://build.opensuse.org/request/show/527260 , due to it's adi command, `dispatch_open_requests()` does not called, therefor `self._supersede` does not be set to True, the following `self.update_superseded_request()` will not carry-over the build state.

**Comment by jberry-suse** [comment]
:(

**Comment by coolo** [comment]
I have the feeling that this is resolved
