### ISSUE TITLE
No permissions when checking for duplicated submit requests

### ISSUE THREAD

**Issue by jordimassaguerpla** [openSUSE/openSUSE-release-tools#1150]
If you run "osc check_dups PROJECT" on a project where there are SR from other users, you will get an error about insufficient permissions, which is fine because you should not try to supersede others SR.

I think it would be better to only check for SR which belong to the current user.

**Comment by DimStar77** [comment]
I doubt check_dups is useful to use against random devel projects - there you want to handle the requetss and accept them in order - with the risk that one accepted SR will break the other (generally requiring a rebase due to changelog)

**Comment by jberry-suse** [comment]
Should be closed after #1151.
