### ISSUE TITLE
botmaster: employ log monitoring for various services to detect errors

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1186]
Given the importance of these services at minimum some basic alerting should be setup to notify re-occurring errors. There have been a number of instances where bots were failing to do something over and over, but nothing is done until someone notices.

**Comment by jberry-suse** [comment]
[IT Ticket #94035](https://infra.nue.suse.com/Ticket/Display.html?id=94035)

**Comment by coolo** [comment]
I can't see that IT ticket, but assuming nothing has happened there. botmaster is mirrored for running server and running agents - but the pipelines themselves are not monitored. Problem is that some of them are bound to report an error - even if it's reported elsewhere.

**Comment by coolo** [comment]
I wonder how we can do that. We definitely still notice too late if a service keeps failing - we need botmaster to monitor itself somehow.

**Comment by coolo** [comment]
First step: I enabled "Breaks" notification on gocd for myself.

**Comment by coolo** [comment]
Those emails turned out to be very useful to find seldom crashes. And everyone (from SUSE, sorry) can add notifications for pipelines of interest. There are more pipelines failing than what are problems (e.g. build failures blocking further stages), but those are easy to ignore.
