### ISSUE TITLE
packagelists: disable source-checker.service in favor of leaper

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1192]
Currently, the service would appear to be obsolete:

```
/usr/local/bin/check_source_in_factory --factory openSUSE:Factory --factory openSUSE:Leap:42.2:Update --factory openSUSE:Leap:42.2 --factory openSUSE:Leap:42.1:Update --factory openSUSE:Leap:42.1 --review-mode=fallback-onfail --fallback-group=backports-reviewers --verbose review
```

@lnussel Can you confirm? `leaper` internally uses this `FactorySourceChecker` so presumably this service is not needed anymore as it was likely a precursor. This also means I can drop it in #1006 and #1185.

**Comment by lnussel** [comment]
Must have missed this one. I think this service is used by maintenance and/or backports. Certainly it would make sense to adjust leaper for them

**Comment by jberry-suse** [comment]
Should be droppable after completion and migration to origin manager.
