### ISSUE TITLE
discussion: formally rename repository to openSUSE-release-tools

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1209]
Likely best done after #1185 to avoid needing to change git remotes where deployed, but seems like would be a benefit to clarity about what is actually in this repository at this point. Any major issues with this?

**Comment by DimStar77** [comment]
no Major concern; we 'just' don't really know what systems/workflows we break by doing so. Not everybody is speaking up here; we should try to keep at least a README on the old repo name (giving hints how to change to the new location after rename); for a couple weeks/months.

**Comment by kraih** [comment]
Renaming a repo on GitHub is pretty straight forward these days, i don't think too much would break. Web traffic is redirected and git operations still work on the old location. https://help.github.com/articles/renaming-a-repository/

**Comment by coolo** [comment]
yes, no problems expected

**Comment by jberry-suse** [comment]
Well, I'm game. Just need to decide when and who has permission and will push the button.

**Comment by jberry-suse** [comment]
Great! Thanks.

**Comment by jberry-suse** [comment]
Perhaps as a follow-up can the description be changed?

https://github.com/openSUSE/openSUSE-release-tools/blob/a8b760de4cb6a4c1b78abad3961039e4cc65a033/dist/package/openSUSE-release-tools.spec#L25

**Comment by jberry-suse** [comment]
Also, this killed coveralls.io integration.

**Comment by jberry-suse** [comment]
Bump, someone with admin access is needed for the remaining two bits.

- [ ] change repository description to match package (see above)
- [ ] setup the new project linking to coveralls.io (or use alternative)

**Comment by jberry-suse** [comment]
Leaving things half baked isn't the best.

**Comment by lnussel** [comment]
you are admin now

**Comment by jberry-suse** [comment]
https://coveralls.io/github/openSUSE/openSUSE-release-tools (dropped another 1% since our last builds)

**Comment by jberry-suse** [comment]
2 minutes flat...not bad, after 3 months :/
