### ISSUE TITLE
repo_checker: provide devel project run for maintainers

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1210]
Given this check will just be noise for most devel projects and many issues with when to run it when devel projects are in flux, just provide an option to run manually and print output directly.

```
./repo_checker.py project_only --devel GNOME:Factory openSUSE_Factory
```

**Comment by DimStar77** [comment]
Probably needs a bit 'more logic' - as devel projects traditionally do not have a 'standard' repository

**Comment by jberry-suse** [comment]
Yeah, but as you suggested just pass in the repo to review. So need to replace `standard` in code with variable the defaults to `standard` for non-devel and detect target project from repo path. Not sure if we need to support chain building against another project that then points to target distro.

**Comment by DimStar77** [comment]
chained repos is something quite standard:

DEVEL project building against openSUSE:Tumbleweed/standard for example; oS:TW/standard is chained to oS:F/snapshot

**Comment by jberry-suse** [comment]
Then being able to layer > 2 projects (supported which I added for DVD) will be needed in `repo_checker.pl`.

**Comment by DimStar77** [comment]
Spinning this a bit further, it might be even beneficial for a developer if he could run it against a 'package' (or a group of packages) - like

check DEVEL PRJ/PKG and get upfront information if this would be satisfiable. Possibly multiple packages together would be the solution; the good thing would be for the dev to have this info upfront, before he submits his stack

**Comment by jberry-suse** [comment]
Having the packages check against Factory directly then?

**Comment by DimStar77** [comment]
> Having the packages check against Factory directly then?

Hmm. yes, or with a user-defined target... 

usecase 1: I want to check a full devel prj stack which I'm planning on submitting:
  repo_checker develprj GNOME:Factory openSUSE_Factory
This should check all packages built in GNOME:Factory, repository openSUSE_Factory, as an overlay over the 'path statements' in prj meta, giving me hints of what is going wrong if this were to be merged

Usecase 2: in 'mixed devel projects', I might only care for some packages (or knowingly not submit all together):
  repo_checker pkgcheck GNOME:Factory/openSUSE_Factory gnome-games --target openSUSE:Factory/standard
=> simulate -games built in GNOME:Factory repo openSUSE_Factory to be overlayed over openSUSE:Factory/standard

Still making any sense? :)

**Comment by jberry-suse** [comment]
Yeah, that's what I thought. Although perhaps the only different should be when a list of packages is provided that the rest of the packages in the project in which they are built are ignored, but the path evaluation is still done as normal. Seems like what you want.

**Comment by DimStar77** [comment]
auto-evaluation of the paths after I gave the src in the devel prj sounds reasonable, indeed

**Comment by jberry-suse** [comment]
Even better, #1656 provides:

`./repo_checker.py project_only graphics` or similar, where the repo that builds against `openSUSE:Factory/{snapshot,standard}` is used automatically. The repo can be overriden via OSRT:Config main-repo (locally or remote on devel project).
