### ISSUE TITLE
tests/obs: leaks environment variable changes and httpretty setup, affecting all tests

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1214]
The `OBS` class is implemented as a singleton that never disables `httppretty` which causes any tests that use sockets outside of this mock to fail. This means that the tests in #1207 fail when run as part of suite, but pass when run individually. Bad design to have fixtures that leak environment changes between tests and no fun for a future developer to have to debug.

Not entirely sure what is the best route to fix. The basic requirement is that `httpretty.disable()` be called when test completes. I can hackily workaround by calling that before my test runs, but clearly `OBS` should handle this itself. Since singleton a deconstructor will not work.

**Comment by jberry-suse** [comment]
Forgot to mention the first issue that masked this one. An environment variable is changed, but never reset. Given that value is directly passed to `get_config()` it is not even necessary.

https://github.com/openSUSE/osc-plugin-factory/blob/7d266d5d0aa854d83814c0483ac4f339f81a9aef/tests/obs.py#L135-L138

**Comment by coolo** [comment]
obs.py is history - httpretty is not, but hopefully its usage is much more contained
