### ISSUE TITLE
tests: decide how to proceed installing additional dependencies on travis

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1221]
In order to use `osc vc` to generate a changelog entry (rather than re-creating functionality in python) the `build` package is needed. This is available for ubuntu out of `openSUSE:Tools` repo, but will not be the last odd dep that ubuntu may not have. As such it may make sense to run the tests themselves in an `openSUSE` container or inside the `osc build` changeroot. The latter will be tricky to get the local OBS available there, but has the benefit that those tests can run on OBS.

Until this is resolved I have not commited the `check_source.py` tests and have disabled the test suite in `%check` section of spec. The spec may also end up just needing to filter out the integration tests and only run the mock tests. The method of filtering needs to be figured out as whitelisting or blacklisting seems a bit suboptimal.

**Comment by coolo** [comment]
this is done using the docker container, no?

**Comment by jberry-suse** [comment]
A large part is yes. For doing the package builds yes, but not for running the tests themselves which is the part that really needs it to do more.

**Comment by lnussel** [comment]
so all this dance for osc vc? How about reimplementing the vc command in osc directly, in python?

**Comment by jberry-suse** [comment]
> so all this dance for osc vc?

That being part of it, but there are other requirements. Additionally, the whole point is to make things a) maintainable, b) representative of real thing so re-inventing more code brings us back to mocks.

> IMO we should use docker-compose and run the tests on opensuse.

Running the tests in a docker container like I did for spec builds is a possibility and one I like, but introduces a bit of complexity surrounding using python versions travis supplies or having them available in openSUSE in addition to properly communicating to and from the container (like coverage results).

Also the possibility of installing the built packages and running the tests against those which would catch missing deps and such as well as installation problems.

**Comment by jberry-suse** [comment]
The other big one at the time was getting the obs_factory plugin included in test setup, but that should be done now since included in OBS.

**Comment by coolo** [comment]
you really should look at circleci. They don't even provide a VM at all, they only give you  container orchestration. As such you can only test python versions you have available in openSUSE, but I don't think that's a big problem.

**Comment by coolo** [comment]
I went with running the tests in a docker container itself composed against the obs containers
