### ISSUE TITLE
rebuildpacs.pl: seems to have major pain with _multibuild packages

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/openSUSE-release-tools#1222]
The HPC team has been converting most of their packages to _multibuild... 

rebuildpacs.pl seems to identify them constantly as 'having trouble' and retriggers them, even though it should not retrigger packages it already recorded in the problems list (on first trigger they are being recorded, then only new stuff should be attempted)

In order to get over the obstacle at all for now, rebuildpacs.pl is hotpacthed on the pkglist vm to ignore some of the packages I have seen being retriggered over and over, which of course bears the risk of masking actual issues

**Comment by coolo** [comment]
it's gone now
