### ISSUE TITLE
repo_checker: decide how to include project level config in build hash

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1236]
If items the whitelist in project level remote config is changed the `repo_checker` should consider different build and re-run. After #1229 all repositories plus the staging meta revision are included. The `cstaging` project meta revision could be included, but given that project is updated semi-frequently for unrelated things it would be preferable to only consider different if config changed.

**Comment by coolo** [comment]
Release Managers can retrigger the staging pipelines if they need installcheck to follow a change, so the problem is not worth an extra hook.

**Comment by jberry-suse** [comment]
I disagree as this should be tied into the same events as everything else for the project on OBS.
