### ISSUE TITLE
Decide future of NonFree workflow

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1247]
It seems the staging tools no longer properly handle requests targeting `NonFree` subproject. I feel like I remember something about this a while back, but likely the recent changes to source checker and what not that load `StagingAPI` will not handle for this as well. The primary bit seems like the staging plugin itself.

For example take a look at the three requests to `Factory:NonFree` currently open.

**Comment by nilxam** [comment]
I thought it's not about staging plugin itself but repo-checker can not accept it, those requests were force accepted but without the `repo-checker` review does not be accepted. IIRC old repochecker accept them if it builds in the devel project.

**Comment by jberry-suse** [comment]
Well, I they do not appear to get staged. `repo-checker` just looks for reviews assigned to it, but since they are never staged they never are "ready" to review.

**Comment by jberry-suse** [comment]
The previous `repo-checker` reviewed build results from the devel project so the packages would not need to be staged and other `ReviewBot`s  handle the `:NonFree`. The staging bits appear to have never been capable of staging requests targeting `:NonFree`. Two questions come to mind:

1) Should `:NonFree` requests be staged as part of the normal workflow? (would resolve the next question)
2) Should the `repo-checker` review be skipped entirely for `:NonFree` requests? (either by `repo-checker` just accepting them or likely better `factory-auto` never issuing a review request)

Unless there is a legal reason, choosing to stage `:NonFree` requests seems to be the best option.

**Comment by DimStar77** [comment]
Since we do not publish the staging projects, we should be fine to build those source also there (no redistribution outside of the standard nonoss repo) - and imho, x:NonFree should be included as part of the normal staging process (if x:NonFree exists of course; not the case for SLE)

When setting up the adi project, it needs to build against x:NonFree, as otherwise there are chances of repo-checker not finding dependencies (think the various -data in there, needing also binaries next to it); and of course overlaid over openSUSE:Factory

**Comment by nilxam** [comment]
We should go with

> Should :NonFree requests be staged as part of the normal workflow? (would resolve the next question)

I''m work on it already.

**Comment by jberry-suse** [comment]
For posterity, related PR #1379.

**Comment by jberry-suse** [comment]
One approach to explore post #1650, would be to define a `:NonFree` pattern that excludes the `:NonFree` part from project name and points to target project (ie leap and Factory). This would effectively make the `staging` key the target project instead of `:NonFree:Staging` and may be enough to cleanly trick all the tools to do what we want.

**Comment by jberry-suse** [comment]
Related #1016 as devel-projects does not include `:NonFree` which may or may not be relevant depending on how that issue goes forward.
