### ISSUE TITLE
rebuildpacs.pl uses different repo format

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1257]
there are several services that run under the old repochecker service on packagelists:
$ grep repochecker /etc/systemd/system/*

The reason they use this user is that they use bs_mirrorfull and used to share the cache with the actual repochecker. Now with the new repochecker user they don't share the cache anymore. Even if they'd run with the same user id they still use a different cache structure in ~/.cache.

Please find a way to unify this again to save resources.

**Comment by jberry-suse** [comment]
Using old structure (`repo-{project}-{repo}-{arch}`):

- create_test_dvds.sh
- rebuildpacs.pl

Using new `repo_checker` structure (`{project]/{repo}/{arch}`) from #964:

- pkglistgen.py
- repo_checker.py

**Comment by jberry-suse** [comment]
Although to be clear, the two new structure bits are running on `tortuga` vs the old ones on `packagelists` so this is not a direct proper currently.

**Comment by coolo** [comment]
create_test_dvds.sh is gone - and for rebuildpacs.pl there might be more changes pending.
