### ISSUE TITLE
systemd: use service type simple instead of oneshot because lnussel likes it :/

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1260]
oneshot is the wrong service type for the systemd units, needs to be "simple" (which is the default if not specified)

**Comment by jberry-suse** [comment]
```
Behavior of oneshot is similar to simple; however, it is expected that the process has to exit before systemd starts follow-up units. RemainAfterExit= is particularly useful for this type of service. This is the implied default if neither Type= nor ExecStart= are specified.
```

https://www.freedesktop.org/software/systemd/man/systemd.service.html

What is wrong about it? Especially in the case of `repo_checker` the mirroring will lock anyway and for most other services that is expected behavior.

**Comment by DimStar77** [comment]
There are some subtle differences between oneshot and simple:

* simple is not supposed to 'end' - any termination of the service is considered failure; As we trigger all our services by timers and they terminate, simple is not the correct method
* oneshot services are never 'started' (they go from 'starting' to 'inactive'; this is especially a problem if a oneshot service runs 'long' and happens to be in the 'multi-user.wanted section: multi-user.wanted would only be reached if that long-running oneshot service terminates/finishes

**Comment by jberry-suse** [comment]
So for our purposes `oneshot` makes more sense?

**Comment by jberry-suse** [comment]
#1258 introduced default `type` services that are started by a timer.

**Comment by DimStar77** [comment]
> So for our purposes oneshot makes more sense?

To my understanding of systemd units, the things we repetedly fire off by timers indeed should be ```oneshot``` - things like ttm, which have their own loop, should be ```simple```
