### ISSUE TITLE
repochecker: make it run on ring2

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1277]
The project_only mode should be able to run on ring2 so we see issues before they hit actual stagings

**Comment by jberry-suse** [comment]
Just ring2? Where should the report be placed, as a comment on :Rings or specific ring project? or just direct to stdout? @DimStar77 seemed to imply that rings are regularly broken and understood to be broken in Factory so this is to only be used manually?

**Comment by DimStar77** [comment]
Is this still valid, with the merge of Ring2 into Ring1?

**Comment by jberry-suse** [comment]
`project_only` works on any project including rings after my last refactoring. So this is both solved and the specific use-case no longer relevant.
