### ISSUE TITLE
repo_checker: consider enhancing pre-processing or recheck request group before changing state

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1291]
https://build.opensuse.org/request/show/543659 was moved between stagings after `repo_checker` had started a review cycle. The group in which it originated passed since it was removed and the troublesome binaries no longer present when mirrored. When the `repo-checker` review was re-added it failed, as expected, in the new group.

The groupings are not re-queried after initial pre-processing. Since all requests have to be scanned ahead of time to group by staging this step must remain as it is, but could consider re-checking that group has not changed since the cycle started.

**Comment by jberry-suse** [comment]
Scenario noticed by @nilxam.

**Comment by coolo** [comment]
no longer a problem with staging-installcheck
