### ISSUE TITLE
bs_mirrorfull: add timeout parameter

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1310]
https://github.com/openSUSE/osc-plugin-factory/pull/1290 indicated that bs_mirrorfull needs to use the timeout parameter of BSRPC::rpc to avoid hanging forever.

**Comment by jberry-suse** [comment]
I do not think it was the only thing that hangs, as it seemed like when OBS went down the repo-checker was completely hung on some api call, but not sure at this point.

**Comment by jberry-suse** [comment]
I included runtime max settings for all systemd services in #1534. Otherwise, if it does timeout not much `repo_checker` can do anyway other than crash.
