### ISSUE TITLE
check_source.pl: avoid printing "Unknown license '*'" for compound licenses

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1322]
A common occurrence that is just noise since license bot handles.

```
$ ./check_source.py --osc-debug --debug --dry id 561341
Output of check script (non-fatal):
Unknown license 'GPL-3.0+ and LGPL-3.0+'
```

Source:

https://github.com/openSUSE/osc-plugin-factory/blob/98a659c3fab8dc036f9945854eae93265d695bed/check_source.pl#L276

Which runs:

https://github.com/openSUSE/obs-service-format_spec_file/blob/c6cdcf52556703a805265d7619fccd70e3b9e50d/prepare_spec#L148-L165

Seems like the best route would be to fix `format_spec_file` service, but alternatively ignoring this specific issue since other tools in process should handle.

**Comment by DimStar77** [comment]
The warning shows because 'and' is case sensitive and according the spec written in caps.  There is at least rpmlint-Factory-strict in TW stagings that would catch really invalid licenses (that rpmlint is a bit more forgiving, as we requested 'and' to be written lowercase in the past)

**Comment by jberry-suse** [comment]
So the current stance is to match standard (ie caps)?

**Comment by DimStar77** [comment]
> So the current stance is to match standard (ie caps)?

Right, if I'm not mistaken, if the license uses caps, then the warning would not appear

**Comment by jberry-suse** [comment]
Since that is not clear at all given the message "unkown license" perhaps the message could be changed instead to be clear about what it does not like.

**Comment by DimStar77** [comment]
The test does not do much analysis there at the moment: it finds 'words' that do not qualify as license (not in the SPDX database) and no other known word.

You would get the exact same warning if you put ```License: I have no idea what this is``` 

I doubt we'd want format_spec file to keep on accepting ```and``` and ```or```

**Comment by jberry-suse** [comment]
The reason makes sense, but does not change the fact that the message does not help a submitter know what to change. Not sure what the right place to do it is, but the message is not effective since it appears as noise given all the other processes accept it without incident and clearly packages remain this way long-term.

**Comment by DimStar77** [comment]
yeap -and I don't think we should start declining this kind of issue (yet); ideas welcome :)

**Comment by jberry-suse** [comment]
Was not suggesting we decline, merely that the message be improved so that it is actually useful and might result in the submitter fixing the issue.

**Comment by lnussel** [comment]
format_spec-file mangles the spec file. So if AND vs and is a known pattern it could just fix it instead of printing a warning :) Printing warnings is the job of rpmlint IMO.

**Comment by jberry-suse** [comment]
Sounds good to me. I will suggest that on the issue there.

**Comment by jberry-suse** [comment]
Interestingly,

```
Unknown license 'GPL-2.0+ AND MIT'
```

**Comment by DimStar77** [comment]
On what machine do you gund t that warning? Recent version of source validator?

**Comment by jberry-suse** [comment]
packagelists as it showed up on request to Factory.
