### ISSUE TITLE
pkglistgen: migrate SLE wrapper scripts to onto migrated python bits

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1329]
The openSUSE scripts were migrated in #1312 and #1328, but the SLE specific bits need to handle as well.

- [x] From what I can tell the rings script (http://paste.suse.de/18043) contains additional `rm` commands specifically kiwi globs that need to be handled.
- [x] Not sure if `~/osc-plugin-factory-coolo/pkglistgen.py` contains any other changes.
- [x] Handle `--ignore-unresolvable` and `--ignore-recommended`.
- [ ] Decide on long-term solution for package clones. Previous was `osc up` which notes to having issues, current does fresh checkout, but for SLE there are a ton of files.
- [ ] Configure `download-baseurl` in `osclib/conf.py` utilized by drop list generator, added in #1386

Presumably everything is the same short of squinting at the scripts longer.

**Comment by jberry-suse** [comment]
If/When you have the time you likely know best what SLE desires.

**Comment by jberry-suse** [comment]
Added reference to drop list generator.

**Comment by jberry-suse** [comment]
For posterity #1404 is related to this and possibly fixes this issue.

**Comment by jberry-suse** [comment]
SLE-15 uses the new tool although still out of custom clone. Not sure where this stands.

**Comment by coolo** [comment]
We are somewhat good on SLE side. The checkout is still very slow, but that's a generic osc problem :(
