### ISSUE TITLE
i586 handling in Leap

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1357]
In Leap i586 is handled specially due to lack of better options and ideas.
In the main project i586 is enabled in principle.  All packages that are neither in Ring0 nor Ring1, nor have baselibs.conf, nor are required by any of the former are build disabled.

Now this causes two issues in staging:
1. repochecker gets confused if a staging project contains a delete request for package A and an update for package B when only the old package B required A. If B is build for i586 in the main project but not in staging, repochecker would still think B depends on A as it sees the old binaries in the target.
2. ADI stagings are grouped. If one of the packages in the group contains baselibs.conf, all packages are built for i586. That will fail for most of them of course.

So in order to fix both issues I wonder whether the staging tools should mirror the build flags of the main project always? Ie we could enable i586 in staging and when whenever a package get selected into a staging project, the build disable setting from the main project would have to be copied.
Secondly, on accept the command could apply the build flags in the target too. That way stagings could change the build flags.

**Comment by jberry-suse** [comment]
1. Two parts: `BuildRequires` and `Requires` in `i586`. The first is #1009, but the second being an interesting issue that seems like only real solution is the same to part two.
2. A unwanted side-effect of #1320 (`baselibs.conf` adi check)

Is there any negative effect to using this same logic for Factory or SLE? Seems like a solution (except for `BuildRequires` which is different issue).

**Comment by lnussel** [comment]
since neither SLE nor Factory disable architectures like Leap any code that looks for the disable tags would just not do anything in SLE or Factory. ie no harm done IMO

**Comment by lkocman** [comment]
Does this need to be still opened if part 1 and part 2 already have issues opened? Could we replace this issue by a label perhaps?

**Comment by coolo** [comment]
jumped
