### ISSUE TITLE
repo_checker: project_only --post-comments seems miss devel project for wxWidgets-3_2

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1371]
I noticed over the last couple days that the `repo-checker` seems to post comment on `openSUSE:Factory` when reviewing both `openSUSE:Factory` and `openSUSE:Leap:15.0`. Rather odd considering one is defined. Originally I figured it might be API error that would go away, but it seems persistent.

**Comment by coolo** [comment]
https://build.opensuse.org/package/show/openSUSE:Factory/wxWidgets-3_2 was updated last one year ago, so it seems gone.

That these comments stay is one reason why I think we need to look for alternatives.

**Comment by jberry-suse** [comment]
> That these comments stay is one reason why I think we need to look for alternatives.

This was another one of the many points that was resolved in my presentation last year which was overlooked. The OBS status reports could be extended to support this as I suggested in my initial feedback.

**Comment by jberry-suse** [comment]
Related to this if not the original cause is the fact that multi-spec packages devel project points to the same project in which the package resides which is exactly the opposite of the desired for the comment. Following the chain of devel links could resolve, but should be done properly to avoid inconsistent results with other tools.
