### ISSUE TITLE
pkglistgen: sync solv cache to shared location

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1407]
As discussed previous a shared location would be handy for testing to compare result against live which will have historical builds that cannot be reproduced.

Essentially need `~/.cache/opensuse-packagelists/solv/` sync'd before and after each run.

**Comment by jberry-suse** [comment]
@lnussel I know you suggested OBS, but perhaps just another git repo that way we can periodically rebase into single commit to drop old files.

I suppose OBS has the advantage of permissions as we could add `factory-staging` or the tools group (probably tools makes more sense) and thus avoid needing to add people to another group. Dunno.

**Comment by jberry-suse** [comment]
Assuming this will store solv files outside of individual products it should likely live outside of product project tree in OBS if we use that. As such perhaps `openSUSE:Tools` or where?

Alternatively, we create a new git repo (presumably under openSUSE namespace which I cannot do). Perhaps `package-lists-archive`, `package-lists-solv-archive` or similar. With #1441 the git option is likely easier since the packagelists code always does a clean checkout due to mentioned `osc` sync issues. Perhaps it won't apply to this type of package setup. Either way.

For local development read access is all that is required which is easy on OBS or git. We can use a deploy key for deployed push.

**Comment by coolo** [comment]
Discussed the options and @lnussel and @DimStar77 preferred a package within the target project - and behlert has no objections. So going ahead with this option
