### ISSUE TITLE
repo-checker: resolve IBS-style direct project level comment notifications

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1421]
Either openSUSE/open-build-service#4590 which is the real solution, or a workaround similar to the request review reminders that references all `bugowners`.

**Comment by coolo** [comment]
Commenting the 'right' package is basically impossible in the scope of SLE - and also in the scope of Leap to be fair. You basically spam release managers - the proper way is really bugzilla for such issues. But for that we would need to be certain the issues aren't temporary, which I find generally very hard to do.

**Comment by jberry-suse** [comment]
Leap reports on devel projects just like Factory which is exactly what is desired. Unfortunately SLE has no such defined layered development and OBS does not support notifying the bugowner who is the "real" owner in SLE model. If there is a better mechanism to use to show repo-checker errors on SLE packages lets use it.

**Comment by coolo** [comment]
The problem with Leap is that SLE packages are maintained by SLE maintainers - the devel project maintainer might be a different one

**Comment by jberry-suse** [comment]
Sure, but that is the nature of the beast. The scope of that problem extends beyond repo-checker.

**Comment by coolo** [comment]
And that's why I think repo checker shouldn't try - and leave that to build-fail-reminder

**Comment by jberry-suse** [comment]
Sure, but it doesn't do anything about SLE packages. It's even hard-coded for Factory. If bugzilla is the only way to communicate with SLE maintainers that's that, but not as if there is a solution ready for repo-checker to use and the current one works quite well for openSUSE.

**Comment by coolo** [comment]
I disagree

**Comment by adrianschroeter** [comment]
On Montag, 3. Juni 2019, 21:10:50 CEST Jimmy Berry wrote:
> Leap reports on devel projects just like Factory which is exactly what is
> desired. Unfortunately SLE has no such defined layered development and OBS
> does not support notifying the bugowner who is the "real" owner in SLE
> model. If there is a better mechanism to use to show repo-checker errors on
> SLE packages lets use it.

actually we should have bugowner notifications .... works for me at least

-- 

Adrian Schroeter
SUSE Linux Products GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
email: adrian@suse.de

**Comment by jberry-suse** [comment]
> actually we should have bugowner notifications .... works for me at least

Such notifications were implemented 5 hours ago (openSUSE/open-build-service#4590) this issue is 15 months old. Lets not pretend that we are correcting the premise of the discussion.

The feature is certainly appreciated.

**Comment by coolo** [comment]
I only closed the ticket after adrian's comment - the feature is from september 2018
