### ISSUE TITLE
move config out of staging area

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1449]
The config for many things unrelated to staging, eg various bots is still in the staging area. In order to not require a staging project just for storing the config it would make sense to move the config to the main project. We could reuse e.g 00Meta or even obs attributes.

**Comment by coolo** [comment]
be aware the permission problem. You need quite some bots/people to write to it.

**Comment by lnussel** [comment]
could be an argument against attributes

**Comment by jberry-suse** [comment]
> The config for many things unrelated to staging, eg various bots is still in the staging area. In order to not require a staging project just for storing the config it would make sense to move the config to the main project. We could reuse e.g 00Meta or even obs attributes.

Has bothered me a bit for a while, especially considering it is `:Staging/dashboard/config` which has a variety of unrelated concepts in the path. :/

> be aware the permission problem. You need quite some bots/people to write to it.

Short of the code that writes a blanks config for caching no bots that I am aware of write to remote config. Only read. Depending on who should be allowed to edit permissions may still be a problem.

> could be an argument against attributes

I had looked at them when improving the locking code. Asuming there are not any restrictions to length that would hinder us like the `repo_checker-binary-whitelist` which can be long, but is likely a temporary problem.

**Comment by jberry-suse** [comment]
> You need quite some bots/people to write to it.

Although of course the bots do write to the other files contained within `dashboard` package. Not sure as the scope of this issue as I was assuming talking about remote `config` only.

**Comment by coolo** [comment]
@adrianschroeter created an attribute namespace OSRT in both OBS and IBS. Within this namespace we (those 3 commenting in here :) can create attributes and per attribute you can define who can modify it.

If we split the config into multiple attributes or not does not really matter. But splitting it has the advantage of not risking to break one while updating the repo checker white list

**Comment by coolo** [comment]
I moved the config as it is to OSRT:Config, but it would be worthwhile to split the repo checker and pkglistgen stuff into attributes of its own.
