### ISSUE TITLE
check_source: Disable all checks that depend on devel projects for SLE

### ISSUE THREAD

**Issue by kraih** [openSUSE/openSUSE-release-tools#1464]
Another request from @coolo. I'm opening this issue so the exact requirements can be discussed.

Since SLE has no devel projects, all factory-auto checks that depend on devel projects should be disabled for SLE.

Test case for mid-air rename (should be accepted):
```
$ ./check_source.py -A https://api.suse.de --dry --debug id 158191
[I] checking 158191
[I] openSUSE.org:mozilla/firefox52@35 -> SUSE:SLE-15:GA/MozillaFirefox
[I] 158191 declined: No in-air renames: The package must be called the same in the devel project as in the target project
[D] 158191 review not changed
```

Test case for delete request (should not require devel project review before accept):
```
$ ./check_source.py -A https://api.suse.de --dry --debug id 157873
[I] checking 157873
[W] createrepo doesn't have maintainers
[D] skipped adding duplicate review for createrepo/SUSE:SLE-15:GA
[D] skipped adding duplicate review for repo-checker
[I] 157873 accepted: ok
[D] 157873 review not changed
```

**Comment by jberry-suse** [comment]
> Test case for mid-air rename (should be accepted):

Presumably this is not related to devel project checks since it always checks `source.name == target.name` regardless of devel project.

> Test case for delete request (should not require devel project review before accept):

As we discussed in IRC, the big one for this being the addition of devel project maintainer review on delete requests.

https://github.com/openSUSE/osc-plugin-factory/blob/d11501f8842e1ab602349c6098786a72f5a59b32/check_maintenance_incidents.py#L52-L66

Will need to do some grepping to see what else is done specific to devel projects in `check_*` files.

**Comment by coolo** [comment]
the source.name == target.name isn't useful in itself. It's handy to find packages, but its' not a requirement even for Factory (as far as I know). But for SLE it's quite regular that updates (bash.SLE11_SP4) are submitted to new code paths - and we have no devel packages that would catch these renames.

**Comment by DimStar77** [comment]
> the source.name == target.name isn't useful in itself. It's handy to find packages

We do enforce it in Factory - to avoid massive confusions for devel packages being named differently than packages in oS:F

**Comment by coolo** [comment]
... and I agree.

but even for Leap it might already be too harsh. Because maintaining a leap branch in the same devel prj sounds like a valid approach.

**Comment by jberry-suse** [comment]
> but even for Leap it might already be too harsh. Because maintaining a leap branch in the same devel prj sounds like a valid approach.

Perhaps @lnussel has thoughts on the matter, but does not seem to have been a problem for Leap thus far. Likely, this needs to be a config option.

The second part, regarding delete requests makes sense, and should be placed behind the `self.ignore_devel` setting added when this was adjusted for Leap. Leaper should be responsible for adding such reviews.

**Comment by jberry-suse** [comment]
From discussion with @kraih it makes sense for me to take over.
