### ISSUE TITLE
Can't submit the base container to SLE 15 anymore

### ISSUE THREAD

**Issue by coolo** [openSUSE/openSUSE-release-tools#1469]
> I can't submit the base container to SLE 15 anymore as it just builds a .kiwi
> file: https://build.suse.de/request/show/159387
> 
> factory-auto complains:
> 
> Output of check script:
> A sles15-image.spec is missing. Packages submitted as FooBar, need to have a FooBar.spec file

Having containers and kiwi products does not happen in Factory, as we use :Live subprojects, but can we allow this for Factory and leap too? @DimStar77 @lnussel

**Comment by DimStar77** [comment]
No strong objection to 'accepting' this kind of submission against :Factory, where it will have to be shut down in other ways then.

**Comment by Vogtinator** [comment]
Sounds like a project-specific configuration/policy is the best way here. .kiwi files in oS:F won't work properly, but in SLE-15 they do.

**Comment by coolo** [comment]
The question is if they are so common that it's worth the setting for O:F

**Comment by DimStar77** [comment]
Probably not - IIRC, the .spec has to be there check has been there since the very early days of factory-auto; I doubt it had to shoot down many submissions though

**Comment by lnussel** [comment]
I don't see a reason to reject this automatically

**Comment by lnussel** [comment]
So who is going to send a patch? In the cited example should the kiwi file be named sles15-image.kiwi instead of config.kiwi as analogy to the spec file naming policy?

**Comment by Vogtinator** [comment]
It can't - `containment-rpm-docker` uses `config.xml` and I'd like to keep that in sync with other images.

**Comment by lnussel** [comment]
if that package uses config.**xml** (which I can't see in Factory) then it would already be inconsistent with config.**kiwi** in the example.

**Comment by Vogtinator** [comment]
Hm, there might indeed be some magic in between which renames it.

**Comment by coolo** [comment]
deployed, so feel free to reopen possible SRs
