### ISSUE TITLE
check_source: SLE can't skip staging review

### ISSUE THREAD

**Issue by coolo** [openSUSE/openSUSE-release-tools#1483]
Factory-auto user has no permissions to skip staging reviews, so it's crashing if trying to do so. Not sure why it can for Leap actually :)

**Comment by DimStar77** [comment]
```osc api /group/factory-staging```

factory-auto is is a member of the staging masters

**Comment by coolo** [comment]
I would say no. We have so few of them that it doesn't justify the confusion we'll see with "where is the package XXX, why is it not showing up" :)

**Comment by coolo** [comment]
I actually wonder why it was useful to implement for openSUSE. Was there a point with a lot of 'only changes'?

**Comment by DimStar77** [comment]
with the SLE sync (SP2) there were quire a bunch of submits with only aligning changelogs. And going through a full staging there makes no sense

The human review remained in place, so they did not just get waved through.

**Comment by coolo** [comment]
this is still needed :(

**Comment by coolo** [comment]
while trying to fix it, I noticed that --skip-add-reviews skips also this part. As for SLE all we add is repo-checker, I now added repo-checker explicitly as reviewer and passed this option.
