### ISSUE TITLE
openSUSE maintenance openQA bot does not handle patchinfo binary filtering

### ISSUE THREAD

**Issue by andreasstieger** [openSUSE/openSUSE-release-tools#1521]
An update was prepared a maintenance update for `gcc48` in [openSUSE:Maintenance:8043](https://build.opensuse.org/project/show/openSUSE:Maintenance:8043). The [maintenance incident patchinfo](https://build.opensuse.org/package/view_file/openSUSE:Maintenance:8043/patchinfo/_patchinfo?expand=1) contains `binary` elements to filter the packages built from being released into the update channel. In this case the runtime libraries are now provided by `gcc7`.

As a consequence, the incident contains more binaries than will be released. This is a somewhat infrequent but in this case intended use of patchinfo filtering. The openQA incident tests, then, fail to install what it thinks are the original packages:
https://openqa.opensuse.org/tests/668043#step/install_packages/9
https://openqa.opensuse.org/tests/668044#step/install_packages/9
https://openqa.opensuse.org/tests/668045#step/install_packages/9

The openSUSE openQA bot extracts the list of packages to hand over via the `INSTALL_PACKAGES` and `VERIFY_PACKAGE_VERSIONS` variables. This code in particular iterates the source containers in the incidents and extracts all built binaries:

https://github.com/openSUSE/openSUSE-release-tools/blob/aabbefd2b64c1e15891d5a1ea4c365ecc17343f7/oqamaint/opensuse.py#L31-L54

The issue is that the bot does not support the patchinfo package filtering via the optional `binary` attribute. The ask would be to have an implementation where this is supported. The patchinfo XML could be parsed to achieve that.

The work-around is to re-trigger test runs for this type of incident while adjusting the two variables being handed over.

Code last shepherded by @coolo 
Test is for @msmeissn
@plusky maybe?

Which alternative sounds better, or maybe I missed one?

**Comment by andreasstieger** [comment]
I worked around the issue by cloning the job and adjusting the package list manually: 

https://openqa.opensuse.org/tests/668834
https://openqa.opensuse.org/tests/668829
https://openqa.opensuse.org/tests/668830

Making this work for the general case may be something for later...

**Comment by coolo** [comment]
gcc is coming from SLE now
