### ISSUE TITLE
update_crawler: provide proper config and/or integrate release schedule

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1543]
update crawler needs to be made configurable. I tried to prevent it from submitting from factory three times already but since it's not a config file it gets overwritten ..

**Comment by jberry-suse** [comment]
Likely the best option it to provide the schedule (like the one used for metrics) as input to have the crawler automatically change modes rather than tweak the file incrementally. In the mean-time editing the file in git might be best unless denoting it as `%config` is valid for bindir in spec.
