### ISSUE TITLE
osrt-staging-bot-superesede: non functional due to permission issues

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/openSUSE-release-tools#1551]
Bot was converted to be a packaged service with

https://github.com/openSUSE/openSUSE-release-tools/commit/eb7e3a458aad5f644bea2681e6e51ed2bcf20398#diff-f373d48829b54bb9552900d212b66b50

The problem here is that the user ```osrt-staging-bot``` has no permission to supersede random requests against openSUSE:Factory, as it is not a target maintainer.

the old service (osc-check_dups) ran as ```repochecker``` (system user, ```factory-repo-checker``` obs user) for this reason.

There are currently this kind of failures on the journal:

```
May 18 11:30:01 packagelists systemd[1]: Started openSUSE Release Tools: supersede duplicate submissions for openSUSE:Factory.
May 18 11:30:24 packagelists osrt-staging-bot[28450]: Server returned an error: HTTP Error 403: Forbidden
May 18 11:30:24 packagelists osrt-staging-bot[28450]: You have no role in request 607523
May 18 11:30:24 packagelists systemd[1]: osrt-staging-bot-supersede@openSUSE:Factory.service: Main process exited, code=exited, status=1/FAILURE
May 18 11:30:24 packagelists systemd[1]: osrt-staging-bot-supersede@openSUSE:Factory.service: Unit entered failed state.
May 18 11:30:24 packagelists systemd[1]: osrt-staging-bot-supersede@openSUSE:Factory.service: Failed with result 'exit-code'.
```

**Comment by DimStar77** [comment]
I realized that there must be an issue as, during one check-in round, I had one package twice in to be checked in. This was a non-ring package that passed adi already, a new submission came in (non-superseding by the submitter), passed adi again and then there were two 'new' submissions pending. The 2nd accept failed (conflict in the submissions)

**Comment by lnussel** [comment]
we still have the task open to add the staging group to all devel projects (in addition to the factory maintainers), that should solve the issue

**Comment by DimStar77** [comment]
Yap, that should indeed be a solution to the issue

**Comment by jberry-suse** [comment]
Also perhaps #1027.

**Comment by jberry-suse** [comment]
Otherwise, could stick with supersede functionality built into osc staging plugin which declines the `factory-staging` review. Alternatively, can go back to use `repo-checker`, but doesn't make sense scope-wise just avoiding permission issue.

**Comment by DimStar77** [comment]
> Otherwise, could stick with supersede functionality built into osc staging plugin which declines the factory-staging review.

That one does not handle the case described, where a request that already passed 'adi staging' and was marked 'new' (ready to be accepted) got a new submission

**Comment by jberry-suse** [comment]
Perhaps it makes sense to handle the case there rather than half in either tool.

**Comment by Vogtinator** [comment]
> That one does not handle the case described, where a request that already passed 'adi staging' and was marked 'new' (ready to be accepted) got a new submission

IMO those should not be superseded automatically. Either the devel pkg maintainer can choose to do so (he already can) or a target maintainer can decline it.

**Comment by DimStar77** [comment]
Also related to https://github.com/openSUSE/openSUSE-release-tools/issues/915 - where a similar case already happened earilier, in Leap

**Comment by Vogtinator** [comment]
> Me being the target maintainer: I don't want to care for such things manually

osc does - when you open a request to the same target it asks you whether to supersede or not. The web ui does the same.

**Comment by DimStar77** [comment]
the webui only does when you click sumbit - NOT when you 'accept and forward' a submit.

**Comment by DimStar77** [comment]
in plus: the Workflow has to work independent of contributors unawareness / errors.

**Comment by jberry-suse** [comment]
I would vote for #1558 as the solution which extends the code I added to handle other oddities like this. An extension could be do check for ignored requests for the same package when adi requests are accepted and unignore them.

**Comment by coolo** [comment]
I removed the service now - and the plugin used there.
