### ISSUE TITLE
Submitting tools should submit the package again if there is another update available in the source

### ISSUE THREAD

**Issue by nilxam** [openSUSE/openSUSE-release-tools#1556]
when the submission is pending in the staging project, and there is another update available in the source, the submitting tools should submit the package again.

the tools have to update:
* update crawler
* compare_pkglist

**Comment by lnussel** [comment]
iow update-crawler not only needs to compare sources to determine what to submit but also open requests

**Comment by jberry-suse** [comment]
> when the submission is pending in the staging project, and there is another update available in the source, the submitting tools should submit the package again.

Won't this just cause a lot of staging rebuilds and delays?

**Comment by coolo** [comment]
It's the usual compromise to find. Waiting with the update of the update until the first round is accepted will lead to bugs to be found that are already fixed. 

So IMO from release manager point of view it's best if these updates are available as quickly as possible but that the supersede can be controlled.

**Comment by jberry-suse** [comment]
Likely should be determined based on some maximum frequency. So those spamming commits as we've seen come in about the rate at which a staging completes building don't end up blocking it for days on end.
