### ISSUE TITLE
adi merge and clean commands

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1559]
@DimStar77  just showed me two simple shell scripts, one to merge two adi's and one to remove failed packages from a given adi. both should be provided by the staging tool itself I suppose :)

**Comment by okurz** [comment]
"simple shell script" would be:

```bash
function adimerge() {
  osc review list openSUSE:Factory -P openSUSE:Factory:Staging:adi:$1 | awk '/State:review/ {print $1}' | xargs osc staging select --move openSUSE:Factory:Staging:adi:$2; }
```

**Comment by coolo** [comment]
adimerge is a dup of #1105 

Not sure what @DimStar77 uses for failed packages, but it sounds like an extension to `unselect --cleanup`

**Comment by DimStar77** [comment]
> adimerge is a dup of #1105
> 
> Not sure what @DimStar77 uses for failed packages, but it sounds like an extension to `unselect --cleanup`

```
#!/bin/bash

# Scans an adi Staging and unselects everything currently failing or unresolvable, leaving only 'successful' packages
# in the staging. This can help for adi that are completely reviewed, but blocked by some failing package
# The failed ones will move to a random new adi staging

if [ -z "$1" ]; then
	echo "Need to be called as $0 <n> - with <n> referencing the number of the adi project to process"
	exit
fi

osc prjresults openSUSE:Factory:Staging:adi:$1 -V | awk '/^[FU] / {print $NF}' | xargs -r osc staging adi --move
```

Hack, and I don't use it very often; it's mostly when some weird grouping happens in with submissions from 'catch-all devel repos' like games, multimeoa:libs and such

**Comment by coolo** [comment]
Hmm, it sounds very specific. Most of the times it will be one or two packages that have to be moved and not requiring major tooling. So I'm tempted to close this and leave the last comment as answer if someone feels the need to script it.

**Comment by DimStar77** [comment]
works for me - the merging of adi's is definitively in use much more often, and that's something the tooling support now.
