### ISSUE TITLE
openSUSE maintenance openQA bot adds excessive comments for multi-target incidents

### ISSUE THREAD

**Issue by andreasstieger** [openSUSE/openSUSE-release-tools#1561]
Incidents in openSUSE:Maintenance that have two targets (Leap 15.0 and 42.3) receive excessive comments from the scheduling bot.

e.g.
Visit https://build.opensuse.org/project/show/openSUSE:Maintenance:8160
Fiorentina Linderoth wrote in project openSUSE:Maintenance:8160:
Group openSUSE Leap 42.3 Incidents@DVD-Incidents (3 tests passed)

Visit https://build.opensuse.org/project/show/openSUSE:Maintenance:8160
Fiorentina Linderoth wrote in project openSUSE:Maintenance:8160:
Group openSUSE Leap 15.0 Incidents@DVD-Incidents (3 tests passed)

The comments overwrite each other, also it's a bit of an e-mail spam issue.

**Comment by coolo** [comment]
The bot operates under the assumption that for openSUSE there is always one incident per target project. This seems to be the first time, it's not

**Comment by andreasstieger** [comment]
In openSUSE Maintenance we frequently use incidents targeting multiple releases, and have been doing so for years. We just did not have this particular example while testing the bot.
