### ISSUE TITLE
factory-auto needs to allow "renames" for submissions from maintenance projects

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1571]
packages in maintenance projects have "name.$issuenumber". Factory-auto thinks that is a rename but it isnt, e.g.

https://build.opensuse.org/request/show/615991

**Comment by lnussel** [comment]
hmm, set check-source-in-air-rename-allow = True in config

**Comment by jberry-suse** [comment]
So nothing else needed right?

**Comment by coolo** [comment]
I guess referencing that option in the error message would be good.

**Comment by jberry-suse** [comment]
Originally I missed that this was not maintenance request as I assumed from description, but rather from :Update to Leap. Need to allow such package names with format `$package.$number` as a subset of "in-air renames" without requiring the option to be enabled.
