### ISSUE TITLE
Tools (leaper,repo-checker) needs to post full URLs in comments

### ISSUE THREAD

**Issue by coolo** [openSUSE/openSUSE-release-tools#1572]
OBS markdown (as github markdown) renders relative URLs correctly, but the notification email sent out won't be rewritten to be absolte - and won't work. See https://bugzilla.novell.com/show_bug.cgi?id=1095929 and https://github.com/openSUSE/open-build-service/issues/5091

**Comment by jberry-suse** [comment]
I wholeheartedly disagree with this.

**Comment by okurz** [comment]
Why is that?

**Comment by jberry-suse** [comment]
Leaving discussion in the OBS issue.
