### ISSUE TITLE
leaper: move --manual-version-updates and --manual-maintenance-updates to config

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1606]
The command line options --manual-version-updates and --manual-maintenance-updates should be  moved to config options so they can be set per project.

**Comment by lnussel** [comment]
did you start working on this yet? Just checking as I found another use case

**Comment by lnussel** [comment]
I had a look at ReviewBot and think the framework for reading a instance specific config file can be moved there:

* in ReviewBot.load_config() use xdg.BaseDirectory.load_config_paths() to try to load a config file according to the name of the bot if no explicit file name was specified
* provide a way for derived classes to extend ReviewBot.config_defaults

**Comment by lnussel** [comment]
ah, well. wrong issue. the --manual-version-updates and --manual-maintenance-updates are actually per project so they need to be set via osclib.conf instead of per instance config.

**Comment by jberry-suse** [comment]
Provided via `automatic_updates` configuration option per origin in conjunction with #2145.
