### ISSUE TITLE
leaper: new command to add to SLE-workarounds

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1607]
some package submissions, like most 15.0 updates right now need to be copied to the :SLE-workarounds subproject. Would be nice to have a command similar to the override command to control to make the bot do it, e.g.

AT leaper workaround

**Comment by lnussel** [comment]
just had a discussion with SLE release managers. they will want a similar feature

for example rpmlint gets submitted to SLE-12-SP3 as maintenance update but that takes a while to to pass the queue. So the package gets submitted to SP4 too to fast track. When the package is then released in SP3, the package can be deleted in SP4 again.

**Comment by jberry-suse** [comment]
No longer necessary. `origin-manager` will mark as workaround from last know origin and upon accept will be considered as a workaround.
