### ISSUE TITLE
repo_checker: proposal to abandon project level whitelist

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1630]
Based on my thinking for some time and the desire for stacking the repo chain in #1624 which exposes this issue more directly it seems now may be the time to make a change.

Currently, there exists two levels to the `repo_checker` whitelist.

1) target project (in `:Staging/dashboard/config/repo_checker-binary-whitelist*`)
2) staging project (project psuedo-meta set via `osc staging config repo_checker-binary-whitelist*`)

The second only applies to the staging project on which it is set and the target project is applied to all.

The whitelist was introduced when I rewrote the `repo_checker` to look at staging projects instead of devel project binaries. The previous approach directly inserted an individual or group of package container binaries into the solv information for the target project. This had the benefit of automatically scoping to only the packages being changed, but would miss problems occuring due to rebuilds and such occurring in staging, not to mention missing everything that happened in staging since it didn't look at it.

The new design reviewed a staging project as a whole, but this also meant it was unclear which problems were "known" or "pre-existing" and which were caused by the changes in question. As such the whitelist was introduced to _acknowledge_ problems that were _known_ to be in the target project. The assumption was the problems would eventually reduce down to near nothing which was true, but given the staging projects only cover ring packages or the packages being changed (adi) a large number of existing problems never had to be placed in the whitelist.

The alternative approach I had envisioned, which I think is theoretically closer to what you want, is to diff the result of the staging project as if it was accepted and part of the target project (ie everything) and diff against the output from the target project to see what is new. Based on the assumption that the problems in the target project would be kept minimal as they are undesirably and considered problems it seemed the whitelist approach as a initial phase tool was far simpler (and it was).

Diffing is a bit complex due to very subtle changes making waves in the solver output and of course any rebuild changing all the numbers. I later added `install_check_parse()` which parses the output to determine the packages involved. This was used to compute a hash to avoid spamming essentially the same comment on packages in devel projects caused by rebuilds.

The same function was later used to automate removing unnecessary entries from the whitelist in `install_check_parse()`. Essentially, if we boil the whitelist down to:

> Everything that made it past staging and into the target project is a known issue.

That can be entirely automated now. This means, during the `project_only` mode the whitelist could be generated by a slight tweak to `whitelist_clean` and thus becomes a "_cache_ of binary names involved in solver problems". At which point it could just be cached locally or computed every time `repo_checker` runs based on the latest `project_only` output in `:Staging/dashboard/repo_checker`. 

Effectively, removes the level 1 whitelist and leaves only the staging project whitelist. This would then allow non-filtered/scoped reviews of staging projects as if they were part of target project and effectively diffed against target project. The caveat (which already exists) based on the nature of the whitelist is that new issues involving binaries with existing issues will be ignored. This is outside the base-scope of this problem and can be solved separately by a more detailed parsing of solver output or using some more direct communication with solver to acquire structured data.

This also makes usage of the `repo_checker` for devel projects much more useful since one could review an individual request against devel project and automatically ignore existing issues since no one to maintain the whitelist. Plus staging masters no longer have to deal with it.

Assuming no one opposed I will implement this before #1624 since it can be done independently and then we can merge that without wreaking havoc in Factory.

**Comment by jberry-suse** [comment]
This then also works for maintenance workflow as the "automated whitelist" will come from `:Update` project and release request will be compared against that.

**Comment by coolo** [comment]
What you write makes sense, I'm just not sure it's wise to decouple it from 1624. Because if you don't rely on external scripts but do the installcheck directly in python using libsolv bindings - as we do in pkglistgen - you have much more control over normalizing the problems. Because if you do the solving yourself, you can e.g. right away spot what repository the problematic packages come from (and elimate their versions and architectures).

**Comment by lnussel** [comment]
hmm. i wonder if pkglistgen and repochecker could share code or are actually just different modes of operation of the same program. IIRC this installcheck tool that gets called by repochecker just iterates over all packages and tries to install them one by one. That is what pkglistgen does too, just by using python bindings.

**Comment by jberry-suse** [comment]
> can e.g. right away spot what repository the problematic packages come from (and elimate their versions and architectures).

Sure, but not that simple since the list of packages involved in such chains may changes in interesting ways which makes normalization difficult at least to decide what constitutes a changes that a human would want to see.

> hmm. i wonder if pkglistgen and repochecker could share code or are actually just different modes of operation of the same program.

Similar definitely, the mirror and such already has an issue to share that code, but the preparation like groupings from staging and such is different and output obviously. Could probably share more than they do.

**Comment by jberry-suse** [comment]
> What you write makes sense, I'm just not sure it's wise to decouple it from 1624.

My point there was this change works without #1624 and should likely be done regardless of what happens there. It just so happens it also provides a workable solution to that as well.

**Comment by lnussel** [comment]
I think what coolo means is that when implementing this based on parsing installcheck output while #1624 goes in the direction of using libsolv the effort spent on the installcheck parser would be lost.

**Comment by jberry-suse** [comment]
#1624 doesn't change the mode of operation at all. Just allows for multiple "underneath layers" instead of just one. The parsing is already sufficient as it stands now, just needs to be used instead of whitelist from config.

Rewriting to use libsolv directly would allow more possibilities (as has been discussed before) and I have not problem with that, but not being done and have no direct need for anything that would allow.

**Comment by jberry-suse** [comment]
A problem I found with libsolv bindings is they do not include file conflict checking bits. Even noted in [crude documentation](https://github.com/openSUSE/libsolv/blob/38c5374d4712667b0b6ada4bf78ddbb343095d0c/examples/pysolv#L23). Given the current perl script expects an rpmdb we'd have to generate that and pass to existing script.

**Comment by coolo** [comment]
The file conflict check will move into an OBS route (in September, @mlschroe didn't want to start it before our vacations) - as it's very generic and not bound to any of our configs or policies. I suggest to make repo_checker.pl only about the findfileconflict part for now and do installcheck out of it. Moving the repo_checker.pl to be online later on is then an easy step.

**Comment by jberry-suse** [comment]
If OBS does enough to build a solv or rpmdb file to evaluate file conflicts why not just serve the file via an API call and we can do w/e is needed?

**Comment by jberry-suse** [comment]
If that is in the works for a month from now, not sure how much value we get from rewriting all that now.
