### ISSUE TITLE
check_maintenance_incidents: evaluate origin based logic and overlap with leaper

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1645]
https://github.com/openSUSE/openSUSE-release-tools/blob/fa1f929d19a57f2e1035e1a4d062e36125e45741/check_maintenance_incidents.py#L99-L112

Seems like a) this is/should be covered by `leaper` now assuming maintenance switches to it, b) leaper calls this code to add maintainer review so should likely move there if not already and disable the "maintbot" by itself. Eventually this entire file should be dropped and the couple function just made library functions.

This should happen before new set of tools deployed for maintenance.

**Comment by lnussel** [comment]
I agree. The code that figures out the maintainer should be refactored into ReviewBot and the rest handled by leaper.

**Comment by jberry-suse** [comment]
Related:

https://github.com/openSUSE/openSUSE-release-tools/blob/fb3d58024ae23e1ddb8365de35ba9edb530d7e92/check_source.py#L60-L61

After #1650 will likely no longer be necessary. In fact `single_action_require` also can be dropped since default is `False` and Factory/Leap has explicit set to `True` (SLE defaults removed, but should be there too).

**Comment by jberry-suse** [comment]
As far as I can tell that `factory-source` logic should be handled by `leaper` maintenance_incident code.

https://github.com/openSUSE/openSUSE-release-tools/blob/fa39e68d50a49598df34fe791d81f38237634fcd/leaper.py#L238-L241

As the target project for such requests will be `openSUSE:Backports:SLE-15:Update` witch matches the `:Update` condition.

**Comment by jberry-suse** [comment]
Indeed, part of [Origin Manager rework milestone](/openSUSE/openSUSE-release-tools/milestone/6).
