### ISSUE TITLE
RFC: For non-products default to 00Meta as the psudometa (previous dashboard) container

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1652]
This would allow devel projects and `:Update` to store the `repo_checker` output and similar in `00Meta` package. Re-using name since `Leap:N` and `Leap:N:Update` already contain it and has builds disabled and only stores meta data.

The location will be configurable via a project config settings so if devel projects want it somewhere else they can do so.

This is primarily necessary to resolve maintenance repo_checker workflow and they definitely need to see the output as many problems have been introduced post-release of _15.0_.

Thoughts?

**Comment by lnussel** [comment]
basically fine I guess but requires access permissions on the package. What about the attribute framework?

**Comment by jberry-suse** [comment]
I can double check, but I would assume it has similar limits as comments which the repo_checker goes beyond, plus it has no UI for viewing the revisions which makes it annoying to easily compare. I considered it and not opposed if it supports what we need, but also more work converting things to use attributes vs just changing the package location.

**Comment by jberry-suse** [comment]
It's really in line of "status reports" I included in presentation (which I saw a PR related to in OBS, but no idea what there "requirements" are as no one talks to the guy pointing the stuff out.
