### ISSUE TITLE
Consider replacing all conf.config[project] references with Config.get(project)

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1653]
This will is less brittle and does not require the parent calling `Config(...)` before calling the code in question. I don't see a downside as there would be no reason to spoof the contents of `conf.config` and not a good practice if someone did. This would simplify usage of a number of bits.

The pattern is what I prepared the code for for using in generic psuedometa access functions which will implicitly look for an override setting for what package name to use via remote config. If it is good enough to use there why not everywhere.

Related to outcome of #1652, but not blocking maintenance.

**Comment by coolo** [comment]
I see 2 usages of this pattern, so I don't consider it worth keeping open
