### ISSUE TITLE
Determine missing features blocking Factory switch to new pkglistgen

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1654]
With the long-term plan being to have all products on the new tool it seems like we need to figure out what is blocking Factory using it and resolve them. @DimStar77 I believe you had mentioned trying it and running into missing things, but perhaps I am just thinking about product builder related bits.

I remember there being some things related to drop list generation, but I believe (and skimming code seems to confirm) those were handled. For example, Factory will include self snapshots and previous version from Leap product family via:

https://github.com/openSUSE/openSUSE-release-tools/blob/c11f78eb83656c583cdba86c0c7537e8a46919f8/osclib/conf.py#L61

Feel free to create individual issues and include in this milestone or just comment. If nothing is known then, we'll need to test it and compare to current output (which will certainly be different which makes it a harder).

**Comment by coolo** [comment]
Not using product_converter as server side service would eliminate the problem we have with powerpc project link though :)

**Comment by coolo** [comment]
What is the status here?

**Comment by DimStar77** [comment]
Unchanged - the pkglist generator, to my information, still lacks the feature that I can have some groups done with recommends included and another group done without recommends (i.e. normal TW DVDs include recommends, Kubic excludes recommends)

**Comment by coolo** [comment]
If that's all, that I can do.

**Comment by jberry-suse** [comment]
For posterity the PR mentioned above #1781.

**Comment by coolo** [comment]
Yeah, thanks. Forgot to create the link
