### ISSUE TITLE
repo_checker: determine how to handle state demotion that causes re-checks until published

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1670]
With the addition of the following bit:

https://github.com/openSUSE/openSUSE-release-tools/blob/a6763671353675d9835b72c625a1fed017664ceb/repo_checker.py#L469-L472

This now means that while that last super slow package is building in _Factory_ `repo_checker` will check all _passing_ stagings repeatedly until _Factory_ completes building and then accept the reviews. This make sense to me since the underlying builds could change the result, but since `repo_checker` only posts comments about failures or resolved issues there is no comment indicating seen and previous state to allow for skipping. Either need to make a comment in such case (easiest), store information elsewhere on staging/request, or make some denotation locally.

**Comment by jberry-suse** [comment]
Previously, the reviews would have just been accepted as long as staging had completed building as it did not consider state of target project. Posting a comment also helps communicate that the staging has been reviewed and no problems expected.

**Comment by coolo** [comment]
no longer a problem as we check the stagings once they are done - and no longer look at layers below

**Comment by jberry-suse** [comment]
Even for adi where building can be completed while underlying layers mess with dependency chains?

**Comment by coolo** [comment]
Yes, if OBS considers the adi to be finished, we look into it. If it fails and that failure is incorrect, the next rebuild or the release manager will retrigger the check. If it passes, the chances are very high it's good.

**Comment by jberry-suse** [comment]
Sure, but that means we are ignoring the issue, not "no longer a problem". As long as we are clear.
