### ISSUE TITLE
leaper: for sle also check other service packs

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1675]
when looking for matching requests leaper on sle side should also look at lower service packs, in case a maintenance update got submitted there.

**Comment by lnussel** [comment]
(so far it only looks at leap and Factory)

**Comment by jberry-suse** [comment]
Just enable in `OSRT:OriginConfig` ;)

```yaml
- SUSE:SLE-15*:
    pending_submission_allow: true
```
