### ISSUE TITLE
check_source_submission wrongly rejects Submissions to _product Package

### ISSUE THREAD

**Issue by e4t** [openSUSE/openSUSE-release-tools#1692]
[This link](https://build.suse.de/package/requests/SUSE:SLE-12-SP4:GA/_product) shows 2 rejected submit requests. The reject reason being:
<pre>
A package submitted as _product has to build as 'Name: _product' - found Name 'None' 
</pre>
It seems that the _product packages are special and are thus not treated properly.
These packages are usually only touched by release managers, however, not all release managers have write access to the product repos - especially on SLE.

**Comment by nilxam** [comment]
Just a note for this issue: we can make check_source skips _product package, *and* if we do so that we should make sure skip staging review on it, selecting _product to a staging project is unusable.

**Comment by coolo** [comment]
for openSUSE we have no more _product - and for SLE12 the staging review is independent of the factory-auto, so no skip staging review. Just ignoring the package in check_source

**Comment by nilxam** [comment]
then https://github.com/openSUSE/openSUSE-release-tools/pull/1693 should fix this issue.

**Comment by jberry-suse** [comment]
```
$ ./check_source.py -A ibs --debug --dry id 171299
[I] checking 171299
[I] home:a_faerber:branches:SUSE:SLE-12-SP4:GA/_product@4 -> SUSE:SLE-12-SP4:GA/_product
[I] 171299 accepted: Skipping all checks for product related packages
[D] 171299 review not changed
```

**Comment by jberry-suse** [comment]
In the future please do not hesitate to open a request. No need to fight the tools.
