### ISSUE TITLE
repo_checker: consider replacing custom repo construction and external install check with python bindings

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1700]
This is something that has been discussed on and off, and I evaluated a variety of possible workflows during my recent round of work on `repo_checker`, but all fail when it comes to file conflict checks. The libsolv python bindings document the fact that they are missing this and it is unclear if the `solv` format includes enough information. Communicating the layered repositories with _simulated merges_ is also a bit tricky depending on which tool is used.

From discussions with @Conan-Kudo over the last few weeks it seems like the python bindings from dnf and hawkey are sufficient to handle the file conflicts properly. The required change would be to produce an `rpm-md` repository instead of modified `yast2` repository and use the python binding to perform the install and file conflict checks. The underlying checks then will read the source files referenced in `rpm-md` to get the full file information for the conflict checks (the missing link).

It seems https://pagure.io/rpmdeplint should be essentially what we need. Any more specific queries can be done using the API. This would allow for dropping a fair bit of perl code and the customized repository format while also allow for access to the issues in a structured form.

I haven't sat down and played with this yet, but it sounds promising. I've also heard vague information about OBS providing some checks itself, but I have my doubts it will support something sufficient for the staging process.

Thoughts?

**Comment by Conan-Kudo** [comment]
Most of what `repo_checker` and friends do is part of [`rpmdeplint`](https://pagure.io/rpmdeplint), which is used by the Fedora Updates System as one of many checks that are done on updates to validate it for sanity to push into the updates repository. The same input can be used for an implementation of a check that uses DNF API to simulate a transaction to check for install-specific conflicts (mode differences, etc.). I recently talked to @dmach about this and he was interested in helping to support that kind of stuff with the libdnf API.

**Comment by Conan-Kudo** [comment]
While that is true, openSUSE policy indicates that alternative usage is supposed to be represented by ghosting in the file list, so it should be there.

Ignoring that, this is what the installcheck would handle, since it would attempt a test transaction to validate the set for a total set of file-based conflicts. DNF already does this for normal package transactions, but also offers the ability to do _only_ that through the API.

**Comment by coolo** [comment]
As I said: to fullfill that task you need full rpm headers, not only the subset rpm-md provides.

**Comment by coolo** [comment]
BTW: not sure what documentation you check, but the %ghost is the file in /etc/alternatives not the file in /usr/bin linking there.

**Comment by jberry-suse** [comment]
My understanding was the tools read the rpms referenced in repo-md in order to have full file information. If that is not correct than yes the same things I ran into last month.

**Comment by Conan-Kudo** [comment]
That is correct.

**Comment by coolo** [comment]
This won't work - for the outlined reasons.
