### ISSUE TITLE
maintenance submission for a Factory package without devel project gets review on openSUSE:Factory

### ISSUE THREAD

**Issue by andreasstieger** [openSUSE/openSUSE-release-tools#1706]
If a package is submitted to Leap maintenance, and the Factory package of the same name has no devel project, a review is added to the maintenance submission to the project `openSUSE:Factory`, which is rarely, if ever, responded to.

E.g. `libqt5-qtbase` https://build.opensuse.org/request/show/637745

**Comment by DimStar77** [comment]
There is an underlying issue here that there should be no package in Factory (short of 00Meta and 000product) that do not have a devel project assigned

**Comment by andreasstieger** [comment]
Trying... https://build.opensuse.org/request/show/637820

**Comment by andreasstieger** [comment]
@nilxam Just trying to get your libqt5-qtbase change in.

**Comment by nilxam** [comment]
TBH the problem on https://build.opensuse.org/request/show/637745 is KDE team have a wrong development setup in KDE:Qt, KDE:Qt:XX, they want to use KDE:Qt as the devel project to Factory but those package is a link to another project eg. KDE:Qt:5.11 thus devel-project tag just went gone.

**Comment by coolo** [comment]
I don't think we should implement workarounds for workarounds. Either OBS supports this correctly or KDE team has to revert (not sure they didn't already)

**Comment by DimStar77** [comment]
> I don't think we should implement workarounds for workarounds. Either OBS supports this correctly or KDE team has to revert (not sure they didn't already)

They didn't - the submissions of libqt5-* are still coming from KDE:Qt5 - which is a 'project link' to (currently) KDE:Qt:5.11; once 5.12 is out, they want to switch the project link (allowing them to maintain the versions in parallel)

**Comment by coolo** [comment]
then this should be filed as OBS feature request to support 'meta' devel projects

**Comment by coolo** [comment]
actually why don't they just change the devel project to KDE:Qt:5.12?

**Comment by coolo** [comment]
sounds like we should forbid submissions from project links and are done.

**Comment by DimStar77** [comment]
> actually why don't they just change the devel project to KDE:Qt:5.12?

That would regularly be ~ 40 changedevel reqs; something they wanted to avoid

@Vogtinator can certainly add more background here
