### ISSUE TITLE
select --from tries to select packages from a different staging as well

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/openSUSE-release-tools#1708]
With `xdg-desktop-portal-kde` in an adi staging, `osc staging select --from D K xdg-desktop-portal-kde` tries to move it as well:
`(1/1) Moving "636539" from "openSUSE:Factory:Staging:D" to "openSUSE:Factory:Staging:K"`

It doesn't actually move the request though AFAICT.

**Comment by jberry-suse** [comment]
Based on the documentation that is an invalid command. Personally, I never use `--from` as the the package name / request number should be enough to identify a what is to be moved. Any duplicates should be handled already.

```
osc staging select [--no-freeze] [--move [--from STAGING]]
```

In general, the following should work:

```
osc staging select --move K xdg-desktop-portal-kde
```

I am going to assume the command you included is not what actually ran, otherwise I'd have to stare at this code a bit more to see how it passed the following condition.

```python
elif request in staged_requests and (move or supersede):
```

Additionally, request `636539` is for the package in your command: `xdg-desktop-portal-kde`. So it seems to have selected the appropriate package not `xdg-desktop-portal`.

Either I am missing something or this report either needs more information or has some incorrect information in it.

**Comment by Vogtinator** [comment]
That's literally what I ran and what the output was. `xdg-desktop-portal-kde` was and still is in the adi staging.

> Additionally, request 636539 is for the package in your command: xdg-desktop-portal-kde. So it seems to have selected the appropriate package not xdg-desktop-portal.

That was a typo, I meant `xdg-desktop-portal-kde`.

**Comment by jberry-suse** [comment]
To be clear, you wrote:
```
osc staging select --from D K xdg-desktop-portal-kde
```

I wrote:

```
osc staging select --move K xdg-desktop-portal-kde
```

I am going to assume you ran:

```
osc staging select --move --from D K xdg-desktop-portal-kde
```

The devil is in the details. From what you wrote:

- It failed to move request `636539` from staging `K` which seems valid since the request was not in `K`.

Again, the specifics here matter.

**Comment by Vogtinator** [comment]
Right, another typo. This time copy and pasted: `HOME=~/favogt_factory osc staging select --move --from D K xdg-desktop-portal-kde`

**Comment by jberry-suse** [comment]
Alright, so the message is wrong in that it should say failed to find request in K or something along those lines? In the future can you just skip `--from`? I would vote for removing the option entirely as a the request ID can be used if you really need to be specific.

**Comment by Vogtinator** [comment]
> Alright, so the message is wrong in that it should say failed to find request in K or something along those lines?

I guess so.

> In the future can you just skip --from? I would vote for removing the option entirely as a the request ID can be used if you really need to be specific.

Use case for the call was to move all Plasma packages from D to K, but the list of package names given also included packages which are part of adi stagings.

**Comment by jberry-suse** [comment]
`--from` does not operate as a wildcard select although that would actually make more sense. It operates as an additional constraint on where to look for the specified requests to move. So it looks for `xdg-desktop-portal-kde` in `D` instead of the `adi` where it is and thus fails to move it without printing such a message.

**Comment by jberry-suse** [comment]
Given that it can find the requests where ever they are staged I am going to assume there was some legacy reason for `--from` that as far as I can tell no longer makes sense.

**Comment by Vogtinator** [comment]
> --from does not operate as a wildcard select although that would actually make more sense. It operates as an additional constraint on where to look for the specified requests to move. So it looks for xdg-desktop-portal-kde in D instead of the adi where it is and thus fails to move it without printing such a message.

> Given that it can find the requests where ever they are staged I am going to assume there was some legacy reason for --from that as far as I can tell no longer makes sense.

It makes sense as such an additional constraint though and apparently works fine - just the message needs to be improved.

**Comment by jberry-suse** [comment]
But why would you need it if you have explicitly list all the packages you want to move anyway? It can figure out that they come from `D` and `adi` automatically.

**Comment by Vogtinator** [comment]
> I assume if you are filtering this has something to do with having a full list of kde related packages and just wanting to move the ones in D?

Yup!

> Somewhat related perhaps towards #731.

Maybe - only that an interactive window doesn't make it easily possible to use a list of packages in a file as selection:

`<plasma/pkglist-5.14 osc staging select --move --from D K`

**Comment by jberry-suse** [comment]
Well, I am not opposed to changing the behavior to print a message there that ignoring since not matching `--from` or similar. Perhaps just dropping the old and replacing with `--filter-from` or some such.

Untest, but you can try if you want since sounds like you use this.

```diff
diff --git a/osclib/select_command.py b/osclib/select_command.py
index 88edf6e3..172a91c3 100644
--- a/osclib/select_command.py
+++ b/osclib/select_command.py
@@ -73,12 +73,10 @@ class SelectCommand(object):
             return self.api.rq_to_prj(request, self.target_project)
         elif request in staged_requests and (move or supersede):
             # 'select' command becomes a 'move'
-            fprj = None
-            if from_:
-                fprj = self.api.prj_from_letter(from_)
-            else:
-                # supersede = (new_rq, package, project)
-                fprj = self.api.packages_staged[staged_requests[request]]['prj'] if not supersede else supersede[2]
+            # supersede = (new_rq, package, project)
+            fprj = self.api.packages_staged[staged_requests[request]]['prj'] if not supersede else supersede[2]
+            if from_ != fprj:
+                print('Ignoring "{}" in "{}" since not "{}"'.format(request, fprj, from_))
 
             if supersede:
                 print('"{} ({}) is superseded by {}'.format(request, supersede[1], supersede[0]))
@@ -133,6 +131,7 @@ class SelectCommand(object):
 
         requests = RequestFinder.find_sr(requests, self.api, newcand)
         requests_count = len(requests)
+        from_ = self.api.prj_from_letter(from_)
         for index, request in enumerate(requests, start=1):
             print('({}/{}) '.format(index, requests_count), end='')
             if not self.select_request(request, move, from_):
```

**Comment by Vogtinator** [comment]
That diff seems to work (ignoring the missing "in"):

```(1/1) Ignoring "636539" in "openSUSE:Factory:Staging:adi:14" since not "openSUSE:Factory:Staging:D"```
