### ISSUE TITLE
leaper: fails to add devel project review due to lacking permission

### ISSUE THREAD

**Issue by nilxam** [openSUSE/openSUSE-release-tools#1729]
Saw this error on packagelists VM, just record it here, have not dig into it.

    Oct 15 10:07:19 packagelists osrt-leaper[27193]: [I] home:MargueriteSu:branches:OBS_Maintained:transmission/transmission.openSUSE_Backports_SLE-15_Update@35c80b5ff092e2a1921
    Oct 15 10:07:19 packagelists osrt-leaper[27193]: [I] expected origin is 'openSUSE:Leap:15.0' (changed)
    Oct 15 10:07:21 packagelists osrt-leaper[27193]: [E] HTTP Error 403: Forbidden
    Oct 15 10:07:21 packagelists osrt-leaper[27193]: Traceback (most recent call last):
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:   File "/usr/share/openSUSE-release-tools/ReviewBot.py", line 835, in runner
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:     workfunc()
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:   File "/usr/share/openSUSE-release-tools/ReviewBot.py", line 817, in work
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:     self.checker.check_requests()
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:   File "/usr/share/openSUSE-release-tools/ReviewBot.py", line 169, in check_requests
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:     good = self.check_one_request(req)
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:   File "/usr/bin/osrt-leaper", line 488, in check_one_request
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:     request_ok = ReviewBot.ReviewBot.check_one_request(self, req)
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:   File "/usr/share/openSUSE-release-tools/ReviewBot.py", line 348, in check_one_request
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:     ret = func(req, a)
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:   File "/usr/share/openSUSE-release-tools/ReviewBot.py", line 407, in check_action_maintenance_incident
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:     a.tgt_releaseproject, tgt_package)
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:   File "/usr/bin/osrt-leaper", line 121, in check_source_submission
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:     self.devel_project_review_ensure(self.request, target_project, target_package)
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:   File "/usr/share/openSUSE-release-tools/ReviewBot.py", line 307, in devel_project_review_ensure
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:     return self.devel_project_review_add(request, project, package, message)
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:   File "/usr/share/openSUSE-release-tools/ReviewBot.py", line 299, in devel_project_review_add
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:     self.add_review(request, by_project=devel_project, by_package=devel_package, msg=message)
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:   File "/usr/share/openSUSE-release-tools/ReviewBot.py", line 288, in add_review
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:     r = osc.core.http_POST(u, data=msg)
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:   File "/usr/lib/python2.7/site-packages/osc/core.py", line 3356, in http_POST
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:     def http_POST(*args, **kwargs):   return http_request('POST', *args, **kwargs)
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:   File "/usr/share/openSUSE-release-tools/osclib/cache.py", line 39, in http_request
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:     ret = osc.core._http_request(method, url, headers, data, file)
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:   File "/usr/lib/python2.7/site-packages/osc/core.py", line 3344, in http_request
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:     fd = urlopen(req, data=data)
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:   File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:     return opener.open(url, data, timeout)
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:   File "/usr/lib64/python2.7/urllib2.py", line 435, in open
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:     response = meth(req, response)
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:   File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:     'http', request, response, code, msg, hdrs)
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:   File "/usr/lib64/python2.7/urllib2.py", line 473, in error
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:     return self._call_chain(*args)
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:   File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:     result = func(*args)
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:   File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default
    Oct 15 10:07:21 packagelists osrt-leaper[27193]:     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    Oct 15 10:07:21 packagelists osrt-leaper[27193]: HTTPError: HTTP Error 403: Forbidden

**Comment by jberry-suse** [comment]
I had commented this bit out to run in "comment-only mode", but was not expecting it to go on this long. As such should likely just merge that change to avoid having to re-apply.
