### ISSUE TITLE
Improve maintbot and check_source processing patchinfo workflow

### ISSUE THREAD

**Issue by nilxam** [openSUSE/openSUSE-release-tools#1730]
If an maintenance incident has patchinfo included, maintbot/ReviewBot will ignore it, however if maintbot haven't found any bad issue on this request, and maintbot already did it work to added required reviews to the request, patchinfo should not be an issue deny to accepting *maintbot* review on an maintenance incident. An example https://build.opensuse.org/request/show/641770

And on SR#641770 , check_source ignores it due to 
`
[D] ignoring patchinfo action
`
we should skip patchinfo but continue processing other packages instead of keep review opened.

CC @andreasstieger

**Comment by jberry-suse** [comment]
Should work fine with `leaper` implementation and did your pr (#1728) fix maintbot?

**Comment by nilxam** [comment]
https://github.com/openSUSE/openSUSE-release-tools/pull/1728 fixed maintbot haven't crashes when using `.tgt_releaseproject` .

The remaining things is we have below in several places, if an maintenance incident has patchinfo package included eg. SR#641770 , `maintbot` and `check_source` will ignore it because of `actions[0]` is patchinfo, it is a valid request but will not moving, that is the workflow need to be improved.

    if self._is_patchinfo(a.src_package):
        return None

**Comment by coolo** [comment]
I'm honestly lost on what is the impact and the missing changes.

**Comment by nilxam** [comment]
If patchinfo lists as the first action, this incident will  be ignored and will not be proceeded(approving review), just pending there.
