### ISSUE TITLE
CI: tar service failing

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1732]
Re-ran last master branch job and went from passing to failing so something changed, presumably external to this repository.

```
[   28s] now finalizing build dir...
[   28s] /usr/lib/build/init_buildsystem: line 1077: hostname: command not found
[   28s] Running build time source services...
[   28s] Error while moving from 'openSUSE-release-tools' to 'openSUSE-release-tools-20181015.c6ff801')
[   28s] Current working directory: '/home/abuild/rpmbuild/SOURCES'
[   28s] service run failed for service 'tar'
[   28s] 
[   28s]  failed "build openSUSE-release-tools.spec" at Mon Oct 15 21:11:29 UTC 2018.
[   28s] 
The buildroot was: /var/tmp/build-root/openSUSE_Factory-x86_64
The command "./dist/ci/docker-run obs-build-target "$TARGET_REPO"" exited with 1.
```

**Comment by jberry-suse** [comment]
Of potential interest, today's TW release includes:

```
obs-service-tar_scm (0.9.1.1534504824.0732756 -> 0.9.4.1537959361.56833cb)
```

**Comment by jberry-suse** [comment]
Nothing obvious in code, although related lines were touched.

Likely scope being the [request 639875](https://build.opensuse.org/request/show/639875).

**Comment by jberry-suse** [comment]
Referencing primary authors in-case something jumps out to them: @M0ses @adrianschroeter.

**Comment by jberry-suse** [comment]
The error is coming from:

https://github.com/openSUSE/obs-service-tar_scm/blob/fefaa74facd1687b683f51ff092651056cc11152/TarSCM/scm/tar.py#L35-L45

seems like the `self.basename` which is set to `self.read_from_obsinfo(self.args.obsinfo, "name")` is not actually available. The structure of cpio is the same as it was months ago (comparing local checkouts). It seems like the cpio is not being extract ahead of the tar service so there is no directory to tar.

**Comment by jberry-suse** [comment]
The build works on OBS, but not using TW version of `tar_scm` which I will assume is not being used on OBS workers yet.

**Comment by jberry-suse** [comment]
Looks the same as other `obs_scm` setups https://build.opensuse.org/package/view_file/hardware:RC-Model:Unstable/qgroundcontrol/_service?expand=1.

**Comment by jberry-suse** [comment]
The issue is actually much further up (this also makes more sense with changes made to `tar_scm`:

```
+ rm openSUSE-release-tools-20181015.c6ff801.obscpio
+ osc -v service disabledrun
makeurl: https://api.opensuse.org ['source', 'openSUSE:Tools', 'openSUSE-release-tools'] cmd=getprojectservices
Run source service: /usr/lib/obs/service/obs_scm --versionformat %cd.%h --url /usr/src/target --scm git --revision heads/master-2-ge1ff954 --changesgenerate enable --extract dist/package/openSUSE-release-tools.spec --filename openSUSE-release-tools --outdir /usr/src/openSUSE:Tools/openSUSE-release-tools/tmpbzssXz.obs_scm.service
--url does not match remote repository
Aborting: service call failed:  /usr/lib/obs/service/obs_scm --versionformat %cd.%h --url /usr/src/target --scm git --revision heads/master-2-ge1ff954 --changesgenerate enable --extract dist/package/openSUSE-release-tools.spec --filename openSUSE-release-tools --outdir /usr/src/openSUSE:Tools/openSUSE-release-tools/tmpbzssXz.obs_scm.service
```

**Comment by jberry-suse** [comment]
As  noted in the fix, this was caused by openSUSE/obs-service-tar_scm@44b3bee as I suggested when mentioning authors above.

**Comment by adrianschroeter** [comment]
On Mittwoch, 17. Oktober 2018, 21:00:24 CEST Jimmy Berry wrote:
> The build works on OBS, but not using TW version of `tar_scm` which I will
> assume is not being used on OBS workers yet.

buildtime source services are comming from your distro. The workers have no 
influence.

-- 

Adrian Schroeter
SUSE Linux Products GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
email: adrian@suse.de
