### ISSUE TITLE
repo_checker: problem with Leap 42.3 NonFree

### ISSUE THREAD

**Issue by andreasstieger** [openSUSE/openSUSE-release-tools#1735]
repo-checker does not seem to support checking Leap 42.3 Non-Free updates. The maintenance release request [SR#642783](https://build.opensuse.org/request/show/642783) was declined with the following message:

> a repository must be specified via OSRT:Config main-repo for openSUSE:Leap:42.3:NonFree:Update

@jberry-suse

**Comment by jberry-suse** [comment]
Related to #1384 and #1247 although simpler since `StagingAPI` (and merge of `NonFree` into main `Staging` project) is not involved.

**Comment by jberry-suse** [comment]
Once the related request is merged and deployed repo-open the request. I'll indicate here when it is deployed. Otherwise, use the override if cannot wait.

**Comment by jberry-suse** [comment]
@andreasstieger Deployed so should be able to re-open request.

**Comment by jberry-suse** [comment]
Accepted review, and logs indicate it reviewed the `NonFree` repository stacks.
