### ISSUE TITLE
CI: automatic submission to factory stopped working

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1749]
```
checking for existing requests to /...
<collection matches="0">
ok
Package 'openSUSE-release-tools' is not a source link, so I cannot guess the submit target.
Please provide it the target via commandline arguments.
-> no difference (likely cron job)
```

Looks like some sort of `osc` change.

**Comment by jberry-suse** [comment]
Not sure if [revision 586](https://build.opensuse.org/package/rdiff/openSUSE:Tools/openSUSE-release-tools?linkrev=base&rev=568) by @coolo caused the issue. I get `Problem getting expanded diff: bad link: conflict in file _servicedata` when viewing it and a submission to Factory was manually created after that.

I re-instated link via:

```
osc linkpac openSUSE:Factory openSUSE-release-tools openSUSE:Tools
```

and `osc sr` now works correctly.

**Comment by jberry-suse** [comment]
Every now and again a conflict arises and must be resolved manually which can be cumbersome to handle properly. Wondering if that is what happened.

**Comment by jberry-suse** [comment]
[request 644728](https://build.opensuse.org/request/show/644728) was created via CI so the problem is resolved.

**Comment by jberry-suse** [comment]
I see in shared diary:

```
Resolved broken state of openSUSE-release-tools, removed _link, submitted to Factory
```

Normally, have to do `osc pull` and resolve workflow to avoid nuking link.

**Comment by coolo** [comment]
without the _link you don't get the problem. So I'd prefer if we stayed without _link and passed a submission target

**Comment by jberry-suse** [comment]
Having a link seems to be the default behavior for devel packages as that is how they are setup after being accepted to Factory and allows for the _diff_ link. The problem to which you are referring is the occasional merge conflict? If so this seems like an OBS issue that should be resolved since it always has to do with _servicedata which nearly always different. The fact that it only happens sometimes is the confusing part.
