### ISSUE TITLE
osc staging select X --move -> fails if no --filter-from is given

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/openSUSE-release-tools#1750]
Since recent changes, it is no longer possible to simply call 

```osc staging select H --move rubygem-rspec rubygem-rspec-core rubygem-rspec-expectations rubygem-rspec-mocks rubygem-rspec-support```

>(1/5) Ignoring "627632" in "openSUSE:Factory:Staging:E" since not in "None"
>(2/5) Ignoring "627633" in "openSUSE:Factory:Staging:E" since not in "None"
>(3/5) Ignoring "636986" in "openSUSE:Factory:Staging:E" since not in "None"
>(4/5) Ignoring "627635" in "openSUSE:Factory:Staging:E" since not in "None"
>(5/5) Ignoring "628914" in "openSUSE:Factory:Staging:E" since not in "None"

for now I worked around by explicitly specifying --filter-from E, which helps to get things going

**Comment by jberry-suse** [comment]
As noted the original PR needed tested and was thus merged prematurely due to miscommunication. Sorry about that.
