### ISSUE TITLE
port osc staging check and openqa-comments to new OBS staging API

### ISSUE THREAD

**Issue by coolo** [openSUSE/openSUSE-release-tools#1768]
This affects check command's output and openqa-comments.
I tried to fix the former: https://github.com/openSUSE/openSUSE-release-tools/pull/1767

But fixing the tests and fixing openqa-comments is above me. Please follow up - this breaks Factory workflow (and will soonish SLE as IBS is deployed)

**Comment by jberry-suse** [comment]
Perhaps we should not remove features until we've migrated!?

**Comment by coolo** [comment]
https://www.youtube.com/watch?v=0AFy_82wiRI comes into my mind. But as I unblocked @DimStar77 the most critical piece is fixing openqa-comments to take checks.

**Comment by jberry-suse** [comment]
Just following my programming as per perception.

**Comment by lnussel** [comment]
so the fix for the check command is # #1767. What's missing is
* adjusting the test suite for #1767 
* porting openqa-comments.py from openqa_jobs to checks/missing_checks

we also need openqa-comments enabled for 15.1 still, can you take a look please?

**Comment by jberry-suse** [comment]
> we also need openqa-comments enabled for 15.1 still, can you take a look please?

Service is already running.

**Comment by coolo** [comment]
https://github.com/openSUSE/openSUSE-release-tools/pull/1767 has adjusted test suite now, it was quite some work as the fixtures were pretty old
