### ISSUE TITLE
CI: tests fail for the last three days, but passed pre-merge

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1770]
As normally happens, tests failed, the person who merged got an e-mail from travis and nothing was done. :( I noticed when I went to merge one of my pull requests and so I am filing an issue.

PR #1755 
- [passed pre-merge](https://travis-ci.org/openSUSE/openSUSE-release-tools/builds/448219411)
- [failed post-merge](https://travis-ci.org/openSUSE/openSUSE-release-tools/builds/450752654)

Would seem to point in the direction of upstream.

**Comment by coolo** [comment]
httppretty was updated that day: https://github.com/openSUSE/openSUSE-release-tools/pull/1771 works around it.

**Comment by lnussel** [comment]
huh? #1755 has no indication at all that anything went wrong with travis.

**Comment by coolo** [comment]
@jberry-suse is saying you should have got an email after merge

**Comment by jberry-suse** [comment]
Makes sense as it did not appear to be the fault of any changes in this repo.

**Comment by jberry-suse** [comment]
Created config change to notify list so those interested can be notified in the future.
