### ISSUE TITLE
openSUSE OpenQA bot does not schedule any per-incident tests for incidents containing many packages

### ISSUE THREAD

**Issue by andreasstieger** [openSUSE/openSUSE-release-tools#1782]
The openSUSE OpenQA bot does not trigger tests for certain types of incidents. The only known characteristic in common is that the incidents have a lot of built packages.

See: https://build.opensuse.org/request/show/648237 (LibreOffice) https://build.opensuse.org/project/show/openSUSE:Maintenance:9145
Message: `no openQA tests defined`

Also: https://build.opensuse.org/request/show/642407 (texlive) https://build.opensuse.org/project/show/openSUSE:Maintenance:8922

**Comment by coolo** [comment]
Most likely some timeouts somewhere triggering a too global exception. But as this a) 4 years old without update and b) these packages are now coming from SLE I'll close
