### ISSUE TITLE
Have staging accept put the TW version in an attribute

### ISSUE THREAD

**Issue by coolo** [openSUSE/openSUSE-release-tools#1800]
To support pkglist workflow, we need to stop modifying product - but have pkglistgen write a 000product with the right version.

So we discussed to have staging accept (additionally for now) write the TW version in a OSRT:ProductVersion attribute.

This would then be patched into the generated product by pkglistgen.

**Comment by coolo** [comment]
@nilxam is this something you can look at?

**Comment by coolo** [comment]
Created OSRT:ProductVersion modifiable by target maintainer and maxlin_factory on obs and ibs.

**Comment by nilxam** [comment]
I think we can close this issue? or is there something else undone?

**Comment by coolo** [comment]
no
