### ISSUE TITLE
droplist generator: unstable output

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1806]
A maintenance release of SDL2_image caused basically a noop diff in the obsolete package list with different sort order. causing a needless build:
https://build.opensuse.org/package/rdiff/openSUSE:Leap:15.1/000product?linkrev=base&rev=1174

**Comment by lnussel** [comment]
the libapparmor change seems weird too. not sure it actually happened

**Comment by jberry-suse** [comment]
The other changes appearing to be an ordering issue?

**Comment by coolo** [comment]
will redo the droplist generation
