### ISSUE TITLE
pglistgen: no way of adding suggested packages to a medium

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/openSUSE-release-tools#1816]
Background: openSUSE Tumbleweed (so far) uses patterns to define what goes on the various media.

A bunch of patterns use 'Suggests:' to have stuff added to the DVD without having packages pre-installed on machines (this concept should actually be more important for Leap, as for TW we can at least argue that online access is pretty much necessary anyway)

At this moment, pkglistgen has no way of defining that we'd want to have the suggested packages added to the medium as well.

Would be nice to be able to switch this on/off, similar to the way we do it with Recommends now.

**Comment by coolo** [comment]
fixed in refactor_pkglistgen branch
