### ISSUE TITLE
TTM should generate a permanent label for published builds

### ISSUE THREAD

**Issue by asdil12** [openSUSE/openSUSE-release-tools#1818]
This way it would be possible to see in https://openqa.opensuse.org/group_overview/1 for each snapshot if it was actually released/published.

**Comment by okurz** [comment]
@jberry-suse could this be something for you to look into or should @asdil12 and me try?

**Comment by DimStar77** [comment]
Comments are added to the TW dashboard by now - and we know which snapshot has been published

See https://openqa.opensuse.org/group_overview/1

Does that match the expectation?

**Comment by asdil12** [comment]
That looks nice.

**Comment by DimStar77** [comment]
ok - let's consider this fixed
