### ISSUE TITLE
duplicate_binaries contains python structures(?) dump

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1820]
https://build.opensuse.org/package/view_file/openSUSE:Leap:15.1:Staging/dashboard/duplicate_binaries?expand=1

>   state:
>     _parent: !!python/object:lxml.etree._Element {}
>     attrname: null
>     is_attribute: false
>     is_tail: false
>     is_text: true

**Comment by nilxam** [comment]
fixed.
