### ISSUE TITLE
repo-checker approves a file conflicted request

### ISSUE THREAD

**Issue by nilxam** [openSUSE/openSUSE-release-tools#1823]
It's weird see this happened on readline submission[1], although we see `file conflict` check still works in other places. `readline`[1] is a package separated from `bash` in Factory, however this feature has not been implemented in Leap, therefore in Leap eg. libreadline.so.7 is provided by `bash` package. While `readline` submission[1] stay in the Leap staging, repo-checker giving a green light on it but it should indeed have file conflict issue with `bash`.

[1] https://build.opensuse.org/request/show/655243

**Comment by DimStar77** [comment]
same binary names are a disaster in any case - and should be blocked / detected and denied.

**Comment by nilxam** [comment]
so we should *caught* this during staging project period, repo-checker should do duplicate binary check also then.

**Comment by nilxam** [comment]
so this is related to https://github.com/openSUSE/openSUSE-release-tools/issues/1031

**Comment by coolo** [comment]
Since #2081 we block duplicated binaries - this should help
