### ISSUE TITLE
suppkg_rebuild: the binarylist query takes a lot of time

### ISSUE THREAD

**Issue by mlschroe** [openSUSE/openSUSE-release-tools#1826]
I noticed in the slow request log that there are quite some requests to _result with view=binarylist. This is a time consuming and expensive operation as it needs to gather all files from all built packages. If you're only interested in data for binaries (and not in stuff like rpmlint.log) it is much faster to do a view=binaryversions request on the project, e.g.:
```
osc api /build/openSUSE:Factory/standard/x86_64?view=binaryversions
```

**Comment by coolo** [comment]
thanks Max!
