### ISSUE TITLE
sub-package does not created when selecting to adi staging

### ISSUE THREAD

**Issue by nilxam** [openSUSE/openSUSE-release-tools#1830]
openQA-test subpackage doesn't created while selecting openQA submission, this breaks accept command when it trying to removing openQA-test package. **Note that** this looks not a command situation, just a special case.

<pre>
Jan 13 15:49:48 packagelists osrt-staging-bot[14959]: adi:46 ready
Jan 13 15:49:48 packagelists osrt-staging-bot[14959]:  - openQA [664637]
Jan 13 15:49:49 packagelists osrt-staging-bot[14959]: Server returned an error: HTTP Error 404: Not Found
Jan 13 15:49:49 packagelists osrt-staging-bot[14959]: openSUSE:Leap:15.1:Staging:adi:46/openQA-t
</pre>

**Comment by nilxam** [comment]
found another one, `libmlt` 's subpackage `webvfx` does not created.

**Comment by nilxam** [comment]
I can't find anything wrong in code, need to find a reproduce way, this possibly check whether package container existing too soon just right after pushed `_link` then returned empty `[]` in `get_sub_packages()`, not 100% sure...

**Comment by nilxam** [comment]
happened again,

$ osc ls openSUSE:Leap:15.1:Staging:adi:36
openQA
os-autoinst

:/

**Comment by nilxam** [comment]
Occurred on `FreeCAD`. Is it possible because it checking package container meanwhile source service has not to be done?

**Comment by coolo** [comment]
No, we lack proper support for this completely. Also for rings - but there we rely on freeze playing tricks. I would like to get rid of these tricks - and fix select

**Comment by nilxam** [comment]
but this ticket is about `adi staging`, staging tool is creating sub-package per specfile in the source container, isn't?

**Comment by coolo** [comment]
it doesn't really matter what type the staging project is. We need to instantiante all spec files in that project.

**Comment by coolo** [comment]
fixed now, slightly overshadowed by the change the python3 though
