### ISSUE TITLE
pkglistgen: Support 'required' package role

### ISSUE THREAD

**Issue by coolo** [openSUSE/openSUSE-release-tools#1844]
For Factory stagings we want uninstallable "important" patterns to stop building Test DVDs. For Leap this is the default by mean of OSRT:Config's pkglistgen-ignore-unresolvable. Leaving it to openQA to detect KDE being uninstallable is a waste of resource

**Comment by nilxam** [comment]
Perhaps intentionally inserts a `not exists package or a string` to repopackage to make DVD build fail?

**Comment by coolo** [comment]
As we're working towards a working pipeline, an exit 1 would be good enough. The product shouldn't be build enabled before it's ready

**Comment by coolo** [comment]
But to avoid suprises, we can still commit an obviously broken product.

**Comment by DimStar77** [comment]
> But to avoid suprises, we can still commit an obviously broken product.

If we can have the 'error' of the breakage inside the product would be an advantage. The less switching between tools (e.g. obs/botmaster) is needed the easier the task becomes

**Comment by coolo** [comment]
Is the PR good enough for you?
