### ISSUE TITLE
openqa-maintenance: incomplete jobs taken as passed?

### ISSUE THREAD

**Issue by okurz** [openSUSE/openSUSE-release-tools#1858]
https://build.suse.de/project/show/SUSE:Maintenance:10277 shows the openqa report as all green but https://openqa.suse.de/tests/2442755# as part of the corresponding tests is "incomplete" and unlabeled. Should that not be regarded as failure? Could it be that "incompletes" are taken as passed?

**Comment by okurz** [comment]
@mimi1vx ?

**Comment by coolo** [comment]
the bot is maintained on gitlab - what's here is just used for opensuse

**Comment by okurz** [comment]
reported as https://gitlab.suse.de/qa-maintenance/openQABot/issues/15
