### ISSUE TITLE
selecting package with multiple spec files does not create links

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1866]
curl ended up in Leap staging A but the curl-mini package wasn't created. Lead to a false positive indicating build cycle.

**Comment by nilxam** [comment]
hmm... we never ever creating inner-project links in the letter staging, and I don't get why do this just appears since curl submission in staging A has not changed build requirement.

**Comment by coolo** [comment]
Indeed, curl-mini is a _link to curl in the frozenlinks. So curl-mini builds the selected curl. If that doesn't work, your link in ring1 is broken. But I'm working on making it more obvious by creating links on select

**Comment by coolo** [comment]
this is fixed now - staging select creates links, freeze ignores them.
