### ISSUE TITLE
origin-manager[crawler]: request human review of bot declining a bot request

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1880]
While monitoring the `origin-manager` queue and results I noticed `factory-auto` seemingly produced an invalid result on [request#680187](https://build.opensuse.org/request/show/680187). Since the request was created by `leaper` the author is not there to push back on the result. It may also be taken as a signal to update crawler to no longer update the package.

It seems like in such cases (bot decline a bot request) a fallback human review should be added (`leap-reviewers`). Likely this should be a `ReviewBot` feature when declining a request where the author is another tool.

I imagine the same can happen with the factory submitter (to be replaced by origin-manager) in Factory as well.

**Comment by jberry-suse** [comment]
Alternatively, this could be implemented by requesting bot (leaper and soon to be origin-manager) that upon request decline it escalates if declined by bot and otherwise revokes request.

**Comment by coolo** [comment]
Hmm, for factory-maintainer auto submissions, the factory-auto decline is actually meant to happen. So IMO the submitting bot needs to decide itself what to do with bot declines.

**Comment by lnussel** [comment]
So far bots/scripts that produce requests don't follow up on them and those scripts have no common base. So it might be easier to indeed put the framework to know about fellow bots and how to deal with them into ReviewBot.

**Comment by coolo** [comment]
this sounds specific to factory-auto to me, as it does some level of origin manager check as well.

**Comment by jberry-suse** [comment]
The factory-auto devel project check will eventually be replaced by origin-manager although not really relevant to this discussion. As for factory-auto intended to decline auto submissions sure, but a maintainer will likely eventually follow-up on that. In this case factory-auto likely had a network issue and declined mistakenly which is then taken a single to no longer up the package...all of which no one would notice unless they explicitly go looking.

For factory maintainer I would be fine with keeping current workflow although adding the package maintainer as a reviewer would also seem reasonable, but for update crawler any auto declines should be escalated. Either a false-negative as this case, or policy differences either of which should be resolved by a human.

When I rewrite update crawler it seems reasonable to create a framework for generating requests which can include following up on them in this manor. The factory script will be replaced by the origin-manager update crawler as well so both instances should be resolved. Additionally, long-term I would expect the fcc_submitter to either be rework on this framework or to become part of origin-manager update crawler.

**Comment by jberry-suse** [comment]
I think this is worth including in Origin manager milestone pertaining to update crawler.

**Comment by coolo** [comment]
I see. agreed to the 'adding package maintainer as a reviewer'

**Comment by coolo** [comment]
as we don't use the update crawler at this point, I'm closing
