### ISSUE TITLE
origin-manager: include origin annotation in comment when waiting

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1881]
https://build.opensuse.org/request/show/680385

changing from SLE to Factory must be highlighted. Normally we do not want to allow that at all.

**Comment by jberry-suse** [comment]
The same change to a lower priority happens anytime a package inherited from previous Leap version is updated to latest Factory. An option could be added to decline lower priority from a current SLE origin, but imagine there are cases that happens as well so human review is probably best.

As for highlighting I think that has been a problem, especially on maintenance requests, for a long time and someone worked around by comments, but those have their own problems. I think the best solution would be a trivial UI tweak on OBS side which I have [requested with details and a mock up](https://github.com/openSUSE/open-build-service/issues/7088).

**Comment by lnussel** [comment]
Ok so the UI tweak seems to be in place but origin manager now doesn't tell anything about the expected origin anymore:
https://build.opensuse.org/request/show/685557

**Comment by coolo** [comment]
No, this looks like my fault.

```
  <review state="new" when="2019-03-16T10:33:36" who="origin-manager" by_group="leap-reviewers">
    <comment>Changing to a lower priority origin.</comment>
  </review>
```

gives a comment, but not a reason. The review model in OBS is a mess :(

**Comment by lnussel** [comment]
To clarify, the OBS UI part is just fine. The review comment by origin-manager is shown. It's just that origin-manager didn't state what the actual origin change is. Looks like it does that only when accepting a review, in the aforementioned case it was still waiting for a factory request.

**Comment by jberry-suse** [comment]
I can add the origin changes to a comment when pending, but that may not be what everyone likes per #1897. Otherwise, my expectation was the UI, but we deployed before that exists so in an odd place right now.

**Comment by jberry-suse** [comment]
The second part of this issue is now tracked in #1905.
