### ISSUE TITLE
add security-team review for rpmlint changes

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1882]
rpmlint so far makes packages fail to build on security policy violations, like setuid binaries, polkit privileges etc. That is rather annoying and blocks people from doing their work when that happens in devel projects. So instead of doing that the badness settings of the failures in question need to be moved to rpmilnt-Factory-strict. Additionally a bot should catch violations in requests and add security-team as reviewer.

According to https://build.opensuse.org/package/view_file/openSUSE:Factory/rpmlint-Factory/config we need

suse-dbus-unauthorized-service
polkit-unauthorized-file
polkit-unauthorized-privilege
polkit-untracked-privilege
permissions-unauthorized-file
permissions-file-setuid-bit
non-position-independent-executable

**Comment by coolo** [comment]
and is the security-team fine with that?

**Comment by DimStar77** [comment]
We have a bot that striclty denies setBadness in rpmlintrc

**Comment by coolo** [comment]
@lnussel your request is very unclear. Please reopen with more details on what you want to achieve
