### ISSUE TITLE
repochecker: blind spot when removing requests from staging?

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1883]
In https://build.opensuse.org/project/show/openSUSE:Leap:15.1:Staging:adi:76 repo-checker reports that the problems are resolved but none of the two remaining requests have the repo-checker review accepted.

**Comment by coolo** [comment]
there is a reason I'm reworking this.

**Comment by DimStar77** [comment]
>  In https://build.opensuse.org/project/show/openSUSE:Leap:15.1:Staging:adi:76 repo-checker reports that the problems are resolved but none of the two remaining requests have the repo-checker review accepted.

You have to delete the comment. Somehow r-c comes into a mode where it has the right ID marked in the comment that it checked it, but probably there is code left that 'downgraded' the accept to ignore if target was not fully built. I'd seen that a couple of times in the last weeks

Of course only a workaround, but with the reworks ongoing at the moment, probably the best short-term solution

**Comment by jberry-suse** [comment]
Assuming it causes a rebuild, repo-checker will re-evaluate the requests in staging. If it does not then it will consider the build unchanged, as such removing comment works as intended. This is one of the problems with not having central orchestration based on proper events from OBS. You could spend an eternity trying to write code to handle all the possible state changes.

**Comment by lnussel** [comment]
in this case it fixed itself actually

**Comment by coolo** [comment]
it didn't :)
