### ISSUE TITLE
repo-checker does not handle indirect conflicts properly

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/openSUSE-release-tools#1885]
`kile-lang` requires `kile`
`kile5-lang` requires `kile5`
`kile5` conflicts `kile`

This means `kile-lang` and `kile5-lang` can't be installed together on the same system.
repo-checker doesn't realize that and declines the `kile5` review as the `-lang` packages have file conflicts.

**Comment by coolo** [comment]
Yeah. And it's unlikely to change.

**Comment by lnussel** [comment]
so wontfix?

**Comment by coolo** [comment]
Unless a complete rewrite of the fileconflicts script comes along, yes.

**Comment by gonzoleeman** [comment]
so having everyone modify SPEC files is easier, for the company, than re-writing a script?

**Comment by coolo** [comment]
Feel free to give it a try. and it's not 'everyone' - there have been 2 cases in 2 years.

**Comment by gonzoleeman** [comment]
In that case, I assume there's a relatively easy method to override the check when it gives a false positive.

**Comment by Vogtinator** [comment]
Shuld be fixed by https://github.com/openSUSE/openSUSE-release-tools/pull/3063
