### ISSUE TITLE
repo_checker: cycle comment broken by recent changes

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1914]
![image](https://user-images.githubusercontent.com/22943929/54834711-b8bd6e00-4c8e-11e9-8e52-05f9ba02960b.png)

(continues for several thousand pixels)

3cd79db20675ffe1f6368e8c85d8bcf15246ec90

Note the intentional indentation and bullet point markdown in the previous code that made it both readible in plain-text email as well as markdown to html.

I would find it hard to believe one tested this new code with OBS comment as the screenshot speaks for itself.

**Comment by coolo** [comment]
installcheck creates text files and repo checker comments are only left in maintenance projects - and I would argue cycle checks are worthless in them. So I guess plain removal of the cycle code in repo checker would fix it

**Comment by jberry-suse** [comment]
Perhaps going forward, but this comment was made in a Leap staging and certainly was not a unreadable wall of text before the change.

**Comment by coolo** [comment]
Right. But I changed Leap
