### ISSUE TITLE
repo_checker: file conflict check does not include non-ring packages against ring due to recent changes

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1915]
As I noted before changes were merged and has been discussed at meetings, but since not resolved for several weeks creating issue to track.

**Comment by coolo** [comment]
as discussed in meetings as well, this will be done after totest manager is a pipeline

**Comment by coolo** [comment]
After 3 years living with stagings only looking at stagings we actually prefer it this way. Integrating a global file conflict check into the release process (as indicated in the last comment) isn't as important as we thought when introducing the repo checker
