### ISSUE TITLE
repo_checker: order of requests matters since recent changes were not done consistently to all request types

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1916]
As I pointed out in regards to the approach, but was left for weeks. My understanding is this was worked around using out-of-tree changes in production.

**Comment by coolo** [comment]
I need a little more context - I don't understand

**Comment by jberry-suse** [comment]
Was discussed an issue with stagings containing delete requests and result being inconsistent. Perhaps rather than fixed just not stagings causing problem for a while. Was making place-holders for issues already discussed.

**Comment by coolo** [comment]
Factory and Leap no longer use repo checker - and SP1 will have to live with this. *Any* change there is considered problematic.

So I'll close

**Comment by jberry-suse** [comment]
So was the one that led to this...
