### ISSUE TITLE
dist/kiwi: un-resolvable image build after dummy-release change

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1926]
Seemingly related to [request 686417 for dummy-release](https://build.opensuse.org/request/show/686417) to require `this-is-only-for-build-envs` as the [image build](https://build.opensuse.org/package/show/openSUSE:Tools:Images/osrt-worker-obs) now fails with:

```
nothing provides this-is-only-for-build-envs needed by dummy-release
```

Given our kiwi does not (or should not) depend on any release directly, this is perhaps an issue with base container that is used to build OSRT image. Regardless of the solution, tracking here since it breaks OSRT container building.

**Comment by coolo** [comment]
What's in the base container doesn't matter here (and the base container has openSUSE-release-ftp)

This is what is expanded for the image:
```
expand args: python3-kiwi kiwi-image-docker-requires openSUSE-release-tools-check-source openSUSE-release-tools-leaper openSUSE-release-tools-obs-operator openSUSE-release-tools-origin-manager openSUSE-release-tools-pkglis
tgen openSUSE-release-tools-repo-checker openSUSE-release-tools-staging-bot kiwi-packagemanager:zypper !systemd-mini !udev-mini !krb5-mini !libsystemd0-mini !libudev-mini1 !gettext-tools-mini !curl-mini !systemd-mini-sysvi
nit liblua5_3-5 aaa_base attr bash coreutils diffutils filesystem fillup glibc grep libbz2-1 libgcc_s1 libncurses6 pam permissions rpm rpm-config-SUSE sed tar libz1 libselinux1 liblzma5 libcap2 libacl1 libattr1 libpopt0 li
belf1 libpcre1 libreadline8 rpm-build gcc-PIE perl build-mkbaselibs brp-check-suse post-build-checks rpmlint-Factory hostname build-compare brp-extract-appdata --ignoreignore--
```

And aaa_base requires a distribution-release and openSUSE:Factory prefers dummy-release. @DimStar77 and me already discussed to avoid this prefer for 'images' and 'containers'. There we should prefer openSUSE-release

**Comment by coolo** [comment]
This is how it looks without the prefer for dummy-release:

```
have choice for distribution-release needed by aaa_base: dummy-release openSUSE-Tumbleweed-Kubic-release openSUSE-release
```

So basically we have 2 products in Tumbleweed.

**Comment by coolo** [comment]
the factory prjconf has been fixed
