### ISSUE TITLE
A delete request against NonFree break down staging-bot

### ISSUE THREAD

**Issue by nilxam** [openSUSE/openSUSE-release-tools#1932]
https://build.opensuse.org/request/show/688501 is a delete request against NonFree package, as it's a delete request then staging-bot tries to select it to a letter staging, during that somehow failed.

<pre>
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]: 0#none@all:
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:   bootstrap_required: false
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:   group: all
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:   requests:
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:     688501: cg
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:     688605: skelcd-control-openSUSE
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:     688681: NetworkManager
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:     688682: remmina
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:     688765: perl-CGI
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:     688788: ImageMagick
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:     688789: libmspack
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:     688790: dracut
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:     688810: kcmutils
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:     688875: libzypp
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:     688876: yast2-bootloader
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:     688877: zypper
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:     688878: transactional-update
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:     689077: wavpack
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:     689078: ntp
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:     689079: libcaca
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:     689080: gd
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:     689119: LibVNCServer
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:     689120: gnome-control-center
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:     689121: yum
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:     689122: kwalletmanager5
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:   staging: D
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:   strategy:
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]:     name: none
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]: 
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]: Accept proposal? [y/n] (y): y
Mar 28 10:29:43 packagelists osrt-staging-bot[31164]: Staging 0#none@all in D
28 10:29:47 packagelists osrt-staging-bot[31164]: Request 688501 is not for openSUSE:Leap:15.1, but for openSUSE:Leap:15.1:NonFree
Mar 28 10:29:47 packagelists osrt-staging-bot[31164]: 
Mar 28 10:29:47 packagelists systemd[1]: osrt-staging-bot-regular@openSUSE:Leap:15.1.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 28 10:29:47 packagelists systemd[1]: osrt-staging-bot-regular@openSUSE:Leap:15.1.service: Unit entered failed state.
Mar 28 10:29:47 packagelists systemd[1]: osrt-staging-bot-regular@openSUSE:Leap:15.1.service: Failed with result 'exit-code'.
</pre>

**Comment by jberry-suse** [comment]
Based on the error, I would bet staging a :NonFree delete does not work properly at all.

**Comment by jberry-suse** [comment]
Yeah, no delete requests against Factory:NonFree have been staged and this is first to Leap:15.1. Would seem like this should have been reported a while ago and not related to staging-bot. One can see the proposal phase is done and failing running the equivalent of:

```
osc staging select D cg
```

Which interestingly works if that is a submit.

**Comment by coolo** [comment]
it's a while that we deleted non-free stuff (and even get requests for it :)

**Comment by jberry-suse** [comment]
7 days ago: https://build.opensuse.org/request/show/687276

**Comment by jberry-suse** [comment]
Will likely need to replace the logic in request finder, but need to nail down why submits work.

**Comment by DimStar77** [comment]
> 7 days ago: https://build.opensuse.org/request/show/687276

Yes, but as such a special case, I did not care to report it as an issue - I simply accepted it after manually doing some checks.

Delete requests in NonFree are really not a common thing - if a fix is easy, well, why not.. 

for regular submit requests, we have special code, adding them to the adi (no nonfree can ever be in the ring, so the adi path is sufficient)

**Comment by jberry-suse** [comment]
As such do we want to handle NonFree deletes the same as normal deletes and stage them in a letter staging or not bother?

**Comment by coolo** [comment]
IMO it would be ok if staging-bot simply left them in backlog

**Comment by jberry-suse** [comment]
> for regular submit requests, we have special code, adding them to the adi (no nonfree can ever be in the ring, so the adi path is sufficient)

I am curious how it gets that far, as selecting a submit for NonFree produces the same error as reading the code would suggest.

```
osc staging select D 687890
Request 687890 is not for openSUSE:Factory, but for openSUSE:Factory:NonFree
```

**Comment by jberry-suse** [comment]
I suppose the `adi` command gets to them first.

**Comment by jberry-suse** [comment]
Created a PR to completed ignore NonFree requests in proposal generation. Submits should still be picked up by `adi`.

https://github.com/openSUSE/openSUSE-release-tools/blob/f449f810d806194da7f77f4b645e0eb5826a5de3/systemd/osrt-staging-bot-regular%40.service#L10-L11
