### ISSUE TITLE
freeze: rename to rebase

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1947]
the name of the freeze command is rather unintuitive. It should be rename to rebased to better reflect common naming practice.

**Comment by lkocman** [comment]
Ack, I was also initially confused by the feature functionality. Please keep the freeze for compat reasons as well.

**Comment by ancorgs** [comment]
Isn't this solved by #2584?

**Comment by coolo** [comment]
I guess the openSUSE prefix broke the auto close
