### ISSUE TITLE
origin-manager: consider supporting non-groups in additional_reviews config

### ISSUE THREAD

**Issue by nilxam** [openSUSE/openSUSE-release-tools#1949]
origin-manager got crashed when through https://build.opensuse.org/request/show/692138 and https://build.opensuse.org/request/show/692214 , attached the log from 692138

Don't know why these two requests are special for origin-manager though.

<pre>

Apr 09 09:11:57 packagelists osrt-origin-manager[352]: [I] checking 692138
Apr 09 09:11:57 packagelists osrt-origin-manager[352]: [D] origin_find: openSUSE:Leap:15.1/kwin5 with source 45e0ec6 (False, True, True)
Apr 09 09:11:57 packagelists osrt-origin-manager[352]: [D] source_contain: KDE:Frameworks5:LTS:5.12                 45e0ec6 == 45e0ec6 (match)
Apr 09 09:11:57 packagelists osrt-origin-manager[352]: [D] origin_find: openSUSE:Leap:15.1/kwin5 with source 88672b5 (True, True, True)
Apr 09 09:11:57 packagelists osrt-origin-manager[352]: [D] source_contain: KDE:Frameworks5:LTS:5.12                 45e0ec6 == 88672b5
Apr 09 09:11:57 packagelists osrt-origin-manager[352]: [D] source_contain: KDE:Frameworks5:LTS:5.12                 88672b5 == 88672b5 (match)
Apr 09 09:11:58 packagelists osrt-origin-manager[352]: [D] policy_evaluate:
Apr 09 09:11:58 packagelists osrt-origin-manager[352]: # policy
Apr 09 09:11:58 packagelists osrt-origin-manager[352]: additional_reviews:
Apr 09 09:11:58 packagelists osrt-origin-manager[352]: - leaper
Apr 09 09:11:58 packagelists osrt-origin-manager[352]: - opensuse-review-team
Apr 09 09:11:58 packagelists osrt-origin-manager[352]: - legal-auto
Apr 09 09:11:58 packagelists osrt-origin-manager[352]: automatic_updates: true
Apr 09 09:11:58 packagelists osrt-origin-manager[352]: maintainer_review_always: false
Apr 09 09:11:58 packagelists osrt-origin-manager[352]: maintainer_review_initial: true
Apr 09 09:11:58 packagelists osrt-origin-manager[352]: pending_submission_allow: false
Apr 09 09:11:58 packagelists osrt-origin-manager[352]: pending_submission_allowed_reviews: []
Apr 09 09:11:58 packagelists osrt-origin-manager[352]: pending_submission_consider: false
Apr 09 09:11:58 packagelists osrt-origin-manager[352]: # inputs
Apr 09 09:11:58 packagelists osrt-origin-manager[352]: direction: forward
Apr 09 09:11:58 packagelists osrt-origin-manager[352]: higher_priority: null
Apr 09 09:11:58 packagelists osrt-origin-manager[352]: new_package: false
Apr 09 09:11:58 packagelists osrt-origin-manager[352]: origin_change: false
Apr 09 09:11:58 packagelists osrt-origin-manager[352]: pending_submission: 'False'
Apr 09 09:11:58 packagelists osrt-origin-manager[352]: same_family: true
Apr 09 09:11:58 packagelists osrt-origin-manager[352]: PolicyResult(wait=False, accept=True, reviews={'leaper': 'Additional review required based on origin.', 'legal-auto':>
Apr 09 09:11:59 packagelists osrt-origin-manager[352]: Traceback (most recent call last):
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:   File "/usr/share/openSUSE-release-tools/ReviewBot.py", line 183, in check_requests
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:     good = self.check_one_request(req)
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:   File "/usr/share/openSUSE-release-tools/ReviewBot.py", line 375, in check_one_request
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:     ret = func(req, a)
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:   File "/usr/share/openSUSE-release-tools/ReviewBot.py", line 456, in check_action_submit
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:     return self.check_source_submission(a.src_project, a.src_package, a.src_rev, a.tgt_project, a.tgt_package)
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:   File "/usr/bin/osrt-origin-manager", line 42, in check_source_submission
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:     return self.policy_result_handle(tgt_project, tgt_package, origin_info_new, origin_info_old, result)
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:   File "/usr/bin/osrt-origin-manager", line 60, in policy_result_handle
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:     self.policy_result_reviews_add(project, package, result.reviews, origin_info_new, origin_info_old)
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:   File "/usr/bin/osrt-origin-manager", line 87, in policy_result_reviews_add
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:     self.add_review(self.request, by_group=key, msg=comment)
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:   File "/usr/share/openSUSE-release-tools/ReviewBot.py", line 307, in add_review
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:     r = osc.core.http_POST(u, data=msg)
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:   File "/usr/lib/python2.7/site-packages/osc/core.py", line 3375, in http_POST
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:     def http_POST(*args, **kwargs):   return http_request('POST', *args, **kwargs)
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:   File "/usr/share/openSUSE-release-tools/osclib/cache.py", line 51, in http_request
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:     ret = osc.core._http_request(method, url, headers, data, file)
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:   File "/usr/lib/python2.7/site-packages/osc/core.py", line 3363, in http_request
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:     fd = urlopen(req, data=data)
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:   File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:     return opener.open(url, data, timeout)
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:   File "/usr/lib64/python2.7/urllib2.py", line 435, in open
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:     response = meth(req, response)
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:   File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:     'http', request, response, code, msg, hdrs)
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:   File "/usr/lib64/python2.7/urllib2.py", line 473, in error
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:     return self._call_chain(*args)
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:   File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:     result = func(*args)
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:   File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default
Apr 09 09:11:59 packagelists osrt-origin-manager[352]:     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
Apr 09 09:11:59 packagelists osrt-origin-manager[352]: HTTPError: HTTP Error 400: Bad Request
Apr 09 09:11:59 packagelists osrt-origin-manager[352]: [I] 692138 ignored

</pre>

**Comment by nilxam** [comment]
@jberry-suse can you have a look?

**Comment by coolo** [comment]
It tries to add by_group=leaper, but leaper is a user not a group.

**Comment by lnussel** [comment]
would it be possible to also support users?

**Comment by lnussel** [comment]
(atm leaper is just a workaround though to get more information until origin-manger has UI)

**Comment by jberry-suse** [comment]
To clarify, someone (presumably lnussel) added `leaper` to additional_reviews portion of config and as coolo noted those are expected to be groups. As it has been removed, everything should go back to normal.

Since the motivation was workaround for lack of UI I am not sure it's worth supporting non-group reviews there.
