### ISSUE TITLE
installcheck: installcheck confused with package update if it has so_ver in the RPM name

### ISSUE THREAD

**Issue by nilxam** [openSUSE/openSUSE-release-tools#1964]
With https://build.opensuse.org/request/show/694761 libqscintilla2_qt5-13 -> libqscintilla2_qt5-15, installcheck still sees the file conflict with libqscintilla2_qt5-13, although the conflict issue should be fixed in the SR.

<pre>
found conflict of libqscintilla2_qt5-13-2.10.8-2.5.x86_64 with qscintilla2_qt5-2.11.1-40.1.x86_64:
  - /usr/share/qt5/qsci/api/python/Python-2.4.api
  - /usr/share/qt5/qsci/api/python/Python-2.5.api
  - /usr/share/qt5/qsci/api/python/Python-2.6.api
  - /usr/share/qt5/qsci/api/python/Python-2.7.api
  - /usr/share/qt5/qsci/api/python/Python-3.1.api
  - /usr/share/qt5/qsci/api/python/Python-3.2.api
  - /usr/share/qt5/qsci/api/python/Python-3.3.api
  - /usr/share/qt5/qsci/api/python/Python-3.4.api
  - /usr/share/qt5/qsci/api/python/Python-3.5.api
  - /usr/share/qt5/qsci/api/python/Python-3.6.api
  - /usr/share/qt5/qsci/api/python/Python-3.7.api
  - /usr/share/qt5/translations/qscintilla_cs.qm
  - /usr/share/qt5/translations/qscintilla_de.qm
  - /usr/share/qt5/translations/qscintilla_es.qm
  - /usr/share/qt5/translations/qscintilla_fr.qm
  - /usr/share/qt5/translations/qscintilla_pt_br.qm
</pre>

**Comment by nilxam** [comment]
BTW I commented `installcheck: ignore libqscintilla2_qt5-13 qscintilla2_qt5` seems not working, also tried `installcheck: ignore qscintilla-qt5 libqscintilla2_qt5-13 qscintilla2_qt5` not working too.

**Comment by coolo** [comment]
how did you solve this in the end?

**Comment by nilxam** [comment]
I didn't. The ignoring somehow works 2 days later.

**Comment by coolo** [comment]
this is a little hard to figure out now
