### ISSUE TITLE
changelog-checker, reject submission if we loose bug, fate or JIRA reference

### ISSUE THREAD

**Issue by lkocman** [openSUSE/openSUSE-release-tools#1991]
As a Release Manager, I have to spend a lot of time on the submission (fixing dependency issues via _product changes, grouping on staging) before we figure out that changelog lost a bug or fate reference.

Autobuild prefers to reject these anyway, so I believe it's safe to have such rule in place

**Comment by coolo** [comment]
dfd98dab304cddf1bf7cb04c3cd98228bcadbe1f (as part of https://github.com/openSUSE/openSUSE-release-tools/pull/679) added a warning in the accept string, but that's obviously lost in space. 

The problem is, I can't find any such warning in the IBS database - so I wonder if it works at all.

**Comment by darix** [comment]
i am all for automating checks that can be automated.

**Comment by lethliel** [comment]
I am too for automating the checks. Is there a command to overwrite those automated checks?

**Comment by jberry-suse** [comment]
Overrideable using ReviewBot override feature I added. In this case the class is `TagChecker` so the osc config key is `tagchecker-override-group` which can be set to whatever group should be able to override using `@<bot-obs-username> override`.
