### ISSUE TITLE
missing dependency on python3-lxml, python3-pyxdg

### ISSUE THREAD

**Issue by lethliel** [openSUSE/openSUSE-release-tools#2028]
This was reported https://bugzilla.opensuse.org/show_bug.cgi?id=1126841

rpm -qa | grep osc
osc-plugin-cycle-20181127.edba5dc-bp151.1.5.noarch
osc-0.164.2-2.1.noarch
osc-plugin-staging-20181127.edba5dc-bp151.1.5.noarch
osc-plugin-check_dups-20181127.edba5dc-bp151.1.5.noarch
osc-plugin-install-0.25-bp151.2.6.noarch
osclib-20181127.edba5dc-bp151.1.5.noarch
osc-plugin-vdelreq-20181127.edba5dc-bp151.1.5.noarch

user@linux-zrtn:~/Workspace/ibs/home:lkocman:branches:SUSE:SLE-15-SP1:GA/000package-groups> iosc diff
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 9203, in _load_plugins
    mod = imp.load_source(modname, os.path.join(plugin_dir, extfile))
  File "/usr/lib64/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/osc-plugins/osc-staging.py", line 20, in <module>
    from osclib.accept_command import AcceptCommand
  File "/usr/lib/osc-plugins/osclib/accept_command.py", line 16, in <module>
    from osclib.core import source_file_load
  File "/usr/lib/osc-plugins/osclib/core.py", line 7, in <module>
    from lxml import etree as ETL
ModuleNotFoundError: No module named 'lxml'

/usr/lib/osc-plugins/osc-staging.py: No module named 'lxml'

 Try 'env OSC_PLUGIN_FAIL_IGNORE=1 osc ...'

**Comment by lethliel** [comment]
originally reported by @lkocman

**Comment by coolo** [comment]
the report is for the package in packagehub

**Comment by jberry-suse** [comment]
[Current package](https://build.opensuse.org/package/dependency/openSUSE:Tools/openSUSE-release-tools?arch=x86_64&dependant_name=openSUSE-release-tools&dependant_project=openSUSE%3ATools&dependant_repository=openSUSE_Factory&filename=osclib-20190515.33b36945-1.1.noarch.rpm&repository=openSUSE_Factory) was fixed as of #1979.

**Comment by jberry-suse** [comment]
![image](https://user-images.githubusercontent.com/22943929/57818635-5347a400-774a-11e9-9f0c-a111ac38b28a.png)

**Comment by coolo** [comment]
yeah, right. Because openSUSE:Tools is obviously the packagehub

**Comment by jberry-suse** [comment]
obviously indeed. wasn't aware we pushed to packagehub and as such it was fixed in upstream. like closing the bug in firefox before openSUSE releases the fixed binaries...

**Comment by coolo** [comment]
Filed #707212 for openSUSE 15.1 maintenance - packagehub is mirrored from there
