### ISSUE TITLE
Testing staging command with current osc[py3}

### ISSUE THREAD

**Issue by nilxam** [openSUSE/openSUSE-release-tools#2037]
- [x] staging accept
- [x] staging acheck
- [x] staging adi --mocde
- [x] staging check_duplicate_binaries
- [x] staging config
- [x] staging config --clear
- [x] staging freeze
- [x] staging frozenage
- [x] staging ignore/unignore
- [x] staging list
- [x] staging lock/unlock
- [x] staging repair
- [x] staging setprio
- [x] staging select --move
- [x] staging unselect

- [x] osc check_dups openSUSE:Factory

**Comment by nilxam** [comment]
Not sure any usage was missing on this list. The basic behavior should works with *future released* osc.

**Comment by jberry-suse** [comment]
:)

**Comment by coolo** [comment]
I build the deployed containers now against https://build.opensuse.org/package/show/home:coolo:updatedosc/osc - but I don't have a rush, so the staging-bot still runs on the mid of april TW container ;)

**Comment by jberry-suse** [comment]
since there is nothing osrt needs in newer osc releases I build operator container against pre-switch release

**Comment by nilxam** [comment]
Found an issue in staging accept for TW, fixed by https://github.com/openSUSE/openSUSE-release-tools/pull/2054

**Comment by nilxam** [comment]
alright, another one in the accept command https://github.com/openSUSE/openSUSE-release-tools/pull/2067

**Comment by coolo** [comment]
one week passed without further bad news - so let's say it's good
