### ISSUE TITLE
factory-auto died during gocd transition

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#2088]
Example seen in [request 706542](https://build.opensuse.org/request/show/706542).

```
Output of check script: 
Can't locate XML/Simple.pm in @INC (you may need to install the XML::Simple module) (@INC contains: /usr/lib/perl5/site_perl/5.28.1/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.28.1 /usr/lib/perl5/vendor_perl/5.28.1/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.28.1 /usr/lib/perl5/5.28.1/x86_64-linux-thread-multi /usr/lib/perl5/5.28.1 /usr/lib/perl5/site_perl) at /godata/pipelines/openSUSE.Source.Check/check_source.pl line 5. 
BEGIN failed--compilation aborted at /godata/pipelines/openSUSE.Source.Check/check_source.pl line 5.
```

**Comment by jberry-suse** [comment]
Not sure why the existing packaging cannot be used to ensure dependencies are happy.

**Comment by coolo** [comment]
Because I want to make sure that merging PRs is all you have to do to fix an issue.

**Comment by jberry-suse** [comment]
The certainly works with either approach.

**Comment by jberry-suse** [comment]
The same way a tool can run `git pull` it can run `zypper up`.

**Comment by coolo** [comment]
but you can't have branches with zypper up that easily

**Comment by coolo** [comment]
the dependencies are listed here and it's not rebuilding on git changes, but perhaps it should:
https://build.opensuse.org/package/view_file/openSUSE:Tools:Images/gocd-agent-release-tools/Dockerfile?expand=1

So far I found tracking depencies outside of git creating less of a chicken/egg problem

**Comment by jberry-suse** [comment]
Should need branches in production, but that's another can of worms.
