### ISSUE TITLE
Trigger.Rebuild service has insufficient permission

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/openSUSE-release-tools#2103]
From https://botmaster.suse.de/go/tab/build/detail/Trigger.Rebuilds/72/Run/1/Run

```
rebuild glib2-branding:openSUSE: nothing provides libgio-2_0-0 = 2.60.2 needed by gio-branding-openSUSE
API '/build/openSUSE:Factory?cmd=rebuild&repository=standard&arch=i586&package=glib2-branding%3AopenSUSE'
Server returned an error: HTTP Error 403: Forbidden
No permission to execute command on package glib2-branding:openSUSE in project openSUSE:Factory
```

The bot correctly wanted to trigger a buildof glib2-branding:openSUSE, but failed to do so. As a consequence, the pkglist gen opted to add upstream branding on the DVD (the *-openSUSE is uninstallable), which in turn results in 'broken' brading in openQA: https://openqa.opensuse.org/tests/948019#step/first_boot/12 (and QA is colorblind, so 'accepted' it at this stage

**Comment by DimStar77** [comment]
(as a workaround, I triggered that package manually, but without the bot we will run into dozens of broken snapshots due to such things)

**Comment by coolo** [comment]
now that's a consequence of https://github.com/openSUSE/openSUSE-release-tools/issues/1043#issuecomment-498197941
