### ISSUE TITLE
can't install userscript with greasemonkey

### ISSUE THREAD

**Issue by fcrozat** [openSUSE/openSUSE-release-tools#2123]
When trying to install userscripts on FF with GreaseMonkey, I get the following error:

Ignore pattern @match */package/show/* because Error: @match: Could not parse the pattern: */package/show/*

**Comment by jberry-suse** [comment]
For a couple of reasons I abandoned trying to support GreaseMonkey as well. As such the instructions recommend using Tampermonkey. If someone wants to make it work in both PRs welcome. Otherwise, it is easier to support one userscript "platform" (ie. Tampermonkey).
