### ISSUE TITLE
ISO changelog extracter creates empty files

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/openSUSE-release-tools#2128]
The changelog extractor, which is used to produce the announcement mails to openSUSE-Factory,produces empty files, i.e.

```
-rw-r--r-- 1 geekotest    nogroup 5332445 Jul  9 02:30 20190708
-rw-r--r-- 1 geekotest    nogroup      26 Jul 10 23:07 20190709
-rw-r--r-- 1 geekotest    nogroup      26 Jul 11 20:13 20190711
-rw-r--r-- 1 geekotest    nogroup      26 Jul 15 15:11 20190713
```

**Comment by DimStar77** [comment]
This is potentially a fallout from the upgrade of ariel to Leap 15.1:

```
2019-07-09 19:31:10|command|root@ariel|'zypper' '-n' '--releasever=15.1' 'dup' '--auto-agree-with-licenses' '--replacefiles' '--download-in-advance'|
2019-07-09 19:31:11|remove |ruby2.1-rubygem-json_pure|1.8.2-6.3|x86_64||
```
CC @okurz

**Comment by DimStar77** [comment]
e.g.

```
/opt/openqa-scripts/factory-package-news.py save --dir /var/lib/snapshot-changes/microos/Tumbleweed/ --snapshot 20190613 /var/lib/openqa/factory/iso/openSUSE-MicroOS-DVD-x86_64-Snapshot20190713-Media.iso 
++ WARN: from_733: broken byte order
++ WARN: Bad directory information for suse
++ WARN: from_733: broken byte order
++ WARN: Bad directory information for suse
++ WARN: from_733: broken byte order
++ WARN: Bad directory information for x86_64
++ WARN: from_733: broken byte order
++ WARN: Bad directory information for noarch
```

**Comment by DimStar77** [comment]
from_733: broken byte order is a message from libcdio

**Comment by DimStar77** [comment]
https://bugzilla.opensuse.org/show_bug.cgi?id=1094761 - lovely

**Comment by coolo** [comment]
the warning have been there since about forever. I don't think they are your problem.

**Comment by DimStar77** [comment]
http://git.savannah.gnu.org/cgit/libcdio.git/commit/?id=8be41a36b8792b7d99fc8383a6c426d8b63ec6a8 - new in libcdio 0.94 - which came with Leap 15.0 - 42.3 was at libcdio 0.93

**Comment by DimStar77** [comment]
I backported two patches from libcdio 2.1 to the Leap 15.1 provided libcdio 0.94.
The patched version of libcdio is currently installed on ariel - and the changelog extractor is functional again (diff of 0713->0716 https://openqa.opensuse.org/factory-package-news/diff/20190716)

In parallel, I submitted my fixed version of libcdio into the SLE15 maintenance process

As such, I think we can safely close this issue: nothing needed be done in the releng tooling, the bug was introduced by upgrading to Leap 15.1 (well, not really - the bug is ultimately in the product builder)
