### ISSUE TITLE
origin-manager: find workaround or propose OBS behavior change to avoid source reviews

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#2146]
Currently, if pending sources are submitted out of a maintenance incident or devel project the source project is added as a reviewer automatically by OBS, but this is not desirable. Given one can `copypac` and submit from their home project to avoid this the behavior does not protect anything. My preference would be dropping the behavior or an attribute on target project to avoid it. Really the target project should matter based on their policies (as our tools implement), not the source project. Until this is resolved #1048 cannot be utilized from #2145.

**Comment by jberry-suse** [comment]
This is also [occurring on submission from SLE-15-SP2](https://build.opensuse.org/request/show/722655).

```xml
  <review state="accepted" when="2019-08-12T11:33:22" who="namtrac" by_package="libstorage-ng" by_project="SUSE:SLE-15-SP2:GA">
    <comment>ok</comment>
    <history who="namtrac" when="2019-08-12T15:59:48">
      <description>Review got accepted</description>
      <comment>ok</comment>
    </history>
  </review>
```

**Comment by jberry-suse** [comment]
As I wrote in the OBS feature request, we could workaround this by copy sources to a temporary project (perhaps origin-manager home project) for submission.

**Comment by coolo** [comment]
blocked by OBS feature

**Comment by coolo** [comment]
Taking that origin manager submissions are hardly relevant atm due to Jump, it's sub-P4. I close in favor of seeing the light in the jungle
