### ISSUE TITLE
origin.user.js: fail doesn't trigger

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#2152]
GET 
XHR 
https://operator.opensuse.org/origin/package/openSUSE:Leap:15.2/python-Django 
[HTTP/2.0 502 Bad Gateway 33ms]

yet, the fail callback doesn't seem to trigger

**Comment by jberry-suse** [comment]
Also good to determine why the request is failing server side, but [difficulty access deployment again](https://progress.opensuse.org/issues/54977).
