### ISSUE TITLE
origin-manager: provide update frequency control (or ignore altogether)

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#2182]
Provide a method, likely an OBS attribute, of controlling the frequency of update submissions. This will primarily be useful for Factory which tracks many packages updated by CI, but is also useful for Leap. Along with this provide a configurable project level default.

Along with a time based frequency should be the ability to never create a request when an open one exists for the package.

Finally, a complete ignore option to halt updates.

**Comment by jberry-suse** [comment]
The ignore portion is related to #942.

**Comment by jberry-suse** [comment]
Perhaps a flag as part of decline message (or comment on request) to automatically add the ignore attribute and could also highlight the frequency in web interface and allow changing there.

**Comment by jberry-suse** [comment]
Requested in https://build.opensuse.org/request/show/733094.

**Comment by jberry-suse** [comment]
- requested for yast packages in SLE-15-SP2.
- inquired about after [Virtualization:containers:images:openSUSE-Leap-15.2 / opensuse-leap-image](https://build.opensuse.org/request/show/742145)

**Comment by jberry-suse** [comment]
@Vogtinator, @gyr: Since you asked for this, notifying you of pending PR and new defaults for openSUSE side. Feel free to add the appropriate config or override attributes once merged.

**Comment by Vogtinator** [comment]
Thanks! The default 1h delay sounds good to me.
