### ISSUE TITLE
origin-manager: allow for new devel projects to be approved by review

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#2183]
Ideally this will also whitelist concurrent pending submissions from the same new devel project the same way the existing whitelist works utilized by factory-auto, but could end up just using the whitelist as a migration path.

Likely related, change_devel requests should simulate an origin_find() with the change in effect and trigger reviews based on that.

**Comment by jberry-suse** [comment]
Had [another case](https://build.opensuse.org/request/show/728221) where this would be useful (much more common for Factory obviously).

**Comment by jberry-suse** [comment]
Should also trigger the normal evaluation of policy after the devel project is specified (like adding additional reviews).

Another example: https://build.opensuse.org/request/show/731928

**Comment by lnussel** [comment]
lack of reviews is critical IMO. prio needs to be raised. we miss review-team and legal for that.

**Comment by jberry-suse** [comment]
@lnussel What would you like the workflow to look like?

I see two main options:

1) standard wait process when new package not found from any origin and require a command command to process as devel (defaults to source project and package)
2) automatically fallback to acting as if source project and package are the devel (which will add necessary reviews at this point)

The first option would essentially trigger the second instead of it being automatic. If the second option an origin-manager review could be added to "approve coming from devel". Currently, no review is added for new packages coming from the highest available origin.

Related would be the Factory flow, I would expect it to always fallback (option 2) and add origin-reviewers to approve first time devel project.

**Comment by coolo** [comment]
> lack of reviews is critical IMO. prio needs to be raised. we miss review-team and legal for that.

BTW: licensedigger is reviewer in 15.2, so you don't miss it

**Comment by jberry-suse** [comment]
I ran into a lot of issues:

- test setup
  - pre-existing failures and assumptions that were intentionally hidden
  - OBS caching problems
  - odd mix of unnecessary custom data handling in harness that needs to be mixed with external script calls
  - tool cache layer assumptions broken by test workflow
- origin-manager change_devel workflow
  - multi-policy handling for old and new origin overly complicated and not worth since majority case should be identical devel policies

As expected there were also a few small fixups exposed by the testing which makes it worth it. Currently, one of the main workflows covered with the second one mostly done, and the third should share a lot of code from other two. Also cover a variety of smaller workflows with tests. Hopefully now that major nuisances are resolved should be able to knock out remaining 1.5 worklows and have confidence old workflows remain function and new ones work.
