### ISSUE TITLE
origin-manager: summary of packages by type and origin along with filter links

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#2185]
Similar to the origin plugin report functionality, having a simple table (and perhaps pie chart) showing the breakdown of packages by origin and state would be useful. Things such as:

- workarounds
- ahead of origin
- behind origin

**Comment by lnussel** [comment]
Justification is to provide data to management to come up with actual facts for claims like Leap isn't compatible with SLE as currently seen in internal mailinglist discussions

**Comment by jberry-suse** [comment]
Want to include summary of packages contained by an origin, but not tracked from there and possibly differentiate between ones that never had matching revisions vs those that did (likely just workarounds then).

**Comment by coolo** [comment]
> Justification is to provide data to management to come up with actual facts for claims like Leap isn't compatible with SLE as currently seen in internal mailinglist discussions

If you believe that you can change feelings with facts, you obviously don't follow the news :(
