### ISSUE TITLE
obs_operator: provide delegation feature for more granular permissions

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#2189]
As was one of the original goals, the operator server could be extended to delegate calls to be upgraded to run as a more privileged user. This would allow something like devel project maintainers the ability to run `osc staging select` on their packages or similar. Related to #2169 as it would need pre-configured credentials to use for delegation and would require restriction of methods.

**Comment by coolo** [comment]
At this point we have no resources to continue the operator
