### ISSUE TITLE
obs_operator: provide command passthru facility

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#2190]
Would allow for running any osrt based command on operator server. Could be a configuration option or flag to wrap osrt based osc plugins and call the operator. This could provide a significant performance increase for remote users as the operator sits closer to OBS. Additionally, when combined with #2189 could allow for the some powerful use-cases.

**Comment by coolo** [comment]
At this point we have no resources to continue the operator
