### ISSUE TITLE
Bug "pcp2csv or pmrep command not found" catched at the  xcdchk level?

### ISSUE THREAD

**Issue by marita22** [openSUSE/openSUSE-release-tools#2217]
Could that bug "SUSE1127978- SLES 15 SP1 Beta4 - pcp: pcp2csv or pmrep command not found", found by IBM
be catched at the  xcdchk level (or maybe at installcheck)?

**Comment by coolo** [comment]
Possibly, but not feasible.

We can potentially check that symlink targets are required, but it would create tons of false positives I'm sure we would have to whitelist again.

But even if we ignored that, the bug actually turned into it: it's still not starting if installing the requires. So in the end it's still safer to install every rpm we have into a container, and execute every binary of it. This way you identify *all* problems of missing or broken dependencies and not just a theoretical subset.

**Comment by marita22** [comment]
Ok, thanks a lot. I will let IBM know.
