### ISSUE TITLE
origin-manager: add hint that it is waiting for override when unknown_origin_wait is true

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#2228]
When origin manager goes into wait state it doesn't tell that, nor how to make it proceed. Some hint about the options would be helpful:
https://build.opensuse.org/request/show/731520

**Comment by jberry-suse** [comment]
Was not waiting so much as we never configured to override group so it never saw your comment as valid. I added the following to 15.2 OSRT:Config:

```
originmanager-override-group = origin-reviewers
```

When waiting on reviews it indicates that so this message could use some extra detail. I also never designed us to use the None override like this as this should really be #2183.

**Comment by jberry-suse** [comment]
Likely also make sense to default override-group to match that of fallback-group in OSRT:OriginConfig.
