### ISSUE TITLE
improve Documentation

### ISSUE THREAD

**Issue by dsamx** [openSUSE/openSUSE-release-tools#2236]
Documentation and code comments are minimal/non-existant.
Please document which tools there are, how to use them and how OBS/openQA/... have to be configured for common tasks.

**Comment by ancorgs** [comment]
These pull requests can be considered first steps to fix the situation:

- https://github.com/openSUSE/openSUSE-release-tools/pull/2604
- https://github.com/openSUSE/openSUSE-release-tools/pull/2606

These ones are not exactly the same, but kind of related:

- https://github.com/openSUSE/openSUSE-release-tools/pull/2588
- https://github.com/openSUSE/openSUSE-release-tools/pull/2605

**Comment by coolo** [comment]
I find the PRs fullfill the request.
