### ISSUE TITLE
origin-manager: synced SLE sources do not generate events

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#2239]
Based on watching the requests generated by the OBS listener and reviewing the logs the only time an update request from SLE is generated is when the back is update in Leap:15.1:Update or similar which triggers an update check which notices the SLE sources were changed. The logs I reviewed never contain an update message for a SLE package even when the revision history on OBS shows they were updated within the timespan covered by the logs.

Presumably, there is nothing on our that can be done about this short of reverting back to running the full crawler more often which I think should be done until OBS properly generates events. I am assuming the lack of events is due to some sort of hack used to create the sync since commits from IBS appear on OBS which is not possible with standard osc tooling. Another thing that would work out-of-the-box with git (pushing entire tree).

**Comment by jberry-suse** [comment]
A random example:

```
<MainThread> [I] Received message # 2213: opensuse.obs.package.update b'{"project":"openSUSE:Factory","package":"expat","sender":"dimstar_suse"}'
<MainThread> [I] checking for updates to openSUSE:Leap:15.2/expat...
submit SUSE:SLE-15-SP2:GA/expat -> openSUSE:Leap:15.2/expat = 732647
```

**Comment by jberry-suse** [comment]
I started [thread on opensuse-buildservice mailing list](https://lists.opensuse.org/opensuse-buildservice/2019-09/msg00112.html).

**Comment by coolo** [comment]
replied there, but for completion: you listen for the wrong event
