### ISSUE TITLE
Eliminate Delete Request complexity

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/openSUSE-release-tools#2251]
A while back we introduced the concept of 'virtual del req' handling - meaning we only really deleted a package once a snapshot was published with the binaries removed. This was done to avid delete requests having immediate averse impacts on users that were building against openSUSE:Factory/snapshot

OBS has since evolved and more features became available - in this case Download on Demand.

So far, the setup was:

openSUSE:Tumbleweed/standard had path=openSUSE:Factory/snapshot

openSUSE:Factory/snapshot was filled by an admin task by copying rpms from openSUSE:Factory/totest (at the publish event) and /totest was copied from /standard (when a snapshot moved to QA)

With DoD fully supported, the new setup will be:

openSUSE:Tumbleweed/standard is setup as a DoD project - fetching RPMs from download.opensuse.org
openSUSE:Factory/snapshot will be changed to have path=openSUSE:Tumbleweed/standard - so the OBS users won't actually see a difference / no need to change their setup

The only 'side effect' seen so far is that devel projects building against /snapshot won't use the -mini packages in this case - but that's not really an issue imho

**Comment by Vogtinator** [comment]
When will this be deployed?

This way it's also possible to copy the prjconf properly, so that it always matches the available packages.

**Comment by DimStar77** [comment]
openSUSE:Tumbleweed/standard is already setup as DoD - and is currently decoupled from openSUSE:Factory/snapshot (making baby steps - allowing to verify that results between the old and new way stay aligned)

**Comment by coolo** [comment]
Fixed in #2268
