### ISSUE TITLE
pkglistgen: invalid DVD content is being generated

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/openSUSE-release-tools#2284]
This issue is based on findings in Staging:H

the package salt has a

 ```
Requires: python3-tornado >= 4.5.1
conflicts: python-tornado >= 5
```

Staging:H contains a meta package python3-tornado (pointing to 6.x) and the tree actual tornado packages, python3-tornado[456], all providing python3-tornado = %{version} capability

pkglistgen is not takingn the conflict into account (correctly): it adds salt to the DVD together with python3-tornado6

This results in salt being uninstallable from the Staging DVD, and thus blocking Staging:H

**Comment by coolo** [comment]
consequence of 8351d2e677eecc4846f00ba674d401a5b8b5ff87
