### ISSUE TITLE
origin-manager submitted same package twice

### ISSUE THREAD

**Issue by nilxam** [openSUSE/openSUSE-release-tools#2288]
just put what monitor sees:

`
<MainThread> [I] Received message # 558: opensuse.obs.request.create b'{"author":"origin-manager","description":"Newer source available from package origin. (host go-agent-stagingbot-5)","number":745365,"actions":[{"action_id":1667708,"type":"submit","sourceproject":"SUSE:SLE-15-SP2:GA","sourcepackage":"python-ecdsa","sourcerevision":"1","targetproject":"openSUSE:Leap:15.2","targetpackage":"python-ecdsa"}],"state":"review","when":"2019-11-05T09:12:38","who":"origin-manager"}'
<MainThread> [I] skipped irrelevant origin: openSUSE:Leap:15.2
<MainThread> [I] Received message # 559: opensuse.obs.request.create b'{"author":"origin-manager","description":"Newer source available from package origin. (host go-agent-stagingbot-3)","number":745366,"actions":[{"action_id":1667711,"type":"submit","sourceproject":"SUSE:SLE-15-SP2:GA","sourcepackage":"python-ecdsa","sourcerevision":"1","targetproject":"openSUSE:Leap:15.2","targetpackage":"python-ecdsa"}],"state":"review","when":"2019-11-05T09:12:39","who":"origin-manager"}'
`

`
<MainThread> [I] Received message # 35: opensuse.obs.request.create b'{"author":"origin-manager","description":"Newer source available from package origin. (host go-agent-stagingbot-5)","number":745327,"actions":[{"action_id":1667594,"type":"submit","sourceproject":"SUSE:SLE-15-SP2:GA","sourcepackage":"libcontainers-common","sourcerevision":"2","targetproject":"openSUSE:Leap:15.2","targetpackage":"libcontainers-common"}],"state":"review","when":"2019-11-05T07:37:52","who":"origin-manager"}'
<MainThread> [I] skipped irrelevant origin: openSUSE:Leap:15.2
<MainThread> [I] Received message # 36: opensuse.obs.request.create b'{"author":"origin-manager","description":"Newer source available from package origin. (host go-agent-stagingbot-3)","number":745328,"actions":[{"action_id":1667597,"type":"submit","sourceproject":"SUSE:SLE-15-SP2:GA","sourcepackage":"libcontainers-common","sourcerevision":"2","targetproject":"openSUSE:Leap:15.2","targetpackage":"libcontainers-common"}],"state":"review","when":"2019-11-05T07:37:53","who":"origin-manager"}'
`

**Comment by nilxam** [comment]
one is from https://botmaster.suse.de/go/tab/build/detail/S15.SP2.Origin.Manager.Update/17/Run/1/Run , that looks messed up, it was checking Leap 15.2 rather than SLE15 SP2, thus it does dup'ed job with OS.Origin.Manager.Update

**Comment by jberry-suse** [comment]
Looks like just the last run (ie today). Unless something change in the `oscrc` for gocd I see nothing that should have caused that.

**Comment by jberry-suse** [comment]
One can see the command:

https://github.com/openSUSE/openSUSE-release-tools/blob/9f80ea19b0eed6cd2b6578976e4c60247f46cbc7/gocd/checkers.suse.gocd.yaml.erb#L89-L112

specifically,

```
osc -A https://api.suse.de origin update
```

**Comment by jberry-suse** [comment]
My local client does the same thing, apiurl is obs instead of ibs even when I pass it in. I have no updated my local osc or anything.

EDIT: could only reproduce once, very odd

**Comment by jberry-suse** [comment]
The monitor needs to be restarted to benefit from the fix.
