### ISSUE TITLE
origin-manager: submitted multispec_subpackage

### ISSUE THREAD

**Issue by nilxam** [openSUSE/openSUSE-release-tools#2293]
Not sure it's intentional but I don't see origin-manager submitted them before. eg.

https://build.opensuse.org/request/show/745742

**Comment by jberry-suse** [comment]
Figured this might happen with #2287. Presumably `package_kind()` returns source in origin project. That whole mess of figuring which are real packages could really use a proper API from OBS, but so could so much else.

**Comment by jberry-suse** [comment]
The code in question should be:

https://github.com/openSUSE/openSUSE-release-tools/blob/9f80ea19b0eed6cd2b6578976e4c60247f46cbc7/osc-origin.py#L375-L383

So either `origin_update()` needs to double check if actually source in target, or the fitlering there needs to be more sophisticated. Additionally, given the rejection of kernel live updates and such (make sense) likely want a pattern blacklist for new package submission that could be applied there. Those packages should not be re-submitted since they were declined, but future kernel live updates would rather be avoided. Unless there is some marking in OBS I think a blacklist in target project would be the best.

**Comment by nilxam** [comment]
Yes, I think we need blacklist feature for origin-manager. I also consider that we should porting some features from fcc_submitter to origin-manager, eg. fcc_submitter will not submitting if the package has been removed from *the target project or the previous released project which has same scope, eg. 15.0, 15.1*.

**Comment by nilxam** [comment]
looks it hasn't fixed completely.

<pre>
maxlin_factory@tigercity:~> osc request show 747507
Request: #747507

  submit:       SUSE:SLE-15-SP2:GA/u-boot-odroid-c2@1 -> openSUSE:Leap:15.2


Message:
Submitting new package from highest potential origin. (host go-agent-stagingbot-3)

State:   declined   2019-11-12T09:20:10 lnussel_factory
Comment: multibuild

Review:  new        Project: openSUSE:Leap:15.2:Staging:adi:1          2019-11-12T08:20:48 staging-bot           
  Being evaluated by staging project "openSUSE:Leap:15.2:Staging:adi:1"
         accepted   Group: factory-staging                             2019-11-12T07:49:25 staging-bot           
  Picked openSUSE:Leap:15.2:Staging:adi:1
         accepted   User: origin-manager                               2019-11-12T07:49:25 origin-manager        
  origin: SUSE:SLE-15-SP2:GA
         accepted   User: factory-auto                                 2019-11-12T07:49:25 factory-auto          
  Check script succeeded
         new        User: licensedigger                                2019-11-12T07:49:25                       

History: 2019-11-12T09:20:10 lnussel_factory Request got declined
         2019-11-12T08:21:13 origin-manager Review got accepted
         2019-11-12T08:20:50 staging-bot  Review got accepted
         2019-11-12T08:20:48 staging-bot  Request got a new review request
         2019-11-12T07:58:19 factory-auto Review got accepted
         2019-11-12T07:49:25 origin-manager Request created
</pre>

    maxlin_factory@tigercity:~> osc api "/source/SUSE:SLE-12-SP2:GA/u-boot-odroid-c2/_link"
    <link package="u-boot" cicount="copy" />maxlin_factory@tigercity:~> osc api "/source/SUSE:SLE-12-SP2:GA/u-boot-odroid-c2/_meta"
    <package name="u-boot-odroid-c2" project="SUSE:SLE-12-SP2:GA">
      <title/>
      <description/>
      <bcntsynctag>u-boot</bcntsynctag>
    </package>

    maxlin_factory@tigercity:~> osc api "/source/SUSE:SLE-12-SP2:GA/u-boot/_meta"
    <package name="u-boot" project="SUSE:SLE-12-SP2:GA">
      <title/>
      <description/>
    </package>

    maxlin_factory@tigercity:~> osc api "/source/SUSE:SLE-12-SP2:GA/u-boot-odroid-c2/_meta"
    <package name="u-boot-odroid-c2" project="SUSE:SLE-12-SP2:GA">
      <title/>
      <description/>
      <bcntsynctag>u-boot</bcntsynctag>
    </package>

**Comment by nilxam** [comment]
needs investigation again

**Comment by jberry-suse** [comment]
See 7c1a658f3d22fcbc689c4786fb53f216528133ef.

**Comment by jberry-suse** [comment]
Alternatively, OBS could provide a proper API for distinguishing package types as I requested in mailing list...

**Comment by jberry-suse** [comment]
Either way, the origin manager specific part of this is fixed, but since it relies on `package_kind()` which indicates `source` that implementation needs to be fixed.

**Comment by jberry-suse** [comment]
per the title, origin manager submitted a `source` package as indicated by `package_kind()` so I opened separate issue.
