### ISSUE TITLE
origin-manager: adds update project as maintainer review

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#2308]
Not sure what happened here:
https://build.opensuse.org/request/show/745678

it added openSUSE:Leap:15.1:Update / python-requests-unixsocket as maintainer review

**Comment by jberry-suse** [comment]
Misconfiguration, that was exposed by new package submissions triggered by #2287 being merged. I resolved by changing policy for `openSUSE:Leap:15.1:Update` via `maintainer_review_initial: false` since that is appropriate.
