### ISSUE TITLE
osclib/core: package_kind(): correct multispec_subpackage detection

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#2317]
Caused by 7c1a658 which was not tested properly as I noted in Tuesday call before it was merged. I don't write lines of code for no reason (not the first time I've seen lines removed as the author of PR didn't think they were needed). Likely the link detection needs improvement or OBS could provide a package kind API call or filter on list/search.

Related #2293.

**Comment by coolo** [comment]
The lines may have a reason, but they were still wrong

**Comment by jberry-suse** [comment]
Just increased the blast radius.

**Comment by coolo** [comment]
multispec packages are dying out, so I'm fine with having the current fallback for link detection. Origin manager submitting packages is no longer relevant for leap
