### ISSUE TITLE
add verification tool to check local links

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#2328]
packages with multiple spec files need to have matching links. We should have some tool that regularly checks the distro projects for consistency.

**Comment by coolo** [comment]
https://github.com/openSUSE/openSUSE-release-tools/pull/2337 - it runs a whole while though, but once a week should be fine.

**Comment by coolo** [comment]
taking that multiple spec files are a dying thing, I guess we can leave it to release managers to run it once upon a time
