### ISSUE TITLE
Strange untracked requests

### ISSUE THREAD

**Issue by nilxam** [openSUSE/openSUSE-release-tools#2344]
Just recorded it here before look intro it

In Staging:D https://build.opensuse.org/staging_workflows/136/staging_projects/openSUSE:Leap:15.2:Staging:D

there are three untracked requests, one of that is https://build.opensuse.org/request/show/749174 which still be listed on excluded_requests, not sure how could this be selected, no clue for the rest two requests.

**Comment by nilxam** [comment]
another two https://build.opensuse.org/request/show/750681 and https://build.opensuse.org/request/show/750764 seems because they're from a `home:` namespace?

with our current code it must fails to unselecting them due to they're not part of `staged_requests` but `untracked_requests`

**Comment by nilxam** [comment]
ah, the first round of stagingbot.regular is on master before new_staging_api branch merged to master.

**Comment by nilxam** [comment]
@coolo unselected them. fixed.

**Comment by coolo** [comment]
yeah, yesterday was a little busy - I did too many things in parallel. Sorry
