### ISSUE TITLE
osc staging accept does not 'complete its job'

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/openSUSE-release-tools#2368]
Yesterday evening, I did a checkin using 'osc staging accept' (all green stagings - that was only a list of adi at that time, no letter staging was ready due to the certificate issues still)

The checkin went pretty ok, with a few things observed:
* The 'waiting for staging project 'xxx' to be accepted happened only for one adi (all the others were 'just being accepted after osc staging accept already long finished (not an issue per se, but weird)
* The 'trigger rebuild loop' for the diff between openSUSE:Factory and openSUSE:Factory:Rebuild did not happen
* Product Version in the openSUSE:Factory attribute was not updated (I bumped it this morning manually)

There were no errors in the accept output, the log was (non-debug log)

```
Accepting all acceptable projects
delete links to packages pending deletion...
triggering staging accepts...
Accepting request 755046: SDL2
waiting for staging project openSUSE:Factory:Staging:adi:57 to be accepted
```

**Comment by coolo** [comment]
it's all @nilxam's fault - he approved https://github.com/openSUSE/openSUSE-release-tools/pull/2361/files#diff-fca4de0f3157171ef8868c69e411f2a2R121 :)

**Comment by nilxam** [comment]
hmm..yeah, I've no excuse here :)
