### ISSUE TITLE
osc staging select --remove-exclusion not working

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/openSUSE-release-tools#2374]
While trying to select a package that is on the EXcluded list, I get:

```
dimstar_suse@zeus:~> osc staging select E libtasn1
(1/1) Adding request "750374" to project "openSUSE:Factory:Staging:E"
Server returned an error: HTTP Error 400: Bad Request
Request 750374 currently excluded from project openSUSE:Factory. Use --remove-exclusion if you want to force this action. and Request 750374 not found in Staging for project openSUSE:Factory
```
so, thanks for the hint on how to go on from here, but:

```
dimstar_suse@zeus:~> osc staging select E libtasn1 --remove-exclusion
osc staging: no such option: --remove-exclusion
Try 'osc help staging' for info.
```

The option is not known (of course there is the workaround with osc staging unignore/osc staging select)

**Comment by coolo** [comment]
the error comes from the [API](https://github.com/openSUSE/open-build-service/pull/8639/files#diff-731c4fdd99b9defd6f1a9caaba929b3fR78) not from the staging plugin. This is based on my [feature request](https://github.com/openSUSE/open-build-service/issues/8525) but I never came around to implement this in the client. That the API error talks about command line options is quite fun though.

**Comment by antlarr** [comment]
Just for the record, I just got the same issue that DimStar reported above.

**Comment by suntorytimed** [comment]
Me too. Luckily the workaround with osc staging unignore pointed out by dimstar worked.
