### ISSUE TITLE
gocd file for abichecker needs to have persistent store

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#2375]
the abi checker stores reports in ~/.cache/opensuse.org/abi-checker/ and the database in ~/.local/share/opensuse.org/abi-checker/

AFAICS the gocd file does not seem to specify that so the checker does not export reports that can be looked at and loses it's state. Also, the host that stores the database and reports needs to run the web interface. See /etc/apache2/vhosts.d/opensuse-abi-checker.conf on the host it ran before.

**Comment by coolo** [comment]
the database is persistent, it's mounted from /srv/go-abichecker

**Comment by lkocman** [comment]
@lnussel do you still think that this is an issue?

**Comment by coolo** [comment]
abichecker was actually disabled as noone cared
