### ISSUE TITLE
[Co-op] Configurable package-set per Staging project

### ISSUE THREAD

**Issue by lkocman** [openSUSE/openSUSE-release-tools#2390]
Original request was to Improve picking SAP and HA related packages in staging areas

SLE Technical project manager team is currently trying to endorse individual Release Managers/TPMs to handle staging-activity for their own packageset. 

What we'd like to achieve is to configure Staging environment to automatically place certain (configurable set) of packages to particular staging projects. E.g. All packages identified as part of SAP product into Staging:S. or HPC to H.

Ideally we'd also like to avoid situation where the main Release Manager accidentally places one of identified (let's say SAP) packages into "his" staging project.  But I'm not sure if that would be easy.

**Comment by coolo** [comment]
This doesn't seem actionable. And I don't think there are "individual release managers" handling stagings - so I tend to close this.

**Comment by coolo** [comment]
Thanks for agreeing
