### ISSUE TITLE
Submitting package after declining droprequest of the same package fails

### ISSUE THREAD

**Issue by scarabeusiv** [openSUSE/openSUSE-release-tools#2410]
If I decline botdel package and submit a fix for it the bot declines it later that two conflicting requests are open and one should be declined.

If with user perms I try to supersede the requests it says that I can't do so due to insufficient permissions:
```
$ osc rq supersede 777444 777950 -m "fixed"
HTTP Error 403: Forbidden post_request_no_permission
You have no role in request 777444
```

I think bot should ignore the declined drop requests, or automatically revoke them (also the superseding should work if i have permission on source package, but that is probably OBS enhancement to take develprjs into account in this case).

**Comment by DimStar77** [comment]
This was addressed with https://github.com/openSUSE/openSUSE-release-tools/commit/28d3767e81c7ce3e107ab60f81a7cc6ee0e43185

So if the old request is at least declined, the bot is putting the new one in place
