### ISSUE TITLE
Multibuild package spread across rings

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/openSUSE-release-tools#2428]
The openSUSE Release Tooling needs to support us with a new concept to split multibuild packages across rings (currently not yet possible - OBS support in the works)

OBS will introduce an ```excludebuild``` statement that can be used in prjconf to disable a specific build flavor in ring0 (e.g python3 to be disabled, python3:base enabled). But that will mean we will end up with openSUSE:Factory/python3 to be linkged to Ring0 AND ring1 (both having specific ecludebuild statements)

At the moment, this is 'invalid setup' for the staging tool - it would complain about a package found in multiple rings

**Comment by adrianschroeter** [comment]
Just for reference: https://github.com/openSUSE/open-build-service/pull/9420

**Comment by nilxam** [comment]
Another question in my mind is how would it looks like when the same package has inherited from different project, eg. letter staging(ring0 + ring1), maybe we need a solution for `staging freeze` command also.
