### ISSUE TITLE
Ensure 'factory-maintainers' are devel prj maintainers

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/openSUSE-release-tools#2429]
This is an angle on https://github.com/openSUSE/open-build-service/issues/9310 - trying to at least prevent to run into the permission errors OBS could throw on accept

When a submission is incoming, we shuld ensure the sourceproject (devel prject) hast factory-maintainers (any configurable group - based on OSRT:Config I'd say) defined as maintainer.

During accept this is nescessay to convert the source package into a branch of the target package  (OBS:InitializeDevelProject)

We envision something like:
* factory-auto does not accept (or decline) the review it has open for the package if factory-maintainers is not maintainer in the source project/devel project
* Comment about this fact on the request (to make sure everybody looking at it know about the issue)
* Send an Addrole request to the source prject, to have the issue corrected

**Comment by coolo** [comment]
good entry level issue for someone who would like to contribute

**Comment by ancorgs** [comment]
> When a submission is incoming, we shuld ensure the sourceproject (devel prject) hast factory-maintainers (any configurable group - based on OSRT:Config I'd say) defined as maintainer.

Which value from OSRT:Config would you suggest to use? Or should we add a new one (if that's the case, you choose the name :wink:)?

Or it's maybe better to receive it as some kind of parameter or env variable that we can set in gocd?

**Comment by ancorgs** [comment]
Why cannot we simply use the maintainer(s) of the target project?

**Comment by coolo** [comment]
The user story as outlined here is only interesting for openSUSE:Factory - we don't need that for SLE or Leap. So it needs to be configurable - if that's a "expect all the maintainer groups in the source" or "expect specific group in source" doesn't really matter (as long as we only have one group in Factory maintaining).

The latter appears more natural to me though.

**Comment by coolo** [comment]
Oh, and about persons maintaining: we use the maintainer field of the devel package to configure who gets the bug reports (bugowners aren't normally set for openSUSE), so polluting that with persons would increase @DimStar77's bug list dramatically.

**Comment by DimStar77** [comment]
> Oh, and about persons maintaining: we use the maintainer field of the devel package to configure who gets the bug reports (bugowners aren't normally set for openSUSE), so polluting that with persons would increase @DimStar77's bug list dramatically.

Thanks for thinking about my sanity and my mailbox

**Comment by DimStar77** [comment]
> > When a submission is incoming, we shuld ensure the sourceproject (devel prject) hast factory-maintainers (any configurable group - based on OSRT:Config I'd say) defined as maintainer.
> 
> Which value from OSRT:Config would you suggest to use? Or should we add a new one (if that's the case, you choose the name 😉)?
> 
> Or it's maybe better to receive it as some kind of parameter or env variable that we can set in gocd?

Cloud be as speaking as
`mandatory_devel_maintainer = group:factory-maintainers`

**Comment by ancorgs** [comment]
Shouldn't this requirement be documented at [1]? That would surely help us to add a meaningful comment for the declined review.

[1] https://en.opensuse.org/openSUSE:How_to_contribute_to_Factory#How_to_request_a_new_devel_project
