### ISSUE TITLE
origin manager notices that request with same hash was rejected and skips it, even when origin has changed

### ISSUE THREAD

**Issue by lkocman** [openSUSE/openSUSE-release-tools#2431]
Hello

we've received a submission against Leap for a package with SLE origin.
Same submission was later accepted in SUSE:SLE-15-SP2:GA however Leap did no receive a submission as it was ignored.

Can we please check also for the origin:
https://github.com/openSUSE/openSUSE-release-tools/blob/master/osclib/origin.py#L732

Thank you

**Comment by lkocman** [comment]
lkocman-factory@localhost:~> osc -d origin update -p openSUSE:Leap:15.2 unar
checking for updates to openSUSE:Leap:15.2/unar...
CACHE_MISS https://api.opensuse.org/statistics/latest_updated?limit=5000 (expired)
GET https://api.opensuse.org/statistics/latest_updated?limit=5000
CACHE_PUT https://api.opensuse.org/statistics/latest_updated?limit=5000 None
CACHE_MISS https://api.opensuse.org/source/openSUSE:Leap:15.2/_attribute/OSRT:OriginConfig (does not exist)
GET https://api.opensuse.org/source/openSUSE:Leap:15.2/_attribute/OSRT:OriginConfig
CACHE_PUT https://api.opensuse.org/source/openSUSE:Leap:15.2/_attribute/OSRT:OriginConfig openSUSE:Leap:15.2
GET https://api.opensuse.org/search/project?match=starts-with%28remoteurl%2C+%22http%22%29
CACHE_MISS https://api.opensuse.org/source/openSUSE:Leap:15.2/_attribute/OSRT:Config (does not exist)
GET https://api.opensuse.org/source/openSUSE:Leap:15.2/_attribute/OSRT:Config
CACHE_PUT https://api.opensuse.org/source/openSUSE:Leap:15.2/_attribute/OSRT:Config openSUSE:Leap:15.2
CACHE_MISS https://api.opensuse.org/source/openSUSE:Leap:15.2/unar/_link (does not exist)
GET https://api.opensuse.org/source/openSUSE:Leap:15.2/unar/_link
CACHE_MISS https://api.opensuse.org/source/openSUSE:Leap:15.2/unar (does not exist)
GET https://api.opensuse.org/source/openSUSE:Leap:15.2/unar
CACHE_PUT https://api.opensuse.org/source/openSUSE:Leap:15.2/unar openSUSE:Leap:15.2
GET https://api.opensuse.org/search/request?withfullhistory=1&match=%28state%2F%40name%3D%27new%27+or+state%2F%40name%3D%27review%27%29+and+%28action%2Ftarget%2F%40project%3D%27openSUSE%3ALeap%3A15.2%27%29+and+%28action%2Ftarget%2F%40package%3D%27unar%27%29+and+action%2F%40type%3D%27change_devel%27
GET https://api.opensuse.org/search/request?withfullhistory=1&match=%28state%2F%40name%3D%27new%27+or+state%2F%40name%3D%27review%27%29+and+%28action%2Ftarget%2F%40project%3D%27openSUSE%3ALeap%3A15.2%27%29+and+%28action%2Ftarget%2F%40package%3D%27unar%27%29+and+action%2F%40type%3D%27submit%27
CACHE_MISS https://api.opensuse.org/source/openSUSE:Leap:15.2/unar/_meta (does not exist)
GET https://api.opensuse.org/source/openSUSE:Leap:15.2/unar/_meta
CACHE_PUT https://api.opensuse.org/source/openSUSE:Leap:15.2/unar/_meta openSUSE:Leap:15.2
CACHE_GET https://api.opensuse.org/source/openSUSE:Leap:15.2/unar/_meta
CACHE_MISS https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/unar/_history (does not exist)
GET https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/unar/_history
CACHE_PUT https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/unar/_history SUSE:SLE-15-SP2:GA
CACHE_MISS https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/unar/_link (does not exist)
GET https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/unar/_link
CACHE_MISS https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/unar?rev=c0165706f57c9b44ae67497269e8152e (does not exist)
GET https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/unar?rev=c0165706f57c9b44ae67497269e8152e
CACHE_PUT https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/unar?rev=c0165706f57c9b44ae67497269e8152e SUSE:SLE-15-SP2:GA
CACHE_MISS https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/unar?rev=56ecbf9c0e68814f212082f09b0abd88 (does not exist)
GET https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/unar?rev=56ecbf9c0e68814f212082f09b0abd88
CACHE_PUT https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/unar?rev=56ecbf9c0e68814f212082f09b0abd88 SUSE:SLE-15-SP2:GA
CACHE_MISS https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/_attribute/OSRT:Config (does not exist)
GET https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/_attribute/OSRT:Config
CACHE_PUT https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/_attribute/OSRT:Config SUSE:SLE-15-SP2:GA
GET https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/unar/_attribute/OSRT:OriginUpdateSkip
CACHE_MISS https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/_attribute/OSRT:OriginUpdateSkip (does not exist)
GET https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/_attribute/OSRT:OriginUpdateSkip
CACHE_PUT https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/_attribute/OSRT:OriginUpdateSkip SUSE:SLE-15-SP2:GA
GET https://api.opensuse.org/source/openSUSE:Leap:15.2/unar/_attribute/OSRT:OriginUpdateSkip
CACHE_MISS https://api.opensuse.org/source/openSUSE:Leap:15.2/_attribute/OSRT:OriginUpdateSkip (does not exist)
GET https://api.opensuse.org/source/openSUSE:Leap:15.2/_attribute/OSRT:OriginUpdateSkip
CACHE_PUT https://api.opensuse.org/source/openSUSE:Leap:15.2/_attribute/OSRT:OriginUpdateSkip openSUSE:Leap:15.2
GET https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/unar/_attribute/OSRT:OriginUpdateSupersede
CACHE_MISS https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/_attribute/OSRT:OriginUpdateSupersede (does not exist)
GET https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/_attribute/OSRT:OriginUpdateSupersede
CACHE_PUT https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/_attribute/OSRT:OriginUpdateSupersede SUSE:SLE-15-SP2:GA
GET https://api.opensuse.org/source/openSUSE:Leap:15.2/unar/_attribute/OSRT:OriginUpdateSupersede
CACHE_MISS https://api.opensuse.org/source/openSUSE:Leap:15.2/_attribute/OSRT:OriginUpdateSupersede (does not exist)
GET https://api.opensuse.org/source/openSUSE:Leap:15.2/_attribute/OSRT:OriginUpdateSupersede
CACHE_PUT https://api.opensuse.org/source/openSUSE:Leap:15.2/_attribute/OSRT:OriginUpdateSupersede openSUSE:Leap:15.2
GET https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/unar/_attribute/OSRT:OriginUpdateDelay
CACHE_MISS https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/_attribute/OSRT:OriginUpdateDelay (does not exist)
GET https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/_attribute/OSRT:OriginUpdateDelay
CACHE_PUT https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/_attribute/OSRT:OriginUpdateDelay SUSE:SLE-15-SP2:GA
GET https://api.opensuse.org/source/openSUSE:Leap:15.2/unar/_attribute/OSRT:OriginUpdateDelay
CACHE_MISS https://api.opensuse.org/source/openSUSE:Leap:15.2/_attribute/OSRT:OriginUpdateDelay (does not exist)
GET https://api.opensuse.org/source/openSUSE:Leap:15.2/_attribute/OSRT:OriginUpdateDelay
CACHE_PUT https://api.opensuse.org/source/openSUSE:Leap:15.2/_attribute/OSRT:OriginUpdateDelay openSUSE:Leap:15.2
GET https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/unar/_attribute/OSRT:OriginUpdateFrequency
CACHE_MISS https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/_attribute/OSRT:OriginUpdateFrequency (does not exist)
GET https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/_attribute/OSRT:OriginUpdateFrequency
CACHE_PUT https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/_attribute/OSRT:OriginUpdateFrequency SUSE:SLE-15-SP2:GA
GET https://api.opensuse.org/source/openSUSE:Leap:15.2/unar/_attribute/OSRT:OriginUpdateFrequency
CACHE_MISS https://api.opensuse.org/source/openSUSE:Leap:15.2/_attribute/OSRT:OriginUpdateFrequency (does not exist)
GET https://api.opensuse.org/source/openSUSE:Leap:15.2/_attribute/OSRT:OriginUpdateFrequency
CACHE_PUT https://api.opensuse.org/source/openSUSE:Leap:15.2/_attribute/OSRT:OriginUpdateFrequency openSUSE:Leap:15.2
GET https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/unar/_history?limit=1
CACHE_MISS https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/unar (does not exist)
GET https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/unar
CACHE_PUT https://api.opensuse.org/source/SUSE:SLE-15-SP2:GA/unar SUSE:SLE-15-SP2:GA
GET https://api.opensuse.org/search/request?withfullhistory=1&match=%28state%2F%40name%3D%27new%27+or+state%2F%40name%3D%27review%27+or+state%2F%40name%3D%27declined%27+or+state%2F%40name%3D%27revoked%27+or+state%2F%40name%3D%27superseded%27%29+and+%28action%2Ftarget%2F%40project%3D%27openSUSE%3ALeap%3A15.2%27%29+and+%28action%2Ftarget%2F%40package%3D%27unar%27%29+and+action%2F%40type%3D%27submit%27
CACHE_MISS https://api.opensuse.org/source/Archiving/unar/_link (does not exist)
GET https://api.opensuse.org/source/Archiving/unar/_link
CACHE_PUT https://api.opensuse.org/source/Archiving/unar/_link Archiving
CACHE_MISS https://api.opensuse.org/source/Archiving/unar?rev=16 (does not exist)
GET https://api.opensuse.org/source/Archiving/unar?rev=16
CACHE_PUT https://api.opensuse.org/source/Archiving/unar?rev=16 Archiving
lkocman-factory@localhost:~> osc origin update -p openSUSE:Leap:15.2 unar
checking for updates to openSUSE:Leap:15.2/unar...

**Comment by coolo** [comment]
leap got jumped
