### ISSUE TITLE
file conflict checker bot raises conflicting %ghost files as an issue

### ISSUE THREAD

**Issue by lkocman** [openSUSE/openSUSE-release-tools#2439]
Hello seems like our file conflict checker bot incorrectly raises conflicts on %ghost files.
Proposed workaround is considered intrusive and considered harmful by Thorsten Kukuk.

https://build.suse.de/request/show/217825
https://bugzilla.suse.com/show_bug.cgi?id=1171495

**Comment by coolo** [comment]
I have no intention to change this. %ghosts should not be spammed
