### ISSUE TITLE
obs-service-product_converter conflicts with  obs-service-generator_driver_update_disk on file BSKiwiXML.pm

### ISSUE THREAD

**Issue by lkocman** [openSUSE/openSUSE-release-tools#2454]
This conflict was raised during installation of osc-service-* on openSUSE Leap 15.2 from the openSUSE Release tools OBS repo.

Detected 1 file conflict:

File /usr/lib/obs/service/BSKiwiXML.pm
  from install of
     obs-service-product_converter-1.4.0-lp152.32.1.noarch (openSUSE.org tools (openSUSE_15.2))
  conflicts with file from install of
     obs-service-generator_driver_update_disk-0.2-lp152.2.3.noarch (openSUSE.org tools (openSUSE_15.2))

File conflicts happen when two packages attempt to install files with the same name but different contents. If you continue, conflicting files will be replaced losing the previous content.
Continue? [yes/no] (no): YES

**Comment by coolo** [comment]
None of these packages is maintained in here.
