### ISSUE TITLE
Critical reviews seem not to be displayed on top of the list after some time

### ISSUE THREAD

**Issue by lkocman** [openSUSE/openSUSE-release-tools#2455]
I did recently open few legaldb reviews for WSL (mainly mingw* packages). 
I did set the OBS request priority to "critical" to top the priority of the legal review process.

Example: http://legaldb.suse.de/reviews/details/169495

A few days after the issues are no longer on top of the list and some maintenance reviews got in front of them.

**Comment by coolo** [comment]
The legal-auto bot isn't part of cavil

**Comment by coolo** [comment]
This is impossible to dig out now
