### ISSUE TITLE
prj_frozen_enough should succeed directly after freeze on empty staging

### ISSUE THREAD

**Issue by JanZerebecki** [openSUSE/openSUSE-release-tools#2462]
Calling prj_frozen_enough should succeed when it is run seconds after running freeze on an empty staging, but it currently doesn't.

The content `<frozenlinks/>` results in a directory entry of `<entry name="_frozenlinks" md5="efc2797971ad89150e0777371ccea1a6" size="15" mtime="1592819428"/>`. [The incorrect mtime needs to be expected and is probably a result of OBS storing it on the md5 of the file instead of in the directory](https://github.com/openSUSE/open-build-service/issues/4365). This mtime makes [prj_frozen_enough()](https://github.com/openSUSE/openSUSE-release-tools/blob/master/osclib/stagingapi.py#L1170) return false as it is older than [MAX_FROZEN_AGE](https://github.com/openSUSE/openSUSE-release-tools/blob/master/osclib/freeze_command.py#L7).

One way to work around this is to use `--no-freeze` with `osc staging select`.

**Comment by coolo** [comment]
I'm afraid this needs working around OBS, so it would just move the layer of working around :(
