### ISSUE TITLE
Creating / Associating bugowner request with new package creation

### ISSUE THREAD

**Issue by fcrozat** [openSUSE/openSUSE-release-tools#2463]
This is a follow-up of https://github.com/openSUSE/open-build-service/issues/9152

Currently, we can't assign bugowner to a package, until it is created, ie until submit request for it is accepted.

It would be very helpful to allow creating bugowner request for packages which are not existing in a project. This way, we could stage those requests along the submit request with the code and have both requests accepted at the same time (and potentielly, have some reviews to ensure we can't accept package creation if corresponding bugowner information is not available.

see the discussion on the initial issue for some ideas on how to fix this.

**Comment by coolo** [comment]
CC @suntorytimed @gyr 

I was thinking the actual bugowner request/change can be delayed actually until the next milestone. What's most important here is having with every new package the information what the bugowner should be set to.

So I was thinking about a new policy the target project can set for factory-auto. it would basically boil down to requiring a "bugowner: group:gnome-maintainers" in the request description for a new package. Having it in comments is a bit dangerous as comments can be edited and deleted - and aren't unique in general.

**Comment by coolo** [comment]
I created a new IBS user `bugowner-checker` that does this. If you add it as reviewer for SP4, you can have it.

**Comment by deneb-alpha** [comment]
thanks for the new bot @coolo :)

**Comment by coolo** [comment]
I consider this fixed
