### ISSUE TITLE
Leap 15.2 not in the statistics

### ISSUE THREAD

**Issue by coogor** [openSUSE/openSUSE-release-tools#2486]
Hi,
looking at metrics.opensuse.org the numbers are going down dramatically, as Leap 15.2 is not in the evaluation. 
Can this be added?
Thanks!

**Comment by aaronpuchert** [comment]
It should be included now, can you check again?

**Comment by coogor** [comment]
Yes, it is in now! Thank you!
Anythng we need to address already for 15.3?

**Comment by aaronpuchert** [comment]
Yes, one would need to repeat #2493.
