### ISSUE TITLE
installcheck: Add ability to ignore particular dependeoncy on RPM

### ISSUE THREAD

**Issue by lkocman** [openSUSE/openSUSE-release-tools#2525]
Hello

Closing the Leap Gap, specifically the indenticallity part will result into situations where we'll build package (let's say pgadmin4) with all of its rpms in SUSE:SLE, in such case all build dependencies are satisified, but some package lack runtime deps.

The reason for not adding certain runtime dependencies is easy, we don't want to or can't maintain them (resources).
To be able to keep identical packages where we can, we'd like to be able to waive these exceptions.

An example from SLE-15-SP3, where we build pgadmin4-web-uwsgi internally in SUSE:SLE, but we don't intend to ship it, as uwsgi (it's runtime requirements) is expected to be only in Leap and Package Hub.

We're currently hitting this particular installcheck error:

Generated from http://botmaster.suse.de:8153/go/tab/build/detail/SLE15.SP3.Staging.D/429/Checks/1/Repo.Checker#tab-console

### [install check & file conflicts for x86_64]

can't install pgadmin4-web-uwsgi-4.29-1.2.noarch:
nothing provides uwsgi needed by pgadmin4-web-uwsgi-4.29.noarch

**Comment by lkocman** [comment]
Dirty hack would be to add provides to the -release package ... but that would be only source of another issues.

**Comment by lkocman** [comment]
Current workaround is to submit these runtime dependencies to SLE, but not to ship them ... I know it's an expensive workaround

**Comment by DimStar77** [comment]
We have already something in place:

in theOSRT:Config attribute:

```
# subpackages of ring packages with unacceptable requires (don't abuse)
repo_checker-binary-whitelist-ring =
```

**Comment by DimStar77** [comment]
Is there still something needed? or is that repo_checker-binary-whitelist sufficient? Jiri at least used it and his usecase could be satisfied

**Comment by lkocman** [comment]
I think that nobody really complained for this so far. So I think they found a way to get around it. Marking as resolved
