### ISSUE TITLE
Rewrite factory submitter for "Jump" style distribution

### ISSUE THREAD

**Issue by lkocman** [openSUSE/openSUSE-release-tools#2534]
We've rejected https://progress.opensuse.org/issues/76417 in Leap 15.3 as we didn't have factory submitter tweaked for use without origin manager. this is a todo to revisit this for openSUSE Leap 15.4

**Comment by lkocman** [comment]
Perhaps openSUSE Step / Leap testing could play a role in this @dirkmueller

**Comment by coolo** [comment]
I get it
