### ISSUE TITLE
pkglistgen: output some warning (or error) when package specified in groups.yml get moved

### ISSUE THREAD

**Issue by fcrozat** [openSUSE/openSUSE-release-tools#2541]
Currently, packages listed explicitly in groups.yml are only a hint to where the package should land. If some other dependency starts moving this package to another module, generator will happily comply.

We should maybe have some warning or error in that case. Comparing with reference-summary file isn't really enough to catch those changes.

**Comment by coolo** [comment]
How is comparing with reference not good enough?

And how do you envision this? The solver only moves packages downwards in the chain, the package will always be in the group it was listed it - just possibly from a layer substracted later.

**Comment by coolo** [comment]
Something else: when was the last time you guys actually looked at warnings from the pkglistgen process? There are a lot of those
