### ISSUE TITLE
pkglistgen: Adding a package not found causes invalid package name to be added to packagelist

### ISSUE THREAD

**Issue by fcrozat** [openSUSE/openSUSE-release-tools#2562]
on BCI, I added to group.yml
libicu
which is not found (it is only a provides).

It causes the pkglistgen to output:
```
BCI-ftp-ftp-x86_64.kiwi
56:      <repopackage name=" libicu not found on x86_64"/>

ftp.group
53:    <package name=" libicu not found on x86_64" supportstatus="l3"/>

BCI-ftp-ftp-x86_64.kwd
1: libicu not found on x86_64: +Kwd:\nsupport_l3\n-Kwd:
```

This is causing repo build to abort. I'm not sure it is wanted or not.

**Comment by DimStar77** [comment]
> on BCI, I added to group.yml
> libicu
> which is not found (it is only a provides).
> 
> It causes the pkglistgen to output:
> 
> ```
> BCI-ftp-ftp-x86_64.kiwi
> 56:      <repopackage name=" libicu not found on x86_64"/>
> 
> ftp.group
> 53:    <package name=" libicu not found on x86_64" supportstatus="l3"/>
> 
> BCI-ftp-ftp-x86_64.kwd
> 1: libicu not found on x86_64: +Kwd:\nsupport_l3\n-Kwd:
> ```
> 
> This is causing repo build to abort. I'm not sure it is wanted or not.

to me, requesting a package that does not exist should be a reason to abort the build

**Comment by fcrozat** [comment]
Sure, I'm used to have staging catching those issues, but BCI doesn't have staging. I just wonder if it is expected or not.

**Comment by coolo** [comment]
It's a feature actually to avoid the product to build before e.g. a renamed package is done. Because product builder itself ignores packages not existing (it's just a warning there)
