### ISSUE TITLE
rejects SR for creating MU on rebuilt only package without change entry

### ISSUE THREAD

**Issue by JanZerebecki** [openSUSE/openSUSE-release-tools#2679]
factory-auto rejected the SR https://build.opensuse.org/request/show/941908 for creating an MU because it contains a package that is only rebuilt and thus is without a change entry. For some type of packages this is a regular occurrence, thus it should be allowed.

I have worked around the problem for now by adding a change entry.

The same thing didn't happen on some similar MUs in build.suse.de.

The error is produced at https://github.com/openSUSE/openSUSE-release-tools/blob/153aea3674549de4dcd6d5604d6fa7855c37a297/check_source.pl#L93

Does "obsolete (by origin-manager)" from https://github.com/openSUSE/openSUSE-release-tools/blob/master/CONTENTS.md#check_maintenance_incidents mean that after some other change this will also be solved for this request? Which change?

Or should the above code location be changed to only trigger if there is any change in the package but not just for a rebuild?

**Comment by coolo** [comment]
factory-auto is named like that as it's implementing openSUSE:Factory policies, using it in openSUSE:Maintenance is a policy decision not to accept packages without changelog. SUSE:Maintenance on IBS doesn't use factory-auto, so it's obvious why you don't get declines there.
