### ISSUE TITLE
the certifications module group gets an unrelated release package pulled in

### ISSUE THREAD

**Issue by msmeissn** [openSUSE/openSUSE-release-tools#2698]
(IBS) SUSE:SLE-15-SP3:GA 000package-groups groups.yml

  - sle_module_certifications:
      default-support: l3
      excludes:
      - sle_module_basesystem

the generated sle_module_certifications.group  in SUSE:SLE-15-SP3:GA 000product has
- sle-module-certifications-release (OK)
- SUSE-Manager-Server-release (BAD, should not be there)

**Comment by coolo** [comment]
Well, sle-module-certifications-release requires `product(SUSE_SLE) >= 15.4` and that's exactly what SUSE-Manager-Server-release provides. Not sure who created this group, but they should have looked at all the other groups and wonder "why does everyone else include sle_minimal?"

**Comment by coolo** [comment]
There is one bug though I'm looking into: the bad release file should be reference-summary, but isn't

**Comment by coolo** [comment]
No bug. SLE release managers faked their way through it by deleting all of SUSE Manager in stagings. 
https://botmaster.suse.de/go/tab/build/detail/SLE15.SP4.Package.Lists/349/Update.000product/1/Update.000product nicely shows

```
 sle_module_certifications:
+  - SUSE-Manager-Retail-Branch-Server-release
   - sle-module-certifications-release
```
