### ISSUE TITLE
staging freeze: unknown status for flag \'None\'

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/openSUSE-release-tools#2817]
Every now and then, `osc staging freeze` errors out with
 `Error: unknown status for flag 'None'`

A debug trace shows we try to explicitly set this at:

```
PUT https://api.opensuse.org/source/openSUSE:Factory:Staging:B/bootstrap-copy/_meta
POST https://api.opensuse.org/source/openSUSE:Factory:Staging:B?cmd=set_flag&flag=build&status=enable
POST https://api.opensuse.org/source/openSUSE:Factory:Staging:B?cmd=set_flag&flag=build&status=None&repository=images
```

**Comment by DimStar77** [comment]
Just ran into this on Staging:H - and I was 'smart enough' to check prj meta before the freeze:

```
  <build>
    <disable repository="bootstrap_copy"/>
    <enable/>
  </build>
```

This seems to be running into the error, due to this code: https://github.com/openSUSE/openSUSE-release-tools/blob/master/osclib/freeze_command.py#L134

```
        images_status = self.api.get_flag_in_prj(prj, flag='build', repository='images')
…
        if build_status == 'enable':
            self.api.build_switch_prj(prj, images_status, repository='images')
```

**Comment by DimStar77** [comment]
The problem happens here:

https://github.com/openSUSE/openSUSE-release-tools/blob/67d6535836432c5aea512c95fc2de79598a28adb/gocd/pkglistgen_staging.gocd.yaml#L514

We 'delete' the entry instead of setting it 'enabled'  - which causes freeze to stumble over None

**Comment by DimStar77** [comment]
https://github.com/openSUSE/openSUSE-release-tools/pull/2818

**Comment by coolo** [comment]
... got merged
