### ISSUE TITLE
Leap opensuse 15.5 python-3.10.8 and mamba, jupyterlab open work

### ISSUE THREAD

**Issue by Penguinbot4** [openSUSE/openSUSE-release-tools#2905]
i see the default install is python3.6 and i had a bit of a problem install the update to python 3.10.8 latest version of 3.10
the build is missing 6 modules and pip now install and works as it should
the install mamba and juypterlab do not install yet

the screen shots show progress and x11 clients and now working this isi chroot built by 15.5 iso image and rpm -aql and tar
the missing modules shown are from debian sid and are src, to be install in suse 15.5 leap

zypper and dnf and rpm have been a great help 
![Screenshot_2022-12-04_00-03-02](https://user-images.githubusercontent.com/118845597/205516420-2f593809-fdf0-4378-82e1-f0dc1e6ecccc.png)
![Screenshot_2022-12-04_11-00-52](https://user-images.githubusercontent.com/118845597/205516432-7e1b8def-b33b-4cac-af7f-5924e021e9e5.png)
![Screenshot_2022-12-04_00-41-55](https://user-images.githubusercontent.com/118845597/205516436-2a2e7f1d-f6b7-4795-bda6-a044d900d885.png)
![Screenshot_2022-12-04_00-33-40](https://user-images.githubusercontent.com/118845597/205516437-7ab9ed6e-caa7-4dc2-b831-90c49f60f19a.png)
![Screenshot_2022-12-04_00-24-25](https://user-images.githubusercontent.com/118845597/205516438-4a7ec3e8-1bcd-4797-b3fb-475c21c41a6c.png)
![Screenshot_2022-12-04_00-07-25](https://user-images.githubusercontent.com/118845597/205516440-ccf77100-2f45-462f-91c0-efda98c6be2d.png)

the rpm and tar error logs
[tar.log](https://github.com/openSUSE/openSUSE-release-tools/files/10152651/tar.log)
[root-t.err.log](https://github.com/openSUSE/openSUSE-release-tools/files/10149499/root-t.err.log)

**Comment by luc14n0** [comment]
Yes, this is not the right place @Penguinbot4. The release tools has nothing to do with **Leap 15.5**'s development, which in turn begs the question: why are you using **15.5**? It's still in Alpha - if memory serves.

**Comment by luc14n0** [comment]
OK, if you want to take the risks of using such an early version of a product still in development who am I to say no. For your information, **openSUSE Leap** bugs are filed in **openSUSE**'s [bugzilla](https://en.opensuse.org/openSUSE:Submitting_bug_reports), and you can open discussions in the mailing list too.
