### ISSUE TITLE
UI change: /monitor duplicates texts

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/openSUSE-release-tools#2913]
Today, the new UI toolkit was deployed, and following the build monitor makes me dizzy:

![image](https://user-images.githubusercontent.com/532559/212047751-2d0276fc-d347-4c18-9a34-e09d32c9b6fb.png)

The left column has all the text duplicated/shifted

**Comment by DimStar77** [comment]
Tested in Firefox and Chrome - both show this behavior

**Comment by dmarcoux** [comment]
This issue should be opened in https://github.com/openSUSE/open-build-service. Meanwhile, someone else opened an issue: #13677.

**Comment by coolo** [comment]
I guess this is a case of tab completion going wrong :)

**Comment by DimStar77** [comment]
> 

d'oh... indeed... sorry
