### ISSUE TITLE
abichecker: need to handle failed

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#368]
need to handle failed and decline:
https://github.com/openSUSE/osc-plugin-factory/blob/master/abichecker/abichecker.py#L893

**Comment by jberry-suse** [comment]
Took a bit to find the version that matched the line number (perma links plz).

https://github.com/openSUSE/openSUSE-release-tools/blob/2c053222c6dffcbd962dad7ca0c6ef5352cd928d/abichecker/abichecker.py#L893

@lnussel, Is this still relevant and self assigned?

**Comment by lnussel** [comment]
should be fixed for completeness I guess but abichecker is rather unmaintained unfortunately. Never got around porting it to a better framework.
