### ISSUE TITLE
maintbot opens duplicate reviews

### ISSUE THREAD

**Issue by andreasstieger** [openSUSE/openSUSE-release-tools#528]
"Submission by someone who is not maintainer in the devel project. Please review"
Duplicate reviews can be added if >1 package comes from the same project and the packages inherit the maintainers from the project.
e.g. https://build.opensuse.org/request/show/401699

```
Review: new Project: KDE:Extra
Submission by someone who is not maintainer in the devel project. Please review
new Project: KDE:Extra
Submission by someone who is not maintainer in the devel project. Please review
```

Ideally only one review is opened.

**Comment by jberry-suse** [comment]
Should be resolved by #1051.
