### ISSUE TITLE
Consider allowing ring requests to be marked as ready and unstaged like adi

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#698]
It seems like the same workflow used by adi stagings could be used for letter stagings in that once the staging is acceptable the requests could be marked "ready to accept" and the staging cleared. This would allow the stagings to be utilized even if the conditions are not right for accepting the requests into the project (ie waiting for Factory to finish building to kick off a snapshot). This would free up those stagings for new requests instead of holding up the process.

**Comment by DimStar77** [comment]
the risk that a letter staging with 'any number of requests' has been buildtested and QAd against each other, then moved to 'ready to accept', followed by any 'newer submission incoming superseding one out of the group' is too high imho.

This would break the group as the superseded package is no longer 'ready to accept' and the rest could fly through, potentially breaking rings from building, making staging a pain.

👎

**Comment by jberry-suse** [comment]
The same problem is true of the adi workflow right now. Even more fun is when two submissions from different sources are both sent and not marked superseding even though they either are or are identical. Seems like a different method for solving the superseded request issue is needed and applied to both workflows.

**Comment by DimStar77** [comment]
yes, it is true for adi - but the impact is much lower; if you break the rings, you impact all letter stagings and that's the stuff we 'guarantee' to build

**Comment by lnussel** [comment]
an option would be to copy the ready sources to a separate project. If a request became invalid by the time we do the checkin we could still use the saved sourced.

The problem with different sources is leap specific as we do not use devel projects. I guess one of the bots should take care of that and decline requests that target the same package as an existing request but have a different source.

**Comment by nilxam** [comment]
please note, the outdated request will be declined by repochecker...

**Comment by lnussel** [comment]
ok, so we closing this one
