### ISSUE TITLE
accept: add conditions to allow for automatic acceptance

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#727]
- discuss and collect current conditions applied manually
- review @DimStar77 [script](/DimStar77/openSUSE-helpers/blob/master/Tumbleweed-Dev-Scripts/accept_green_stagings.sh)

Accepting green stagings automatically has the benefit of clearing up stagings which can then be used in automated proposals.

**Comment by jberry-suse** [comment]
If I understand correctly the principle considerations are allowing enough time for the main project to complete builds so that snapshots can be released. This is relevant for both Tumbleweed and Leap (with snapshot pre-release cycle). It is not clear if the snapshot should be fully released or simply built and sent to openqa before the next accept round. I would assume the `totest` repo would have separate conditions for being updated to prevent skipping a release.

The rest of the referenced script is making sure that superseded requests and adi stagings are as far along as they can be. This can be accomplished by placing the `accept` command last in the `staging-bot` service, but does not seem necessary since superseded requests will cause a staging to be unacceptable and the adi command will be run regularly anyway. If run last then the now empty stagings will be used right away. Either end has pros and cons, but running last seems fine.

As such the only piece that would seem to be needed is checking the build status of main project with a new flag on `accept`. If the project pre-condition is met all acceptable stagings are accepted.

Does this seem reasonable? Otherwise, what else is needed?

**Comment by jberry-suse** [comment]
Are there any reactions on sync'ing the checkin rounds between Factory and Leap as the build time is influenced by freezes and checkins in the other project? Especially, if this is automated it should be fairly easy to sync them or offset them so that accepts are never done in one project while the other is still building. Or only done together and freezing of stagings waits until both complete building.

**Comment by DimStar77** [comment]
There are no considerations on accepting TW with regards to Leap (and I'm pretty sure there are none the other way around neither). We simply expect OBS to have the power needed to keep us moving

**Comment by DimStar77** [comment]
as for the condition to accept: the snapshot must have moved to openQA and openQA must have picked up the tests. for TW, we also have a OBS-backend task running that is syncing /standard with /totest, which must be completed (or we could not sync /totest to /snapshot once openQA gives green light).

The move from standard to totest is guarded by totest-manager: as long as a snapshot is still testing (and not yet considered failed), a new snapshot is put on hold for sync, until ttm can either release the snapshot (passed) or discard it (failed).

Last but not least: the versioning of TW mandates a maximum count of 1 checkin per day; for Leap, this limitation does not apply AFAIK

**Comment by jberry-suse** [comment]
Out of curiousity, does your [ @DimStar77 ] script include `osc staging unlock` ? From today's automatic checkin the hold seemed to remain after the checkin until it expired. This was also the case when max reported the staging-bot which had taken over the lock due to a bug after it expired.

**Comment by DimStar77** [comment]
yes it does, unless osc crashes due to https://github.com/openSUSE/osc-plugin-factory/issues/911 - there is no proper error handler in the script (yet)
