### ISSUE TITLE
considering breaking out `select --add` as separate command

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#754]
The select logic seems a bit odd since it basically has the `--add` option which does not perform a select, but instead adds packages to a project's pseudometa.

```python
if opts.add:
    api.mark_additional_packages(target_project, [opts.add])
else:
    SelectCommand(api, target_project) \
        .perform(requests, opts.move, opts.from_, opts.no_freeze)
```

```python
meta['add_to_repo'] = sorted(additionals)
self.set_prj_pseudometa(project, meta)
```

I am not familiar with what `add_to_repo` is achomplishing as it is not referenced anywhere else in the codebase. Is this still utilized and if so should it be moved out of select in a similar fashion to moving `list --supersede` into a separate command in #738.

**Comment by DimStar77** [comment]
@coolo 
Do you have strong feelings for ```select --add``` and a usecase for it? Otherwise I'd actually propose to remove this code completely

**Comment by coolo** [comment]
https://progress.opensuse.org/issues/2892 never worked out - but we didn't remove the code.

**Comment by DimStar77** [comment]
I think the use case documented in the progress issue is mainly obsolete by the fact of us having a 'more complete ring' - which is self contained up to the install level for repo-checker (without layering)

**Comment by coolo** [comment]
this issue (and the code) predates staging projects even

**Comment by coolo** [comment]
(repo checker using staging projects I mean)
