### ISSUE TITLE
select: place requests in staging where that package is broken or non-none strategy and broken staging

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#803]
As a pre-step to either `select` or as a new command, consider broken stagings. The following two examples should clarify the intention.

- Staging:A
  - xmlgraphics-fop build fails
- Staging:C
  - devel @ KDE:Frameworks5
  - digikam builds

Relevant backlog:

- xmlgraphics-fop
- photo-lib-foo from KDE:Frameworks5
- digikam from KDE:Frameworks5

Select:

- xmlgraphics-fop -> Staging:A
- photo-lib-foo -> Staging:C
- digikam -> Staging:C

Essentially, a failed staging merge condition. Currently, the only merge occur as followups to initially staging while a staging is still building. This would handle followup requests to resolve issues after building completes.

**Comment by coolo** [comment]
Not investing in further select automation
