### ISSUE TITLE
select: pickup followup requests based on description or for a failing to build package

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#811]
Followup request, those created after issues are seen in a staging, are quite common and would nice to have a more automated method for handling them. Using a special syntax in the description text seems like a nice convenience.

Some possible examples/patterns (perhaps support a few):

- Followup for KDE:Frameworks5 in Staging:E.
- (Stage|Place) in Staging:E
- (Followup )?for(.* in)? Staging:E

These followup requests could be restricted in a few ways to help alleviate abuse and what not.

- Restricted to project/package maintainers so a slightly more trusted user which would prevent random requests from being created and staged all over. Although, likely the request would end up being duplicate and ignored anyway.
- Maintain the automatic 8 hour staging window or if staging is in the state `failed`.

If a request is made for a package failing to build in only one of the stagings, or if not too tricky a dependency of a failing package, it should be placed in that staging.

**Comment by jberry-suse** [comment]
Also worth considering is lifting the `--merge` window for `devel` or `super` so that **all** followup requests are included. I can see this being really handy and potentially annoying. Could end up just getting a trickle of requests at such an interval that the staging never finishes building. Although in many cases that may be the only legitimate way forward. Another possibility would be to just increase it to a much longer period like a week.

**Comment by jberry-suse** [comment]
A simplified version that may be helpful before a more complex algorithm can be implemented would be a slight tweak of the last comment. Where the window is lifted if that staging is not in an `acceptable` state.

**Comment by jberry-suse** [comment]
The followup descriptions could also be used in conjunction with a tool that looks for un-resolvable requests (many times in `adi`s, especially for Leap) that simply need another package submitted. Having a preference order of sources and generate a submit with the reason it was generated in description so it gets staged properly. I find I do this manually already.

**Comment by jberry-suse** [comment]
Also comments on staging projects many times have links or markdown reference to needed requests.

**Comment by jberry-suse** [comment]
Comments can be all over https://build.opensuse.org/request/show/519533

**Comment by coolo** [comment]
For reasons as this we are currently (for quite a while actually) running without automated staging
