### ISSUE TITLE
select: evaluate supersede logic to determine if still desired

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#851]
There is supersede logic in select that follows a different path from the logic in `stagingapi`. It only checks if the new request ID is larger than the one already staged. In general this distinction seems arbitrary and for Leap likely makes even less sense. With the exposing of the other `supersede` functionality via its own command that would seem preferred over some sort of logic in `select`.

From reading the code, it would seem it allows for one to do an implicit move from one staging to another as long as there is an open request that is considered superseding (greater ID and same target package). The code shares the path of move which is intriguing.

Unless I am mistake the logic seems a bit off (and the message backwards). The final call:

```python
self.api.move_between_project(fprj, request, self.target_project)
```
for a `--move` makes sense, but supersede:

- `fprj` will be the project containing an older request for same package
- `request` (should be `request_id`) ID of newer request
- `target_project` the argument from command line

The message seems backwards:

```python
print('"{} ({}) is superseded by {}'.format(request, supersede[1], supersede[0]))
# new_request_id (package) is superseded by old_request_id
```

The move code, unless I am mistaken, tries to remove the new request ID from the specified project. This should fail since it is not staged there and so it ends up doing nothing, but prints seemingly misleading message about `superseded` and `moving`.

Assuming no one is running into this since I believe one would have to issue a rather unusual command in order to do so. I simply decided to review while I was tweaking the supersede logic for #842. The original commits reference a "corner case" and the code was changed several times.

Forcing `_supersede()` to always `return None` does not cause any test failures that might help illuminate the reasoning. Has anyone seen the `superseded` message printed from `select` before or have some light to shed on this?

**Comment by jberry-suse** [comment]
Besides removing potential cruft this would also drop an OBS request per request to be staged.

**Comment by jberry-suse** [comment]
Found the [original description](https://progress.opensuse.org/issues/1785):

> Corner case for select:
> 
> - Package Pkg is selected to be in staging project A (reviewed in project o:F:S:A)
> - A new revision of A supersede the one in o:F:S:A
> - The release manager decides to put the new version in o:F:S:B
> - Work to do: select need to detect this case and convert that to a Move From A to B

That's basically the gist I was thinking, but the code does not seem to support that (at least in current state) since `move_between_project()` checks if the request is in the from project which the new request clearly would not be.

Confirming the reasoning is handy. Is this something that makes sense to support? Seems like one should either supersede or move, but not both in a single action. If so the logic should be fixed to function properly.

**Comment by lnussel** [comment]
as long as the code produces a consistent state (ie doesn't select the package into two stagings at the same time) I'm fine with requring separate commands. I can't remember running into this myself though.

**Comment by coolo** [comment]
the OBS API handles this meanwhile
