### ISSUE TITLE
staging-bot: consider mirroring ignored status for requests pending Factory acceptance

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#874]
For example [`installation-images`](https://build.opensuse.org/request/show/491875) has a pending Factory request that is marked as ignored and it will remain pending until Factory is accepted. It would seem to make sense to mark it as ignored for the same reason as Factory.

Leaper has the necessary context, but would require giving leaper permission to write to `dashboard/ignored_requests`. Alternatively, this could be added to `ignore` command or similar. Even a special mode of `leaper.py` that would only add to ignored.

If the request is selected it should be unselected. As such it may make sense to be part of `unselect --cleanup` or under a new flag.

Regardless of how it is implemented any reasons for not mirroring the ignored state?

**Comment by jberry-suse** [comment]
Should likely make more sense as a `staging-bot` addition since it has the proper permissions. Could be part of `OSRT:Config` something like `mirror-ignore-from: openSUSE:Factory`. Likely does not make sense in leaper/origin manager since will not want to mirror from another other origin anyway (plus no access to IBS).

**Comment by coolo** [comment]
I'm a little confused about it, but I guess this talks about mirroring from Factory to Leap - which no longer applies
