### ISSUE TITLE
Is ?expand=1 useful for /source/<project> calls that only look at package name?

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#907]
As discovered in #906 a variety of scripts have a copy of this method with `{'expand': 1}` while `StagingAPI` has effectively the same code without the `expand` option. Looking at the output from the API call the list of packages for `openSUSE:Factory` is identical in length, but includes `originproject` attribute which is completely ignored by the code. The call also appears to run quite a bit slower with the `expand` option so if it is unnecessary as it would appear it should be dropped.

```python
def get_source_packages(self, project):
    """Return the list of packages in a project."""
    query = {'expand': 1}
    root = ET.parse(http_GET(makeurl(self.apiurl,['source', project],
                              query=query))).getroot()
    packages = [i.get('name') for i in root.findall('entry')]

    return packages
```

**Comment by lnussel** [comment]
depends on the context. expand is relevant if the code is meant to follow project links. If it ignored linked projects anyways the expand can be removed.

**Comment by coolo** [comment]
as explained
