### ISSUE TITLE
Create requests to solve un-resolvable packages where the package does not exist in target project

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#910]
Using a prioritized list of sources generate a request to submit a new package to the target project.

I do this regularly for Leap. Today I created to requests before stopping deciding it should just be automated.

- created sr#495122: followup for love
- created sr#495123: followup for libguestfs

Combined with #811 description based followup staging should make for a rather nice workflow.

For Leap, priorities should be something like the following (and triggering a required package update makes more sense as well).

- SLE
- Factory

For Factory simply:

- devel projects
  - same as un-resolvable package, otherwise
  - alphabetical order to keeping it consistent (could either skip this or try and fallback to repo inspect)

Obviously, block if existing request for the required package in question.

**Comment by coolo** [comment]
As we meanwhile did 2 leap versions without this feature - maybe we don't need it? @lnussel @nilxam

**Comment by jberry-suse** [comment]
Also did many version without staging-bot. Just a matter of how much manual tediousness one has to deal with.
