### ISSUE TITLE
Do not allow both a change_devel and submit request for the same target package at the same time

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#913]
Factory managed to trigger the different source project logic that I added to supersede for Leap. See https://build.opensuse.org/request/show/495521.

- submit
- change_devel accepted
- submit from new devel was ignored per logic

It seems the same code that checks that requests are from a devel project should decline a request of either type that is sent (or in real terms reviewed) after a request of a different type for the same target package. The submitter may then decide the order in which they wish to proceed and decline the original request and re-submit if necessary.

**Comment by coolo** [comment]
That's sub P7
