### ISSUE TITLE
two requests for the same package

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#915]
$ osc rq list openSUSE:Leap:42.3 elementary-icon-theme
495763  State:new        By:staging-bot  When:2017-05-18T03:51:54
        submit:          X11:Pantheon/elementary-icon-theme@19 ->           openSUSE:Leap:42.3
        Review by User       is accepted:  leaper(leaper)                                    
        Review by Group      is accepted:  factory-staging(staging-bot)                      
        Review by Group      is accepted:  leap-reviewers(jberry)                            
        Review by Project    is accepted:  openSUSE:Leap:42.3:Staging:adi:10(staging-bot)    
        Comment: ready to accept 

496427  State:new        By:staging-bot  When:2017-05-18T23:34:12
        submit:          openSUSE:Factory/elementary-icon-theme@14300b4aaea4ee42a2659201a11f35b5 -> openSUSE:Leap:42.3
        Review by User       is accepted:  leaper(leaper)                                    
        Review by Group      is accepted:  factory-staging(staging-bot)                      
        Review by Project    is accepted:  openSUSE:Leap:42.3:Staging:adi:25(staging-bot)    
        Review by Package    is accepted:  X11:Pantheon/elementary-icon-theme(XRevan86)      
        Review by Group      is accepted:  leap-reviewers(jberry)                            
        Descr: Automatic request from openSUSE:Factory by UpdateCrawler
        Comment: ready to accept 

$ osc staging -p openSUSE:Leap:42.3 accept
Accepting request 495763: elementary-icon-theme
Server returned an error: HTTP Error 400: Bad Request
The source of package X11:Pantheon/elementary-icon-theme for revision 19 is broken

**Comment by jberry-suse** [comment]
The first being "ready to accept" before the second came in. Presumably this is a general adi workflow consideration, but I would have expected to see it before now.

What is the desired behavior in this case? Supersede the already "ready to accept" request or prevent the new one form being marked "ready to accept" until the original is actually accepted?

**Comment by DimStar77** [comment]
supersede sounds like the most obvious thing to me - if they user would have created the submission using osc instead of webui, he'd likely have been asked anyway to supersede the old one (and he'd had answered yes)

**Comment by jberry-suse** [comment]
This is something that the one of the bots in Factory does right? I've seen it happen to my requests.

**Comment by DimStar77** [comment]
yes - I'm pretty sure that one does not look at the status if the old one would already be 'ready to accept'

**Comment by lkocman** [comment]
I suppose some improvements already happened right @coolo ? At least I recall you mentioning some progress on -co-op on 000product in SLE. Is this still relevant then?

**Comment by coolo** [comment]
we kind of made this obsolete by no longer accepting adi projects early.
