### ISSUE TITLE
manager42/update crawler catch origin changes in maintenance

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#918]
maintenance changed origin of python-Pygments in 42.2 by accepting a request but failed to also submit to 42.3, so the update was missed. Maybe we can catch such cases in manager42 or update crawler.

**Comment by jberry-suse** [comment]
Post #1636 `leaper` has basic support for maintenance and you indicate maintenance manually maintains the lookup file. I'd say that solves the title and further work should probably go into the rewrite and merger of these tools which I'll collect in #1643.
