### ISSUE TITLE
Create escalation system for build failures and repo_checker discoveries

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#933]
As the last escalation step a bug should be created for packages with build failures.

**Comment by jberry-suse** [comment]
More fleshed out and agreed upon during `2017-08-15` release team meeting.

- week 1: comment
- week 2: mail
- week 3: mail reminder
- week 4: bug report
- week 6: delete request

Comments and mail are already implement for build failures, and just comments for `repo_checker` discoveries. The mail code should be generalized along with the bug creation code from `issue-diff.py`.

**Comment by lnussel** [comment]
👍

**Comment by coolo** [comment]
I would remove the comment step - they are problematic in general (OBS lacks some features, but they are also hitting too often the wrong people). So IMO merging the installcheck problems into the build fail reminder is the goal IMO.
