### ISSUE TITLE
risk: include whatdependson summary in reviews (especially delete requests)

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#943]
Seems like how many packages depend on a package is typically an important indicator of how risky an update would be. Several python packages have been in that category, but short of manually checking or knowing of the top of one's head there is no easy indication.

**Comment by jberry-suse** [comment]
Similarly, on delete including a note about the package existing in Factory would be helpful.

**Comment by coolo** [comment]
No longer relevant with closed leap gap
