### ISSUE TITLE
risk: ideas for risk assessment tool

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#944]
@lnussel and I have bounced around the idea of reworking the leaper bot based on the current usage as the code is rather ungainly.

From performing a large number of `leap-reviewers` reviews it seems clear there are classes of updates that should not require human review (like SLE updates) from the perspective of is the update desirable for Leap. Instead only relevant for technical/legal or maintainer sign off. Otherwise, it simply becomes a nuisance to weed through loads of requests that simply should be accepted.

The leaper bot could be reworked to generate a risk and/or badness index (related #943) and only require human review for packages above a certain threshold. Seems more a nuisance to require `leap-reviewer` reviews of KDE LTS updates which are clearly alright from a leap perspective.

The primary areas for concern of origin changes, delete requests. Origin change include major version updates for packages inherited from previous Leap version. Packages that are tracking Factory or a special Leap devel are unobjectionable from the `leap-reviewers` perspective.

Generally, the sources for Leap packages are from places that have already had human review and the only decision to make from the Leap perspective is do we want to support this or is this compatible with the rest of Leap. Combined with a way to shut-off update crawler requests #942 should make for a much smoother daily operation.

Likely, it makes sense to start developing these indexes and outputting additional information that went into the index and if manual review confirms these indexes then the bot can be switched to utilize the index for deciding when to require the review.

**Comment by lnussel** [comment]
Now that we are getting closer to the release it may be desirable to do more and stricter reviews actually.  At some point even a KDE lts update may no longer be desiable. The question then just is at which level to decline.

**Comment by jberry-suse** [comment]
This was intended for next Leap cycle as I do not expect to get to this soon, but a good note to plan for dialing back setting for next cycle.

**Comment by jberry-suse** [comment]
The more I've run into the issue leaper really needs to be able to check for parallel requests to SLE especially since that is the encouraged workflow now.

**Comment by jberry-suse** [comment]
Broke off origin-manager issue, refocused to risk assessment tool, and removed from origin manager milestone.

**Comment by coolo** [comment]
No longer relevant with closed leap gap
