### ISSUE TITLE
update-crawler: generate delete requests for obsoleted packages

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#945]
Seems like these delete requests should be generated automatically. The output of `installcheck` contains the required indications.

```
can't install srptools-1.0.2-4.3.x86_64:
  package is obsoleted by srp_daemon-14-6.1.x86_64
can't install jakarta-commons-pool-1.3-115.19.noarch:
  package is obsoleted by apache-commons-pool-1.6-1.21.noarch
can't install python3-dateutil-2.4.2-4.1.noarch:
  package is obsoleted by python3-python-dateutil-2.6.0-2.1.noarch
can't install openh323-devel-1.19.0.1-4.1.x86_64:
  package is obsoleted by h323plus-devel-1.26.5-5.1.x86_64
can't install kipi-plugins5-5.0.0~beta5-3.4.x86_64:
  package is obsoleted by kipi-plugins-5.5.0-2.5.x86_64
```

Any reason to keep the obsoleted packages?

**Comment by jberry-suse** [comment]
Using very early prototype I generated the following 18 delete requests for Leap 42.3.

```
openh323 506349
baloo 506350
jaxen-bootstrap 506351
baloo 506352
ghostscript-mini 506353
akonadi-runtime 506354
xdg-app 506355
perl-version 506356
synaptiks 506357
kdebase4-workspace 506358
python-dateutil 506359
baloo 506360
kdebase4-workspace 506361
python3-xdg 506362
lxdm 506363
kdepim4-runtime 506364
python3-kde4 506365
kdebase4-workspace 506366
```

The prototype would benefit from:

- a rpm name to package map (reverse of existing API calls, perhaps keep map from #952)
- merging multiple deletes into one with all relevant reason text
- checking for existing delete requests

Definitely rough, but more fun then making them by hand.

**Comment by jberry-suse** [comment]
Would also make sense to share the same check as `cleanup_rings` that repo-checker of which `repo-checker `contains half to ensure a delete is safe before creating it.

**Comment by jberry-suse** [comment]
Also seems some of the installcheck failures are simply tolerated/expected. Would seem to make sense to disable generating the subpackages that are not intended to be installed.

**Comment by jberry-suse** [comment]
Half ended up being valid so not bad. The others are "half valid" since certain subpackages are used, but not all. Seems like those packages should be fixed.

**Comment by lnussel** [comment]
Ideally some bot would detect the situation already when a new package that obsoletes another one gets submitted.  Those packages are not really not installable. They would just be replaced by the next zypper up. Nevertheless the admin could lock them if a specific version is required.

**Comment by jberry-suse** [comment]
This should be caught be repochecker's installcheck, well at least for packages grouped together (ie ring or adi groups), but would miss issues in other packages just the same as the rest of the staging workflow.

**Comment by lnussel** [comment]
it's probably something for the build fail reminder actually. it also needs to handle install fails, not just rebuild fails anyways.

**Comment by coolo** [comment]
I would prefer using build fail reminder to picking up installcheck problems over the comments we use now.
