### ISSUE TITLE
repo_checker: invoke mirror, cycle, and install checks in parallel

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#974]
All three of these processes take a long time and are not related so it should be feasible to run them in parallel for a significant performance gain. (targeting the new repo_checker form #964)

It is not clear if allowing `ReviewBot` itself to operate in parallel while `repo_checker` blocks at `ensure_group()` for the same group so each group is only checked once. `ReviewBot` would then loop through reviews until all groups are blocked and un-block as they complete.

Alternatively, the parallelism could be added to `repo_checker` only by a small restructure to call `ensure_group()` as part of `prepare_review()`. This case has the benefit of more direct control, but I wonder if other bots would benefit from running in parallel or if OBS would dislike the number of concurrent requests.

The other consideration is the amount of resources available on packagelists as the checks take > 1GB of ram and lock up a CPU core. Having `installcheck` itself run in parallel would be nice as it takes the longest by far.

**Comment by lnussel** [comment]
repo_checker could create work packages but don't do the work itself. Then we could have workers that perform the actual checks. Wit that we could spawn as many workers as the machine permits.

**Comment by jberry-suse** [comment]
Does the machine have enough resources to handle process more than one group at a time? Otherwise, we'd need to use a proper scheduler and multiple workers.

**Comment by coolo** [comment]
this is what we do on gocd now

**Comment by jberry-suse** [comment]
Each staging project is done is parallel right? Which is not the same, but more useful

**Comment by coolo** [comment]
I was refering to 'proper scheduler and multiple workers'
