### ISSUE TITLE
leaper: prevent non-incremental updates

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#982]
leap should e.g. add leap-reviewers if a change from SLE looks like a revert, eg. sr#507319

**Comment by jberry-suse** [comment]
What specifically constitutes a revert for this purpose? A smaller version number than before? Pure loss of changelog entries, majority loss, or any loss?

**Comment by lnussel** [comment]
maybe even just non-incremental changelog

**Comment by jberry-suse** [comment]
So `count('-' in changelog diff) >= 0`?

**Comment by jberry-suse** [comment]
Handled in origin manager (the root else):

https://github.com/openSUSE/openSUSE-release-tools/blob/214f8bbc2ae41b30e2a3517229b5c187298f3fe5/osclib/origin.py#L437-L441
